package io.github.erkko68.filament

import io.github.erkko68.filament.interop.*

/**
 * Material defines the visual appearance of a surface.
 *
 * Materials are created from a binary blob generated by the material compiler (matc).
 * A Material is a template from which MaterialInstance objects can be created.
 *
 * **Creating instances:**
 * Use createInstance() to spawn an instance from this material. Instances inherit the material's
 * properties but can override parameters (color, texture, etc.) for per-object customization.
 * Always destroy instances with Engine.destroy() before destroying the material.
 *
 * **Material compilation:**
 * Use compile() to asynchronously compile specific material variants. This is useful for
 * precompiling variants you know will be used, reducing first-time rendering stalls.
 * After issuing multiple compile() calls, call Engine.flush() so the backend can start
 * compilation work.
 *
 * **Material properties:**
 * Material properties are read-only and determined at compile time from the matc-generated blob.
 * These include shading model, blending mode, transparency mode, and other rendering settings.
 * To override parameters per-instance, use MaterialInstance.
 */
class Material @InternalFilamentApi constructor(internal var nativeHandle: NativePointer) {
    /** The native object, for interop with code calling the Fila* C API directly. Read-only: this wrapper owns it. */
    @InternalFilamentApi
    val nativeObject: NativePointer get() = nativeHandle

    /**
     * Shading model determines how light interacts with the material surface.
     *
     * - UNLIT: No lighting applied; emissive possible. Useful for UI, billboards, glow effects
     * - LIT: Standard physically-based lighting (default)
     * - SUBSURFACE: Subsurface scattering for thin materials (skin, leaves, paper)
     * - CLOTH: Cloth-specific lighting model for fabric appearance
     * - SPECULAR_GLOSSINESS: Legacy shading model (use LIT for new materials)
     */
    enum class Shading { UNLIT, LIT, SUBSURFACE, CLOTH, SPECULAR_GLOSSINESS }
    /**
     * Attribute interpolation type in the fragment shader.
     *
     * - SMOOTH: Smooth interpolation (default); values smoothly transition across primitives
     * - FLAT: Flat interpolation; values are constant per primitive (no interpolation)
     */
    enum class Interpolation { SMOOTH, FLAT }
    /**
     * Blending mode determines how a material's color is combined with the background.
     *
     * - OPAQUE: Material is opaque; fully solid (default)
     * - TRANSPARENT: Transparent with alpha pre-multiplication; affects diffuse lighting only
     * - ADD: Additive blending (e.g., hologram, glow)
     * - MASKED: Alpha-tested (either fully opaque or fully transparent per pixel)
     * - FADE: Transparent with alpha pre-multiplication; affects specular lighting
     * - MULTIPLY: Darkens what's behind it
     * - SCREEN: Brightens what's behind it
     */
    enum class BlendingMode { OPAQUE, TRANSPARENT, ADD, MASKED, FADE, MULTIPLY, SCREEN }
    /**
     * How transparent objects are rendered.
     *
     * - DEFAULT: Transparent object drawn honoring the raster state
     * - TWO_PASSES_ONE_SIDE: Object drawn in depth buffer, then color buffer with culling honored but depth test ignored
     * - TWO_PASSES_TWO_SIDES: Object drawn twice in color buffer (back faces, then front faces); culling ignored
     */
    enum class TransparencyMode { DEFAULT, TWO_PASSES_ONE_SIDE, TWO_PASSES_TWO_SIDES }
    /**
     * Refraction rendering mode.
     *
     * - NONE: No refraction
     * - CUBEMAP: Use cubemap for refraction (requires pre-captured environment)
     * - SCREEN_SPACE: Real-time screen-space refraction (can be expensive)
     */
    enum class RefractionMode { NONE, CUBEMAP, SCREEN_SPACE }
    /**
     * Type of refracted surface.
     *
     * - SOLID: Thick solid material (refraction assumes finite thickness)
     * - THIN: Thin material like glass (refraction assumes thin surface)
     */
    enum class RefractionType { SOLID, THIN }
    /**
     * Reflection rendering mode.
     *
     * - DEFAULT: Use standard reflection (cubemap or IBL)
     * - SCREEN_SPACE: Real-time screen-space reflections (can be expensive)
     */
    enum class ReflectionMode { DEFAULT, SCREEN_SPACE }
    /**
     * Vertex domain specifies which coordinate space vertices are defined in.
     *
     * - OBJECT: Vertices in object space (default)
     * - WORLD: Vertices in world space
     * - VIEW: Vertices in view/camera space
     * - DEVICE: Vertices in normalized device coordinates ([-1, 1])
     */
    enum class VertexDomain { OBJECT, WORLD, VIEW, DEVICE }
    /**
     * Culling mode determines which faces are rendered.
     *
     * - NONE: Both front and back faces rendered (disables culling)
     * - FRONT: Cull front faces; only back faces rendered
     * - BACK: Cull back faces; only front faces rendered (default)
     * - FRONT_AND_BACK: Cull all faces (usually used for testing or special effects)
     */
    enum class CullingMode { NONE, FRONT, BACK, FRONT_AND_BACK }
    /**
     * Priority queue for asynchronous material compilation.
     *
     * - CRITICAL: Highest priority; compiles immediately
     * - HIGH: High priority; compiles before LOW queue
     * - LOW: Low priority; compiles last
     *
     * @see compile
     */
    enum class CompilerPriorityQueue { CRITICAL, HIGH, LOW }
    /**
     * UBO batching mode controls whether material instances share uniform buffers.
     *
     * - DEFAULT: Use engine settings; if UBO batching is enabled and material domain is SURFACE, enable it
     * - DISABLED: Disable UBO batching for this material (each instance gets its own uniform buffer)
     */
    enum class UboBatchingMode { DEFAULT, DISABLED }

    /**
     * User variant filter bits for material compilation.
     *
     * These bits control which material variants are compiled. Using only required variants
     * saves compilation time and memory. For example, if your app doesn't use stereoscopic rendering,
     * clear the STE bit.
     */
    object UserVariantFilterBit {
        /** Variant for directional lighting */
        val DIRECTIONAL_LIGHTING: Int = 0x01
        /**
         * Variant for dynamic (local) lighting. Since 1.76.0 dynamic lighting is a
         * specialization constant, so this no longer shrinks offline `.filamat` blobs —
         * it only prunes runtime pipeline compilations.
         */
        val DYNAMIC_LIGHTING: Int = 0x02
        /** Variant for shadow-receiving objects */
        val SHADOW_RECEIVER: Int = 0x04
        /** Variant for skinned/skeletal animation */
        val SKINNING: Int = 0x08
        /** Variant for fog effects */
        val FOG: Int = 0x10
        /** Variant for Variance Shadow Maps */
        val VSM: Int = 0x20
        /** Variant for Screen-Space Reflections */
        val SSR: Int = 0x40
        /** Variant for stereoscopic rendering */
        val STE: Int = 0x80
        /** All variants combined */
        val ALL: Int = 0xFF
    }

    /**
     * Holds metadata about a material parameter.
     *
     * Parameters are created during material compilation and define customizable properties
     * like textures, colors, or numeric values that can be set per instance.
     */
    class Parameter(
        /** Name of the parameter as defined in the material */
        val name: String,
        /** Data type of the parameter */
        val type: Type,
        /** Precision (if a numeric type) */
        val precision: Precision,
        /** Array count (1 if not an array) */
        val count: Int
    ) {

        /**
         * Parameter data types.
         *
         * - BOOL/BOOL2/BOOL3/BOOL4: Boolean scalar or vector
         * - FLOAT/FLOAT2/FLOAT3/FLOAT4: Floating-point scalar or vector
         * - INT/INT2/INT3/INT4: Signed integer scalar or vector
         * - UINT/UINT2/UINT3/UINT4: Unsigned integer scalar or vector
         * - MAT3/MAT4: 3x3 or 4x4 floating-point matrix
         * - SAMPLER_2D/SAMPLER_2D_ARRAY/SAMPLER_CUBEMAP/SAMPLER_EXTERNAL/SAMPLER_3D: Texture sampler
         * - SUBPASS_INPUT: Input attachment for rendering
         */
        enum class Type {
            BOOL, BOOL2, BOOL3, BOOL4,
            FLOAT, FLOAT2, FLOAT3, FLOAT4,
            INT, INT2, INT3, INT4,
            UINT, UINT2, UINT3, UINT4,
            MAT3, MAT4,
            SAMPLER_2D, SAMPLER_2D_ARRAY, SAMPLER_CUBEMAP, SAMPLER_EXTERNAL, SAMPLER_3D,
            SUBPASS_INPUT
        }
        /**
         * Precision level for numeric parameters.
         *
         * - LOW: Low precision (may reduce quality but improve performance)
         * - MEDIUM: Medium precision
         * - HIGH: High precision
         * - DEFAULT: Use engine default
         */
        enum class Precision { LOW, MEDIUM, HIGH, DEFAULT }
    }

    /**
     * Builder for creating Material objects from compiled material packages.
     *
     * The Builder takes a material package (binary blob from the matc compiler) and
     * configures rendering quality and batching options before building the final Material.
     */
    class Builder() {
        private val nativeBuilder = FilaMaterial_Builder_create()
        // Set in payload(): a non-empty blob that isn't a compiled .filamat. build() rejects it before
        // calling Filament's parser, which would otherwise panic uncatchably (see isValidFilamatPayload).
        private var payloadInvalid = false
        // Filament's Builder::package keeps the pointer (no copy) until build(), so the payload lives until then.
        private var payloadScope: InteropScope? = null
        /**
         * Shadow sampling quality affects how soft shadows are rendered.
         *
         * - HARD: 2x2 PCF (Percentage Closer Filtering); faster but harder shadows
         * - LOW: 3x3 Gaussian filter; slower but softer, smoother shadows
         */
        enum class ShadowSamplingQuality { HARD, LOW }

        /**
         * Specifies the material data (compiled binary blob).
         *
         * The material data is a binary blob produced by libfilamat or by matc (the material compiler).
         *
         * @param data Pointer to the material data; must stay valid until build() is called
         * @return This Builder, for chaining calls
         */
        fun payload(data: ByteArray): Builder = apply {
            if (data.isNotEmpty()) {
                payloadInvalid = !isValidFilamatPayload(data)
                releasePayload()
                payloadScope = InteropScope().also { FilaMaterial_Builder_package(nativeBuilder, it.toInterop(data), data.size) }
            } else {
                payloadInvalid = false
            }
        }
        /**
         * Sets the quality of the indirect light computations.
         *
         * This is only taken into account if the material is lit and in the surface domain.
         * This setting affects the IndirectLight computation if one is specified on the Scene
         * and Spherical Harmonics are used for the irradiance.
         *
         * @param shBandCount Number of spherical harmonic bands. Must be 1, 2 or 3 (default).
         * @return This Builder, for chaining calls.
         *
         * @see IndirectLight
         */
        fun sphericalHarmonicsBandCount(shBandCount: Int): Builder = apply {
            FilaMaterial_Builder_sphericalHarmonicsBandCount(nativeBuilder, shBandCount)
        }
        /**
         * Set the quality of shadow sampling.
         *
         * This is only taken into account if the material is lit and in the surface domain.
         *
         * @param quality Shadow sampling quality
         * @return This Builder, for chaining calls.
         */
        fun shadowSamplingQuality(quality: ShadowSamplingQuality): Builder = apply {
            FilaMaterial_Builder_shadowSamplingQuality(nativeBuilder, quality.ordinal)
        }
        /**
         * Set the batching mode of the instances created from this material.
         *
         * @param mode Batching mode to use
         * @return This Builder, for chaining calls.
         */
        fun uboBatching(mode: UboBatchingMode): Builder = apply {
            FilaMaterial_Builder_uboBatching(nativeBuilder, mode.ordinal)
        }
        private fun releasePayload() {
            payloadScope?.release()
            payloadScope = null
        }

        /**
         * Creates the Material and returns it.
         *
         * @param engine Engine to associate this Material with
         * @return The newly created Material
         * @throws IllegalArgumentException if the [payload] is not a valid compiled `.filamat`. The
         *   payload is checked before Filament's parser can panic, so callers can recover (e.g. return
         *   null + report an error) rather than crash the process.
         */
        fun build(engine: Engine): Material {
            if (payloadInvalid) {
                releasePayload()
                FilaMaterial_Builder_destroy(nativeBuilder)
                throw IllegalArgumentException(
                    "Failed to build material — the payload is not a valid compiled .filamat",
                )
            }
            val handle = FilaMaterial_Builder_build(nativeBuilder, engine.nativeHandle)
            FilaMaterial_Builder_destroy(nativeBuilder)
            releasePayload()
            if (handle == NullPointer) {
                throw IllegalArgumentException(
                    "Failed to build material — the payload is not a valid compiled .filamat",
                )
            }
            return Material(handle)
        }
    }

    /**
     * Asynchronously compile a subset of this Material's variants.
     *
     * After issuing several compile() calls, it is recommended to call Engine.flush() so the
     * backend can start compilation work as soon as possible. The provided callback is guaranteed
     * to be called on the main thread after all specified variants are compiled. This can take
     * hundreds of milliseconds.
     *
     * If all variants are already compiled, the callback is scheduled as soon as possible, but
     * this might take a few dozen milliseconds depending on backend queue depth.
     *
     * If the same variant is scheduled for compilation multiple times, the first scheduling takes
     * precedence; later scheduling is ignored.
     *
     * **Note:** If you intend to override specialization constants on a per-MaterialInstance basis
     * via MaterialInstance, the programs compiled here may not be reusable. Call
     * MaterialInstance.compile() instead in those cases.
     *
     * @param priority Which priority queue to use (CRITICAL, HIGH, or LOW).
     * @param variants Variants to compile (bitmask of UserVariantFilterBit values, or UserVariantFilterBit.ALL).
     * @param callback Optional callback invoked on main thread when compilation completes.
     */
    fun compile(priority: CompilerPriorityQueue, variants: Int, callback: (() -> Unit)? = null) {
        if (callback == null) {
            FilaMaterial_compile(nativeHandle, priority.ordinal, variants, NullPointer, NullPointer, NullPointer)
        } else {
            val userData = Callbacks.register(once = true) { _ -> callback() }
            FilaMaterial_compile(nativeHandle, priority.ordinal, variants, NullPointer, Callbacks.argUser, userData)
        }
    }

    /**
     * Create a new MaterialInstance from this material.
     *
     * Instances inherit all material properties but can override parameters for per-object
     * customization. Multiple instances can be created from a single material. Always destroy
     * instances with Engine.destroy() when no longer needed.
     *
     * @return A new MaterialInstance with default parameters.
     */
    fun createInstance(): MaterialInstance = MaterialInstance(FilaMaterial_createInstance(nativeHandle))
    /**
     * Create a new MaterialInstance with an optional debug name.
     *
     * The name can be used for debugging/profiling purposes.
     *
     * @param name Debug name for this instance (if empty, inherits material name).
     * @return A new MaterialInstance with the given name.
     */
    fun createInstance(name: String): MaterialInstance = MaterialInstance(name.useCString { FilaMaterial_createInstanceWithName(nativeHandle, it) })
    /**
     * Get this material's default instance.
     *
     * The default instance is used for setDefaultParameter() calls on the Material itself.
     * Changes to the default instance affect all MaterialInstances that don't override those
     * parameters. The default instance is owned and managed by this Material.
     *
     * @return The default MaterialInstance.
     */
    val defaultInstance: MaterialInstance get() = MaterialInstance(FilaMaterial_getDefaultInstance(nativeHandle))

    /**
     * Get the name of this material.
     *
     * @return Material name string (from the matc-compiled blob).
     */
    val name: String get() = stringFromInterop(FilaMaterial_getName(nativeHandle)) ?: ""
    /** Get the shading model. */
    val shading: Shading get() = Shading.entries[FilaMaterial_getShading(nativeHandle)]
    /** Get the vertex attribute interpolation mode. */
    val interpolation: Interpolation get() = Interpolation.entries[FilaMaterial_getInterpolation(nativeHandle)]
    /** Get the blending mode. */
    val blendingMode: BlendingMode get() = BlendingMode.entries[FilaMaterial_getBlendingMode(nativeHandle)]
    /** Get the transparency rendering mode (only relevant for TRANSPARENT/FADE blending). */
    val transparencyMode: TransparencyMode get() = TransparencyMode.entries[FilaMaterial_getTransparencyMode(nativeHandle)]
    /** Get the refraction mode. */
    val refractionMode: RefractionMode get() = RefractionMode.entries[FilaMaterial_getRefractionMode(nativeHandle)]
    /** Get the refraction surface type. */
    val refractionType: RefractionType get() = RefractionType.entries[FilaMaterial_getRefractionType(nativeHandle)]
    /** Get the reflection mode. */
    val reflectionMode: ReflectionMode get() = ReflectionMode.entries[FilaMaterial_getReflectionMode(nativeHandle)]
    /** Get the vertex coordinate space domain. */
    val vertexDomain: VertexDomain get() = VertexDomain.entries[FilaMaterial_getVertexDomain(nativeHandle)]
    /** Get the face culling mode. */
    val cullingMode: CullingMode get() = CullingMode.entries[FilaMaterial_getCullingMode(nativeHandle)]
    
    /** Check if color writes are enabled. Default is true. */
    val isColorWriteEnabled: Boolean get() = FilaMaterial_isColorWriteEnabled(nativeHandle)
    /** Check if depth writes are enabled. Default is true. */
    val isDepthWriteEnabled: Boolean get() = FilaMaterial_isDepthWriteEnabled(nativeHandle)
    /** Check if depth testing is enabled. Default is true. */
    val isDepthCullingEnabled: Boolean get() = FilaMaterial_isDepthCullingEnabled(nativeHandle)
    /** Check if this material renders both front and back faces (double-sided). Default is false (back culling). */
    val isDoubleSided: Boolean get() = FilaMaterial_isDoubleSided(nativeHandle)
    /**
     * Check if alpha-to-coverage is enabled.
     *
     * Alpha-to-coverage converts alpha values to a coverage mask for MSAA, improving
     * transparency rendering quality with MSAA.
     */
    val isAlphaToCoverageEnabled: Boolean get() = FilaMaterial_isAlphaToCoverageEnabled(nativeHandle)
    
    /**
     * Get the alpha threshold for MASKED blending mode.
     *
     * Pixels with alpha >= threshold are rendered as fully opaque; below threshold are fully transparent.
     *
     * @return Threshold value in [0, 1].
     */
    val maskThreshold: Float get() = FilaMaterial_getMaskThreshold(nativeHandle)
    /**
     * Get the specular anti-aliasing variance.
     *
     * Lower values reduce specular aliasing but may blur highlights.
     *
     * @return Variance in [0, 1].
     */
    val specularAntiAliasingVariance: Float get() = FilaMaterial_getSpecularAntiAliasingVariance(nativeHandle)
    /**
     * Get the specular anti-aliasing threshold.
     *
     * Clamps specular aliasing reduction to avoid over-blurring.
     *
     * @return Threshold in [0, 1].
     */
    val specularAntiAliasingThreshold: Float get() = FilaMaterial_getSpecularAntiAliasingThreshold(nativeHandle)
    /** Get the minimum required feature level for this material. */
    val featureLevel: Engine.FeatureLevel get() = Engine.FeatureLevel.entries[FilaMaterial_getFeatureLevel(nativeHandle)]
    
    /**
     * Get the number of parameters declared by this material.
     *
     * @return Parameter count (0 if the material has no parameters).
     */
    val parameterCount: Int get() = FilaMaterial_getParameterCount(nativeHandle)

    /**
     * Get metadata about all parameters declared by this material.
     *
     * @return List of Parameter objects describing each parameter.
     */
    val parameters: List<Parameter> get() {
        val count = parameterCount
        if (count == 0) return emptyList()
        // Five ints per parameter: isSampler, isSubpass, type, count, precision.
        val info = IntArray(count * 5)
        val n = info.usePinned { FilaMaterial_getParameters(nativeHandle, it, count) }
        return (0 until n).map { i ->
            val o = i * 5
            Parameter(
                stringFromInterop(FilaMaterial_getParameterName(nativeHandle, i)) ?: "",
                materialParameterType(info[o + 2], info[o] != 0, info[o + 1] != 0),
                Parameter.Precision.entries[info[o + 4]],
                info[o + 3],
            )
        }
    }

    /**
     * Get the set of vertex attributes required by this material.
     *
     * Use this to determine which attributes your vertex buffers must provide. If a required
     * attribute is missing, rendering will fail or produce incorrect results.
     *
     * @return Set of required VertexAttribute values (e.g., POSITION, TANGENTS, UV0, COLOR, etc.).
     */
    val requiredAttributes: Set<VertexBuffer.VertexAttribute> get() {
        val bitset = FilaMaterial_getRequiredAttributes(nativeHandle)
        val result = mutableSetOf<VertexBuffer.VertexAttribute>()
        VertexBuffer.VertexAttribute.entries.forEach { attr ->
            if ((bitset and (1 shl attr.ordinal)) != 0) {
                result.add(attr)
            }
        }
        return result
    }

    /**
     * Check whether a parameter with the given name exists.
     *
     * @param name Parameter name.
     * @return true if the parameter exists, false otherwise.
     */
    fun hasParameter(name: String): Boolean = name.useCString { FilaMaterial_hasParameter(nativeHandle, it) }
    /**
     * Get the transform parameter name associated with a sampler.
     *
     * Some samplers can have associated texture coordinate transforms (scale, rotation, etc).
     *
     * @param samplerName Name of a sampler parameter.
     * @return Transform parameter name if it exists, or null if not.
     */
    fun getParameterTransformName(samplerName: String): String? = samplerName.useCString { stringFromInterop(FilaMaterial_getParameterTransformName(nativeHandle, it)) }
    /**
     * Set a boolean parameter on this material's default instance.
     *
     * The parameter must exist and be of boolean type.
     *
     * @param name Parameter name.
     * @param value Boolean value.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Boolean) = name.useCString { FilaMaterial_setDefaultParameter_bool(nativeHandle, it, value) }
    /**
     * Set a float parameter on this material's default instance.
     *
     * @param name Parameter name.
     * @param value Float value.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Float) = name.useCString { FilaMaterial_setDefaultParameter_float(nativeHandle, it, value) }
    /**
     * Set an integer parameter on this material's default instance.
     *
     * @param name Parameter name.
     * @param value Integer value.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, value: Int) = name.useCString { FilaMaterial_setDefaultParameter_int(nativeHandle, it, value) }
    /**
     * Set a 2D vector parameter on this material's default instance.
     *
     * @param name Parameter name.
     * @param x X component.
     * @param y Y component.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float) = name.useCString { FilaMaterial_setDefaultParameter_float2(nativeHandle, it, x, y) }
    /**
     * Set a 3D vector parameter on this material's default instance.
     *
     * @param name Parameter name.
     * @param x X component.
     * @param y Y component.
     * @param z Z component.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float, z: Float) = name.useCString { FilaMaterial_setDefaultParameter_float3(nativeHandle, it, x, y, z) }
    /**
     * Set a 4D vector parameter on this material's default instance.
     *
     * @param name Parameter name.
     * @param x X component.
     * @param y Y component.
     * @param z Z component.
     * @param w W component.
     *
     * @see getDefaultInstance
     */
    fun setDefaultParameter(name: String, x: Float, y: Float, z: Float, w: Float) = name.useCString { FilaMaterial_setDefaultParameter_float4(nativeHandle, it, x, y, z, w) }
}

// Every compiled .filamat begins with the MaterialVersion chunk, whose 8-byte type token is
// "MAT_VERSION" stored little-endian — i.e. the bytes "SREV_TAM" on disk. Builder.build() checks
// this before handing the payload to Filament's parser, which panics on a non-.filamat blob; that
// panic unwinds across the prebuilt's -fno-exceptions frames and terminates the process. Bailing
// here turns the common bad-asset case (a PNG, a truncated download) into an IllegalArgumentException.
private val FILAMAT_MAGIC = "SREV_TAM".encodeToByteArray()

/** True if [data] starts with the compiled-`.filamat` magic. Cheap structural sniff, not a full parse. */
internal fun isValidFilamatPayload(data: ByteArray): Boolean =
    data.size >= FILAMAT_MAGIC.size && FILAMAT_MAGIC.indices.all { data[it] == FILAMAT_MAGIC[it] }

// ParameterInfo packs a union: `type` holds a UniformType, a SamplerType or a SubpassType,
// selected by isSampler/isSubpass. Parameter.Type flattens the three enums in that order, so
// the sampler range is just an offset. The coerces drop UniformType.STRUCT and
// SamplerType.SAMPLER_CUBEMAP_ARRAY, which Parameter.Type does not model.
internal fun materialParameterType(raw: Int, isSampler: Boolean, isSubpass: Boolean): Material.Parameter.Type {
    val entries = Material.Parameter.Type.entries
    val first = Material.Parameter.Type.SAMPLER_2D.ordinal
    val last = Material.Parameter.Type.SAMPLER_3D.ordinal
    return when {
        isSubpass -> Material.Parameter.Type.SUBPASS_INPUT
        isSampler -> entries[(first + raw).coerceIn(first, last)]
        else -> entries[raw.coerceIn(0, Material.Parameter.Type.MAT4.ordinal)]
    }
}

@ExternalSymbolName("FilaMaterial_Builder_build")
private external fun FilaMaterial_Builder_build(builder: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_Builder_create")
private external fun FilaMaterial_Builder_create(): NativePointer

@ExternalSymbolName("FilaMaterial_Builder_destroy")
private external fun FilaMaterial_Builder_destroy(builder: NativePointer)

@ExternalSymbolName("FilaMaterial_Builder_package")
private external fun FilaMaterial_Builder_package(builder: NativePointer, payload: NativePointer, size: Int)

@ExternalSymbolName("FilaMaterial_Builder_shadowSamplingQuality")
private external fun FilaMaterial_Builder_shadowSamplingQuality(builder: NativePointer, quality: Int)

@ExternalSymbolName("FilaMaterial_Builder_sphericalHarmonicsBandCount")
private external fun FilaMaterial_Builder_sphericalHarmonicsBandCount(builder: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_Builder_uboBatching")
private external fun FilaMaterial_Builder_uboBatching(builder: NativePointer, mode: Int)

@ExternalSymbolName("FilaMaterial_compile")
private external fun FilaMaterial_compile(material: NativePointer, priority: Int, variants: Int, handler: NativePointer, callback: NativePointer, userData: NativePointer)

@ExternalSymbolName("FilaMaterial_createInstance")
private external fun FilaMaterial_createInstance(material: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_createInstanceWithName")
private external fun FilaMaterial_createInstanceWithName(material: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getBlendingMode")
private external fun FilaMaterial_getBlendingMode(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getCullingMode")
private external fun FilaMaterial_getCullingMode(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getDefaultInstance")
private external fun FilaMaterial_getDefaultInstance(material: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getFeatureLevel")
private external fun FilaMaterial_getFeatureLevel(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getInterpolation")
private external fun FilaMaterial_getInterpolation(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getMaskThreshold")
private external fun FilaMaterial_getMaskThreshold(material: NativePointer): Float

@ExternalSymbolName("FilaMaterial_getName")
private external fun FilaMaterial_getName(material: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getParameterCount")
private external fun FilaMaterial_getParameterCount(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getParameterName")
private external fun FilaMaterial_getParameterName(material: NativePointer, index: Int): NativePointer

@ExternalSymbolName("FilaMaterial_getParameterTransformName")
private external fun FilaMaterial_getParameterTransformName(material: NativePointer, samplerName: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getParameters")
private external fun FilaMaterial_getParameters(material: NativePointer, info: NativePointer, count: Int): Int

@ExternalSymbolName("FilaMaterial_getReflectionMode")
private external fun FilaMaterial_getReflectionMode(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getRefractionMode")
private external fun FilaMaterial_getRefractionMode(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getRefractionType")
private external fun FilaMaterial_getRefractionType(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getRequiredAttributes")
private external fun FilaMaterial_getRequiredAttributes(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getShading")
private external fun FilaMaterial_getShading(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getSpecularAntiAliasingThreshold")
private external fun FilaMaterial_getSpecularAntiAliasingThreshold(material: NativePointer): Float

@ExternalSymbolName("FilaMaterial_getSpecularAntiAliasingVariance")
private external fun FilaMaterial_getSpecularAntiAliasingVariance(material: NativePointer): Float

@ExternalSymbolName("FilaMaterial_getTransparencyMode")
private external fun FilaMaterial_getTransparencyMode(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getVertexDomain")
private external fun FilaMaterial_getVertexDomain(material: NativePointer): Int

@ExternalSymbolName("FilaMaterial_hasParameter")
private external fun FilaMaterial_hasParameter(material: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isAlphaToCoverageEnabled")
private external fun FilaMaterial_isAlphaToCoverageEnabled(material: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isColorWriteEnabled")
private external fun FilaMaterial_isColorWriteEnabled(material: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDepthCullingEnabled")
private external fun FilaMaterial_isDepthCullingEnabled(material: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDepthWriteEnabled")
private external fun FilaMaterial_isDepthWriteEnabled(material: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDoubleSided")
private external fun FilaMaterial_isDoubleSided(material: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool")
private external fun FilaMaterial_setDefaultParameter_bool(material: NativePointer, name: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float")
private external fun FilaMaterial_setDefaultParameter_float(material: NativePointer, name: NativePointer, value: Float)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float2")
private external fun FilaMaterial_setDefaultParameter_float2(material: NativePointer, name: NativePointer, x: Float, y: Float)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float3")
private external fun FilaMaterial_setDefaultParameter_float3(material: NativePointer, name: NativePointer, x: Float, y: Float, z: Float)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float4")
private external fun FilaMaterial_setDefaultParameter_float4(material: NativePointer, name: NativePointer, x: Float, y: Float, z: Float, w: Float)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int")
private external fun FilaMaterial_setDefaultParameter_int(material: NativePointer, name: NativePointer, value: Int)
