package buildlogic.apigen.kotlin

/**
 * Writes the common `@ExternalSymbolName external fun` of every Fila* function a C header declares, named like the
 * C symbol (web binds by global name). C types map to the types externals take (docs/internals/bindings.md): any pointer is a
 * `NativePointer`, 32-bit integers and enums an `Int`, 64-bit ones a `Long`.
 */
internal class KotlinExternalsWriter(typeHeaders: Collection<String>) {
    /** Kotlin type of each non-struct typedef the headers declare: enums, wide enums, function pointers, FilaEntity. */
    private val typedefs = typeHeaders.flatMap { text ->
        ENUM.findAll(text).map { it.groupValues[1] to "Int" } +
            SCALAR.findAll(text).map { it.groupValues[2] to BUILTINS.getValue(it.groupValues[1]) } +
            FUNCTION_POINTER.findAll(text).map { it.groupValues[1] to "NativePointer" }
    }.toMap()

    /** The Kotlin file binding [header] (its text, from `c/[source]`) in [pkg], or null when it declares no functions. */
    fun write(source: String, header: String, pkg: String): String? {
        val functions = PROTOTYPE.findAll(header.lineSequence().filterNot { it.startsWith("//") }.joinToString("\n"))
            .map { external(it.groupValues[1], it.groupValues[2], it.groupValues[3], source) }.toList()
        if (functions.isEmpty()) return null
        return "// Generated by generateKotlinExternals from c/$source; do not edit.\n" +
            "package $pkg\n\nimport io.github.erkko68.filament.interop.ExternalSymbolName\n" +
            (if (functions.any { "NativePointer" in it }) "import io.github.erkko68.filament.interop.NativePointer\n" else "") +
            functions.joinToString("") { "\n$it" }
    }

    private fun external(returns: String, name: String, params: String, where: String): String {
        val kotlinParams = params.split(", ").filter { it.isNotEmpty() && it != "void" }.joinToString { param ->
            val (type, paramName) = PARAM.matchEntire(param.trim())?.destructured ?: error("Can't parse parameter '$param' of $name in $where")
            "${if (paramName in KEYWORDS) "`$paramName`" else paramName}: ${kotlin(type, "$name in $where")}"
        }
        val result = kotlin(returns, "$name in $where").takeIf { it != "Unit" }?.let { ": $it" } ?: ""
        return "@ExternalSymbolName(\"$name\")\ninternal external fun $name($kotlinParams)$result\n"
    }

    private fun kotlin(c: String, where: String): String {
        if ('*' in c) return "NativePointer"
        val base = c.removePrefix("const ").trim()
        return BUILTINS[base] ?: typedefs[base] ?: error("No Kotlin type for C type '$c' ($where)")
    }

    private companion object {
        val PROTOTYPE = Regex("""^(\S[^(\n]*?)\s*\b(Fila\w+)\(([^)\n]*)\);$""", RegexOption.MULTILINE)
        val PARAM = Regex("""(.*?[\s*])(\w+)""")
        val ENUM = Regex("""^typedef enum \w+ \{[^}]*} (\w+);""", RegexOption.MULTILINE)
        val SCALAR = Regex("""^typedef (u?int(?:32|64)_t) (\w+);""", RegexOption.MULTILINE)
        val FUNCTION_POINTER = Regex("""^typedef [^(]*\(\*(\w+)\)""", RegexOption.MULTILINE)
        val BUILTINS = mapOf(
            "void" to "Unit", "bool" to "Boolean", "float" to "Float", "double" to "Double",
            "int32_t" to "Int", "uint32_t" to "Int", "int64_t" to "Long", "uint64_t" to "Long",
        )
        val KEYWORDS = setOf(
            "as", "break", "class", "continue", "do", "else", "false", "for", "fun", "if", "in", "interface", "is", "null",
            "object", "package", "return", "super", "this", "throw", "true", "try", "typealias", "typeof", "val", "var",
            "when", "while",
        )
    }
}
