// Generated by generateKotlinExternals from c/filamat/generated/FilaFilamatPackage.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilamatPackage_create")
internal external fun FilaFilamatPackage_create(): NativePointer

@ExternalSymbolName("FilaFilamatPackage_create_size_t")
internal external fun FilaFilamatPackage_create_size_t(size: Int): NativePointer

@ExternalSymbolName("FilaFilamatPackage_create_void_size_t")
internal external fun FilaFilamatPackage_create_void_size_t(src: NativePointer, size: Int): NativePointer

@ExternalSymbolName("FilaFilamatPackage_destroy")
internal external fun FilaFilamatPackage_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilamatPackage_getData")
internal external fun FilaFilamatPackage_getData(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatPackage_getSize")
internal external fun FilaFilamatPackage_getSize(self: NativePointer): Int

@ExternalSymbolName("FilaFilamatPackage_getEnd")
internal external fun FilaFilamatPackage_getEnd(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatPackage_setValid")
internal external fun FilaFilamatPackage_setValid(self: NativePointer, valid: Boolean)

@ExternalSymbolName("FilaFilamatPackage_isValid")
internal external fun FilaFilamatPackage_isValid(self: NativePointer): Boolean
