// Generated by generateKotlinExternals from c/filamat/generated/FilaFilamat.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilamat_targetApiFromBackend")
internal external fun FilaFilamat_targetApiFromBackend(backend: Int): Int

@ExternalSymbolName("FilaFilamat_charTo64bitNum")
internal external fun FilaFilamat_charTo64bitNum(str: NativePointer, out: NativePointer)
