// Generated by generateKotlinExternals from c/filamat/manual/FilaFilamatMaterialBuilderManual.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_build")
internal external fun FilaFilamatMaterialBuilder_build(self: NativePointer): NativePointer
