// Generated by generateKotlinExternals from c/filamat/generated/FilaFilamatMaterialBuilderBase.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName

@ExternalSymbolName("FilaFilamatMaterialBuilderBase_init")
internal external fun FilaFilamatMaterialBuilderBase_init()

@ExternalSymbolName("FilaFilamatMaterialBuilderBase_shutdown")
internal external fun FilaFilamatMaterialBuilderBase_shutdown()
