// Generated by generateKotlinExternals from c/filamat/generated/FilaFilamatMaterialBuilder.h; do not edit.
package io.github.erkko68.filament.filamat.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_create")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_create(name: NativePointer, value: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_destroy")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_getName")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_setName")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_setName(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_getValue")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_getValue(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderPreprocessorDefine_setValue")
internal external fun FilaFilamatMaterialBuilderPreprocessorDefine_setValue(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_create")
internal external fun FilaFilamatMaterialBuilderAttribute_create(): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_destroy")
internal external fun FilaFilamatMaterialBuilderAttribute_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_getAttributeName")
internal external fun FilaFilamatMaterialBuilderAttribute_getAttributeName(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_getDefineName")
internal external fun FilaFilamatMaterialBuilderAttribute_getDefineName(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_getName")
internal external fun FilaFilamatMaterialBuilderAttribute_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_getType")
internal external fun FilaFilamatMaterialBuilderAttribute_getType(self: NativePointer): Int

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_setType")
internal external fun FilaFilamatMaterialBuilderAttribute_setType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_getLocation")
internal external fun FilaFilamatMaterialBuilderAttribute_getLocation(self: NativePointer): Int

@ExternalSymbolName("FilaFilamatMaterialBuilderAttribute_setLocation")
internal external fun FilaFilamatMaterialBuilderAttribute_setLocation(self: NativePointer, value: Int)

@ExternalSymbolName("FilaFilamatMaterialBuilder_create")
internal external fun FilaFilamatMaterialBuilder_create(): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_destroy")
internal external fun FilaFilamatMaterialBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilamatMaterialBuilder_asFilamatMaterialBuilderBase")
internal external fun FilaFilamatMaterialBuilder_asFilamatMaterialBuilderBase(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_noSamplerValidation")
internal external fun FilaFilamatMaterialBuilder_noSamplerValidation(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_includeEssl1")
internal external fun FilaFilamatMaterialBuilder_includeEssl1(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_name")
internal external fun FilaFilamatMaterialBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_compilationParameters")
internal external fun FilaFilamatMaterialBuilder_compilationParameters(self: NativePointer, params: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_shading")
internal external fun FilaFilamatMaterialBuilder_shading(self: NativePointer, shading: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_interpolation")
internal external fun FilaFilamatMaterialBuilder_interpolation(self: NativePointer, interpolation: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_parameter_UniformType_ParameterPrecision")
internal external fun FilaFilamatMaterialBuilder_parameter_UniformType_ParameterPrecision(self: NativePointer, name: NativePointer, type: Int, precision: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_parameter_size_t_UniformType_ParameterPrecision")
internal external fun FilaFilamatMaterialBuilder_parameter_size_t_UniformType_ParameterPrecision(self: NativePointer, name: NativePointer, size: Int, type: Int, precision: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_parameter_SamplerType_SamplerFormat_ParameterPrecision_bool_bool_char_optional")
internal external fun FilaFilamatMaterialBuilder_parameter_SamplerType_SamplerFormat_ParameterPrecision_bool_bool_char_optional(self: NativePointer, name: NativePointer, samplerType: Int, format: Int, precision: Int, filterable: Boolean, multisample: Boolean, transformName: NativePointer, stages: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_int32_t")
internal external fun FilaFilamatMaterialBuilder_constant_int32_t(self: NativePointer, name: NativePointer, type: Int, defaultValue: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_float")
internal external fun FilaFilamatMaterialBuilder_constant_float(self: NativePointer, name: NativePointer, type: Int, defaultValue: Float): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_constant_bool")
internal external fun FilaFilamatMaterialBuilder_constant_bool(self: NativePointer, name: NativePointer, type: Int, defaultValue: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_variable")
internal external fun FilaFilamatMaterialBuilder_variable(self: NativePointer, v: Int, name: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_variable_ParameterPrecision")
internal external fun FilaFilamatMaterialBuilder_variable_ParameterPrecision(self: NativePointer, v: Int, name: NativePointer, precision: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_require")
internal external fun FilaFilamatMaterialBuilder_require(self: NativePointer, attribute: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_materialDomain")
internal external fun FilaFilamatMaterialBuilder_materialDomain(self: NativePointer, materialDomain: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_material")
internal external fun FilaFilamatMaterialBuilder_material(self: NativePointer, code: NativePointer, line: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_materialVertex")
internal external fun FilaFilamatMaterialBuilder_materialVertex(self: NativePointer, code: NativePointer, line: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_quality")
internal external fun FilaFilamatMaterialBuilder_quality(self: NativePointer, quality: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_featureLevel")
internal external fun FilaFilamatMaterialBuilder_featureLevel(self: NativePointer, featureLevel: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_blending")
internal external fun FilaFilamatMaterialBuilder_blending(self: NativePointer, blending: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_customBlendFunctions")
internal external fun FilaFilamatMaterialBuilder_customBlendFunctions(self: NativePointer, srcRGB: Int, srcA: Int, dstRGB: Int, dstA: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_postLightingBlending")
internal external fun FilaFilamatMaterialBuilder_postLightingBlending(self: NativePointer, blending: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_vertexDomain")
internal external fun FilaFilamatMaterialBuilder_vertexDomain(self: NativePointer, domain: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_culling")
internal external fun FilaFilamatMaterialBuilder_culling(self: NativePointer, culling: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_colorWrite")
internal external fun FilaFilamatMaterialBuilder_colorWrite(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_depthWrite")
internal external fun FilaFilamatMaterialBuilder_depthWrite(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_depthCulling")
internal external fun FilaFilamatMaterialBuilder_depthCulling(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_instanced")
internal external fun FilaFilamatMaterialBuilder_instanced(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_doubleSided")
internal external fun FilaFilamatMaterialBuilder_doubleSided(self: NativePointer, doubleSided: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_maskThreshold")
internal external fun FilaFilamatMaterialBuilder_maskThreshold(self: NativePointer, threshold: Float): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_alphaToCoverage")
internal external fun FilaFilamatMaterialBuilder_alphaToCoverage(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_shadowMultiplier")
internal external fun FilaFilamatMaterialBuilder_shadowMultiplier(self: NativePointer, shadowMultiplier: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_transparentShadow")
internal external fun FilaFilamatMaterialBuilder_transparentShadow(self: NativePointer, transparentShadow: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_coloredPenumbra")
internal external fun FilaFilamatMaterialBuilder_coloredPenumbra(self: NativePointer, coloredPenumbra: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_specularAntiAliasing")
internal external fun FilaFilamatMaterialBuilder_specularAntiAliasing(self: NativePointer, specularAntiAliasing: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_specularAntiAliasingVariance")
internal external fun FilaFilamatMaterialBuilder_specularAntiAliasingVariance(self: NativePointer, screenSpaceVariance: Float): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_specularAntiAliasingThreshold")
internal external fun FilaFilamatMaterialBuilder_specularAntiAliasingThreshold(self: NativePointer, threshold: Float): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_clearCoatIorChange")
internal external fun FilaFilamatMaterialBuilder_clearCoatIorChange(self: NativePointer, clearCoatIorChange: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_flipUV")
internal external fun FilaFilamatMaterialBuilder_flipUV(self: NativePointer, flipUV: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_linearFog")
internal external fun FilaFilamatMaterialBuilder_linearFog(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_shadowFarAttenuation")
internal external fun FilaFilamatMaterialBuilder_shadowFarAttenuation(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_multiBounceAmbientOcclusion")
internal external fun FilaFilamatMaterialBuilder_multiBounceAmbientOcclusion(self: NativePointer, multiBounceAO: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_specularAmbientOcclusion")
internal external fun FilaFilamatMaterialBuilder_specularAmbientOcclusion(self: NativePointer, specularAO: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_refractionMode")
internal external fun FilaFilamatMaterialBuilder_refractionMode(self: NativePointer, refraction: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_refractionType")
internal external fun FilaFilamatMaterialBuilder_refractionType(self: NativePointer, refractionType: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_reflectionMode")
internal external fun FilaFilamatMaterialBuilder_reflectionMode(self: NativePointer, mode: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_transparencyMode")
internal external fun FilaFilamatMaterialBuilder_transparencyMode(self: NativePointer, mode: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_stereoscopicType")
internal external fun FilaFilamatMaterialBuilder_stereoscopicType(self: NativePointer, stereoscopicType: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_stereoscopicEyeCount")
internal external fun FilaFilamatMaterialBuilder_stereoscopicEyeCount(self: NativePointer, eyeCount: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_customSurfaceShading")
internal external fun FilaFilamatMaterialBuilder_customSurfaceShading(self: NativePointer, customSurfaceShading: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_platform")
internal external fun FilaFilamatMaterialBuilder_platform(self: NativePointer, platform: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_targetApi")
internal external fun FilaFilamatMaterialBuilder_targetApi(self: NativePointer, targetApi: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_optimization")
internal external fun FilaFilamatMaterialBuilder_optimization(self: NativePointer, optimization: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_workarounds")
internal external fun FilaFilamatMaterialBuilder_workarounds(self: NativePointer, workarounds: Long): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_printShaders")
internal external fun FilaFilamatMaterialBuilder_printShaders(self: NativePointer, printShaders: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_saveRawVariants")
internal external fun FilaFilamatMaterialBuilder_saveRawVariants(self: NativePointer, saveRawVariants: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_generateDebugInfo")
internal external fun FilaFilamatMaterialBuilder_generateDebugInfo(self: NativePointer, generateDebugInfo: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_variantFilter")
internal external fun FilaFilamatMaterialBuilder_variantFilter(self: NativePointer, variantFilter: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_shaderDefine")
internal external fun FilaFilamatMaterialBuilder_shaderDefine(self: NativePointer, name: NativePointer, value: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_output")
internal external fun FilaFilamatMaterialBuilder_output(self: NativePointer, qualifier: Int, target: Int, precision: Int, type: Int, name: NativePointer, location: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_enableFramebufferFetch")
internal external fun FilaFilamatMaterialBuilder_enableFramebufferFetch(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_vertexDomainDeviceJittered")
internal external fun FilaFilamatMaterialBuilder_vertexDomainDeviceJittered(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_useLegacyMorphing")
internal external fun FilaFilamatMaterialBuilder_useLegacyMorphing(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_groupSize")
internal external fun FilaFilamatMaterialBuilder_groupSize(self: NativePointer, groupSize: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_useDefaultDepthVariant")
internal external fun FilaFilamatMaterialBuilder_useDefaultDepthVariant(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_materialSource")
internal external fun FilaFilamatMaterialBuilder_materialSource(self: NativePointer, source: NativePointer): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_setApiLevel")
internal external fun FilaFilamatMaterialBuilder_setApiLevel(self: NativePointer, apiLevel: Int): NativePointer

@ExternalSymbolName("FilaFilamatMaterialBuilder_getAttributeDatabase")
internal external fun FilaFilamatMaterialBuilder_getAttributeDatabase(out: NativePointer, outCapacity: Int): Int
