// Generated by generateKotlinExternals from c/filament/generated/FilaColorGrading.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_create")
internal external fun FilaColorGradingBuilder_create(): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_destroy")
internal external fun FilaColorGradingBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaColorGradingBuilder_quality")
internal external fun FilaColorGradingBuilder_quality(self: NativePointer, qualityLevel: Int): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_format")
internal external fun FilaColorGradingBuilder_format(self: NativePointer, format: Int): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_dimensions")
internal external fun FilaColorGradingBuilder_dimensions(self: NativePointer, dim: Int): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_toneMapper")
internal external fun FilaColorGradingBuilder_toneMapper(self: NativePointer, toneMapper: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_luminanceScaling")
internal external fun FilaColorGradingBuilder_luminanceScaling(self: NativePointer, luminanceScaling: Boolean): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_gamutMapping")
internal external fun FilaColorGradingBuilder_gamutMapping(self: NativePointer, gamutMapping: Boolean): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_exposure")
internal external fun FilaColorGradingBuilder_exposure(self: NativePointer, exposure: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_nightAdaptation")
internal external fun FilaColorGradingBuilder_nightAdaptation(self: NativePointer, adaptation: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_whiteBalance")
internal external fun FilaColorGradingBuilder_whiteBalance(self: NativePointer, temperature: Float, tint: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_channelMixer")
internal external fun FilaColorGradingBuilder_channelMixer(self: NativePointer, outRed: NativePointer, outGreen: NativePointer, outBlue: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_shadowsMidtonesHighlights")
internal external fun FilaColorGradingBuilder_shadowsMidtonesHighlights(self: NativePointer, shadows: NativePointer, midtones: NativePointer, highlights: NativePointer, ranges: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_slopeOffsetPower")
internal external fun FilaColorGradingBuilder_slopeOffsetPower(self: NativePointer, slope: NativePointer, offset: NativePointer, power: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_contrast")
internal external fun FilaColorGradingBuilder_contrast(self: NativePointer, contrast: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_vibrance")
internal external fun FilaColorGradingBuilder_vibrance(self: NativePointer, vibrance: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_saturation")
internal external fun FilaColorGradingBuilder_saturation(self: NativePointer, saturation: Float): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_curves")
internal external fun FilaColorGradingBuilder_curves(self: NativePointer, shadowGamma: NativePointer, midPoint: NativePointer, highlightScale: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_customLut")
internal external fun FilaColorGradingBuilder_customLut(self: NativePointer, data: NativePointer, dataCount: Int, dimension: Int): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_outputColorSpace")
internal external fun FilaColorGradingBuilder_outputColorSpace(self: NativePointer, colorSpace: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_fastMath")
internal external fun FilaColorGradingBuilder_fastMath(self: NativePointer, fastMath: Boolean): NativePointer

@ExternalSymbolName("FilaColorGradingBuilder_build")
internal external fun FilaColorGradingBuilder_build(self: NativePointer, engine: NativePointer): NativePointer
