// Generated by generateKotlinExternals from c/filament/generated/FilaRenderTarget.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_create")
internal external fun FilaRenderTargetBuilder_create(): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_destroy")
internal external fun FilaRenderTargetBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaRenderTargetBuilder_texture")
internal external fun FilaRenderTargetBuilder_texture(self: NativePointer, attachment: Int, texture: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_mipLevel")
internal external fun FilaRenderTargetBuilder_mipLevel(self: NativePointer, attachment: Int, level: Int): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_face")
internal external fun FilaRenderTargetBuilder_face(self: NativePointer, attachment: Int, face: Int): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_layer")
internal external fun FilaRenderTargetBuilder_layer(self: NativePointer, attachment: Int, layer: Int): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_multiview")
internal external fun FilaRenderTargetBuilder_multiview(self: NativePointer, attachment: Int, layerCount: Int, baseLayer: Int): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_samples")
internal external fun FilaRenderTargetBuilder_samples(self: NativePointer, samples: Int): NativePointer

@ExternalSymbolName("FilaRenderTargetBuilder_build")
internal external fun FilaRenderTargetBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderTarget_getTexture")
internal external fun FilaRenderTarget_getTexture(self: NativePointer, attachment: Int): NativePointer

@ExternalSymbolName("FilaRenderTarget_getMipLevel")
internal external fun FilaRenderTarget_getMipLevel(self: NativePointer, attachment: Int): Int

@ExternalSymbolName("FilaRenderTarget_getFace")
internal external fun FilaRenderTarget_getFace(self: NativePointer, attachment: Int): Int

@ExternalSymbolName("FilaRenderTarget_getLayer")
internal external fun FilaRenderTarget_getLayer(self: NativePointer, attachment: Int): Int

@ExternalSymbolName("FilaRenderTarget_getSupportedColorAttachmentsCount")
internal external fun FilaRenderTarget_getSupportedColorAttachmentsCount(self: NativePointer): Int
