// Generated by generateKotlinExternals from c/filament/generated/FilaMorphTargetBuffer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_create")
internal external fun FilaMorphTargetBufferBuilder_create(): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_destroy")
internal external fun FilaMorphTargetBufferBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaMorphTargetBufferBuilder_vertexCount")
internal external fun FilaMorphTargetBufferBuilder_vertexCount(self: NativePointer, vertexCount: Int): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_count")
internal external fun FilaMorphTargetBufferBuilder_count(self: NativePointer, count: Int): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_name")
internal external fun FilaMorphTargetBufferBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_withPositions")
internal external fun FilaMorphTargetBufferBuilder_withPositions(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_withTangents")
internal external fun FilaMorphTargetBufferBuilder_withTangents(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_enableCustomMorphing")
internal external fun FilaMorphTargetBufferBuilder_enableCustomMorphing(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaMorphTargetBufferBuilder_build")
internal external fun FilaMorphTargetBufferBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaMorphTargetBuffer_setPositionsAt_float3_size_t_size_t")
internal external fun FilaMorphTargetBuffer_setPositionsAt_float3_size_t_size_t(self: NativePointer, engine: NativePointer, targetIndex: Int, positions: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaMorphTargetBuffer_setPositionsAt_float4_size_t_size_t")
internal external fun FilaMorphTargetBuffer_setPositionsAt_float4_size_t_size_t(self: NativePointer, engine: NativePointer, targetIndex: Int, positions: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaMorphTargetBuffer_setTangentsAt")
internal external fun FilaMorphTargetBuffer_setTangentsAt(self: NativePointer, engine: NativePointer, targetIndex: Int, tangents: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaMorphTargetBuffer_getVertexCount")
internal external fun FilaMorphTargetBuffer_getVertexCount(self: NativePointer): Int

@ExternalSymbolName("FilaMorphTargetBuffer_getCount")
internal external fun FilaMorphTargetBuffer_getCount(self: NativePointer): Int

@ExternalSymbolName("FilaMorphTargetBuffer_hasPositions")
internal external fun FilaMorphTargetBuffer_hasPositions(self: NativePointer): Boolean

@ExternalSymbolName("FilaMorphTargetBuffer_hasTangents")
internal external fun FilaMorphTargetBuffer_hasTangents(self: NativePointer): Boolean

@ExternalSymbolName("FilaMorphTargetBuffer_isCustomMorphingEnabled")
internal external fun FilaMorphTargetBuffer_isCustomMorphingEnabled(self: NativePointer): Boolean
