// Generated by generateKotlinExternals from c/filament/generated/FilaVignetteOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaVignetteOptions_create")
internal external fun FilaVignetteOptions_create(): NativePointer

@ExternalSymbolName("FilaVignetteOptions_destroy")
internal external fun FilaVignetteOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaVignetteOptions_getMidPoint")
internal external fun FilaVignetteOptions_getMidPoint(self: NativePointer): Float

@ExternalSymbolName("FilaVignetteOptions_setMidPoint")
internal external fun FilaVignetteOptions_setMidPoint(self: NativePointer, value: Float)

@ExternalSymbolName("FilaVignetteOptions_getRoundness")
internal external fun FilaVignetteOptions_getRoundness(self: NativePointer): Float

@ExternalSymbolName("FilaVignetteOptions_setRoundness")
internal external fun FilaVignetteOptions_setRoundness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaVignetteOptions_getFeather")
internal external fun FilaVignetteOptions_getFeather(self: NativePointer): Float

@ExternalSymbolName("FilaVignetteOptions_setFeather")
internal external fun FilaVignetteOptions_setFeather(self: NativePointer, value: Float)

@ExternalSymbolName("FilaVignetteOptions_getColor")
internal external fun FilaVignetteOptions_getColor(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaVignetteOptions_setColor")
internal external fun FilaVignetteOptions_setColor(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaVignetteOptions_getEnabled")
internal external fun FilaVignetteOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaVignetteOptions_setEnabled")
internal external fun FilaVignetteOptions_setEnabled(self: NativePointer, value: Boolean)
