// Generated by generateKotlinExternals from c/filament/manual/FilaViewManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaView_pick")
internal external fun FilaView_pick(self: NativePointer, x: Int, y: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)
