// Generated by generateKotlinExternals from c/filament/generated/FilaTexture.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaTextureBuilder_create")
internal external fun FilaTextureBuilder_create(): NativePointer

@ExternalSymbolName("FilaTextureBuilder_destroy")
internal external fun FilaTextureBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaTextureBuilder_width")
internal external fun FilaTextureBuilder_width(self: NativePointer, width: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_height")
internal external fun FilaTextureBuilder_height(self: NativePointer, height: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_depth")
internal external fun FilaTextureBuilder_depth(self: NativePointer, depth: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_levels")
internal external fun FilaTextureBuilder_levels(self: NativePointer, levels: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_samples")
internal external fun FilaTextureBuilder_samples(self: NativePointer, samples: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_sampler")
internal external fun FilaTextureBuilder_sampler(self: NativePointer, target: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_format")
internal external fun FilaTextureBuilder_format(self: NativePointer, format: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_usage")
internal external fun FilaTextureBuilder_usage(self: NativePointer, usage: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_swizzle")
internal external fun FilaTextureBuilder_swizzle(self: NativePointer, r: Int, g: Int, b: Int, a: Int): NativePointer

@ExternalSymbolName("FilaTextureBuilder_name")
internal external fun FilaTextureBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaTextureBuilder_external")
internal external fun FilaTextureBuilder_external(self: NativePointer): NativePointer

@ExternalSymbolName("FilaTextureBuilder_async")
internal external fun FilaTextureBuilder_async(self: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): NativePointer

@ExternalSymbolName("FilaTextureBuilder_build")
internal external fun FilaTextureBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaTextureBuilder_import")
internal external fun FilaTextureBuilder_import(self: NativePointer, id: Long): NativePointer

@ExternalSymbolName("FilaTexture_isTextureFormatSupported")
internal external fun FilaTexture_isTextureFormatSupported(engine: NativePointer, format: Int): Boolean

@ExternalSymbolName("FilaTexture_isTextureFormatMipmappable")
internal external fun FilaTexture_isTextureFormatMipmappable(engine: NativePointer, format: Int): Boolean

@ExternalSymbolName("FilaTexture_isTextureFormatCompressed")
internal external fun FilaTexture_isTextureFormatCompressed(format: Int): Boolean

@ExternalSymbolName("FilaTexture_isProtectedTexturesSupported")
internal external fun FilaTexture_isProtectedTexturesSupported(engine: NativePointer): Boolean

@ExternalSymbolName("FilaTexture_isTextureSwizzleSupported")
internal external fun FilaTexture_isTextureSwizzleSupported(engine: NativePointer): Boolean

@ExternalSymbolName("FilaTexture_computeTextureDataSize")
internal external fun FilaTexture_computeTextureDataSize(format: Int, type: Int, stride: Int, height: Int, alignment: Int): Int

@ExternalSymbolName("FilaTexture_validatePixelFormatAndType")
internal external fun FilaTexture_validatePixelFormatAndType(internalFormat: Int, format: Int, type: Int): Boolean

@ExternalSymbolName("FilaTexture_getMaxTextureSize")
internal external fun FilaTexture_getMaxTextureSize(engine: NativePointer, type: Int): Int

@ExternalSymbolName("FilaTexture_getMaxArrayTextureLayers")
internal external fun FilaTexture_getMaxArrayTextureLayers(engine: NativePointer): Int

@ExternalSymbolName("FilaTexture_getWidth")
internal external fun FilaTexture_getWidth(self: NativePointer, level: Int): Int

@ExternalSymbolName("FilaTexture_getHeight")
internal external fun FilaTexture_getHeight(self: NativePointer, level: Int): Int

@ExternalSymbolName("FilaTexture_getDepth")
internal external fun FilaTexture_getDepth(self: NativePointer, level: Int): Int

@ExternalSymbolName("FilaTexture_getLevels")
internal external fun FilaTexture_getLevels(self: NativePointer): Int

@ExternalSymbolName("FilaTexture_getTarget")
internal external fun FilaTexture_getTarget(self: NativePointer): Int

@ExternalSymbolName("FilaTexture_getFormat")
internal external fun FilaTexture_getFormat(self: NativePointer): Int

@ExternalSymbolName("FilaTexture_setImage_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor")
internal external fun FilaTexture_setImage_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor(self: NativePointer, engine: NativePointer, level: Int, xoffset: Int, yoffset: Int, zoffset: Int, width: Int, height: Int, depth: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaTexture_setImage_PixelBufferDescriptor")
internal external fun FilaTexture_setImage_PixelBufferDescriptor(self: NativePointer, engine: NativePointer, level: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaTexture_setImage_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor")
internal external fun FilaTexture_setImage_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor(self: NativePointer, engine: NativePointer, level: Int, xoffset: Int, yoffset: Int, width: Int, height: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaTexture_setImageAsync_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void")
internal external fun FilaTexture_setImageAsync_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void(self: NativePointer, engine: NativePointer, level: Int, xoffset: Int, yoffset: Int, zoffset: Int, width: Int, height: Int, depth: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaTexture_setImageAsync_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void")
internal external fun FilaTexture_setImageAsync_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void(self: NativePointer, engine: NativePointer, level: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaTexture_setImageAsync_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void")
internal external fun FilaTexture_setImageAsync_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor_CallbackHandler_AsyncCompletionCallback_void(self: NativePointer, engine: NativePointer, level: Int, xoffset: Int, yoffset: Int, width: Int, height: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaTexture_setExternalStream")
internal external fun FilaTexture_setExternalStream(self: NativePointer, engine: NativePointer, stream: NativePointer)

@ExternalSymbolName("FilaTexture_generateMipmaps")
internal external fun FilaTexture_generateMipmaps(self: NativePointer, engine: NativePointer)

@ExternalSymbolName("FilaTexture_isCreationComplete")
internal external fun FilaTexture_isCreationComplete(self: NativePointer): Boolean
