// Generated by generateKotlinExternals from c/filament/generated/FilaViewport.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaViewport_create")
internal external fun FilaViewport_create(): NativePointer

@ExternalSymbolName("FilaViewport_create_int32_t_int32_t_uint32_t_uint32_t")
internal external fun FilaViewport_create_int32_t_int32_t_uint32_t_uint32_t(left: Int, bottom: Int, width: Int, height: Int): NativePointer

@ExternalSymbolName("FilaViewport_destroy")
internal external fun FilaViewport_destroy(self: NativePointer)

@ExternalSymbolName("FilaViewport_empty")
internal external fun FilaViewport_empty(self: NativePointer): Boolean

@ExternalSymbolName("FilaViewport_right")
internal external fun FilaViewport_right(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_top")
internal external fun FilaViewport_top(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_getLeft")
internal external fun FilaViewport_getLeft(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_setLeft")
internal external fun FilaViewport_setLeft(self: NativePointer, value: Int)

@ExternalSymbolName("FilaViewport_getBottom")
internal external fun FilaViewport_getBottom(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_setBottom")
internal external fun FilaViewport_setBottom(self: NativePointer, value: Int)

@ExternalSymbolName("FilaViewport_getWidth")
internal external fun FilaViewport_getWidth(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_setWidth")
internal external fun FilaViewport_setWidth(self: NativePointer, value: Int)

@ExternalSymbolName("FilaViewport_getHeight")
internal external fun FilaViewport_getHeight(self: NativePointer): Int

@ExternalSymbolName("FilaViewport_setHeight")
internal external fun FilaViewport_setHeight(self: NativePointer, value: Int)
