// Generated by generateKotlinExternals from c/filament/generated/FilaDynamicResolutionOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaDynamicResolutionOptions_create")
internal external fun FilaDynamicResolutionOptions_create(): NativePointer

@ExternalSymbolName("FilaDynamicResolutionOptions_destroy")
internal external fun FilaDynamicResolutionOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaDynamicResolutionOptions_getMinScale")
internal external fun FilaDynamicResolutionOptions_getMinScale(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaDynamicResolutionOptions_setMinScale")
internal external fun FilaDynamicResolutionOptions_setMinScale(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaDynamicResolutionOptions_getMaxScale")
internal external fun FilaDynamicResolutionOptions_getMaxScale(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaDynamicResolutionOptions_setMaxScale")
internal external fun FilaDynamicResolutionOptions_setMaxScale(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaDynamicResolutionOptions_getSharpness")
internal external fun FilaDynamicResolutionOptions_getSharpness(self: NativePointer): Float

@ExternalSymbolName("FilaDynamicResolutionOptions_setSharpness")
internal external fun FilaDynamicResolutionOptions_setSharpness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaDynamicResolutionOptions_getEnabled")
internal external fun FilaDynamicResolutionOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaDynamicResolutionOptions_setEnabled")
internal external fun FilaDynamicResolutionOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaDynamicResolutionOptions_getHomogeneousScaling")
internal external fun FilaDynamicResolutionOptions_getHomogeneousScaling(self: NativePointer): Boolean

@ExternalSymbolName("FilaDynamicResolutionOptions_setHomogeneousScaling")
internal external fun FilaDynamicResolutionOptions_setHomogeneousScaling(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaDynamicResolutionOptions_getQuality")
internal external fun FilaDynamicResolutionOptions_getQuality(self: NativePointer): Int

@ExternalSymbolName("FilaDynamicResolutionOptions_setQuality")
internal external fun FilaDynamicResolutionOptions_setQuality(self: NativePointer, value: Int)
