// Generated by generateKotlinExternals from c/filament/generated/FilaGenericToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGenericToneMapper_create")
internal external fun FilaGenericToneMapper_create(contrast: Float, midGrayIn: Float, midGrayOut: Float, hdrMax: Float): NativePointer

@ExternalSymbolName("FilaGenericToneMapper_destroy")
internal external fun FilaGenericToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaGenericToneMapper_asToneMapper")
internal external fun FilaGenericToneMapper_asToneMapper(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGenericToneMapper_getContrast")
internal external fun FilaGenericToneMapper_getContrast(self: NativePointer): Float

@ExternalSymbolName("FilaGenericToneMapper_getMidGrayIn")
internal external fun FilaGenericToneMapper_getMidGrayIn(self: NativePointer): Float

@ExternalSymbolName("FilaGenericToneMapper_getMidGrayOut")
internal external fun FilaGenericToneMapper_getMidGrayOut(self: NativePointer): Float

@ExternalSymbolName("FilaGenericToneMapper_getHdrMax")
internal external fun FilaGenericToneMapper_getHdrMax(self: NativePointer): Float

@ExternalSymbolName("FilaGenericToneMapper_setContrast")
internal external fun FilaGenericToneMapper_setContrast(self: NativePointer, contrast: Float)

@ExternalSymbolName("FilaGenericToneMapper_setMidGrayIn")
internal external fun FilaGenericToneMapper_setMidGrayIn(self: NativePointer, midGrayIn: Float)

@ExternalSymbolName("FilaGenericToneMapper_setMidGrayOut")
internal external fun FilaGenericToneMapper_setMidGrayOut(self: NativePointer, midGrayOut: Float)

@ExternalSymbolName("FilaGenericToneMapper_setHdrMax")
internal external fun FilaGenericToneMapper_setHdrMax(self: NativePointer, hdrMax: Float)
