// Generated by generateKotlinExternals from c/filament/generated/FilaLightManager.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_create")
internal external fun FilaLightManagerShadowOptionsVsm_create(): NativePointer

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_destroy")
internal external fun FilaLightManagerShadowOptionsVsm_destroy(self: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_getElvsm")
internal external fun FilaLightManagerShadowOptionsVsm_getElvsm(self: NativePointer): Boolean

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_setElvsm")
internal external fun FilaLightManagerShadowOptionsVsm_setElvsm(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_getBlurWidth")
internal external fun FilaLightManagerShadowOptionsVsm_getBlurWidth(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptionsVsm_setBlurWidth")
internal external fun FilaLightManagerShadowOptionsVsm_setBlurWidth(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_create")
internal external fun FilaLightManagerShadowOptions_create(): NativePointer

@ExternalSymbolName("FilaLightManagerShadowOptions_destroy")
internal external fun FilaLightManagerShadowOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptions_getMapSize")
internal external fun FilaLightManagerShadowOptions_getMapSize(self: NativePointer): Int

@ExternalSymbolName("FilaLightManagerShadowOptions_setMapSize")
internal external fun FilaLightManagerShadowOptions_setMapSize(self: NativePointer, value: Int)

@ExternalSymbolName("FilaLightManagerShadowOptions_getShadowCascades")
internal external fun FilaLightManagerShadowOptions_getShadowCascades(self: NativePointer): Int

@ExternalSymbolName("FilaLightManagerShadowOptions_setShadowCascades")
internal external fun FilaLightManagerShadowOptions_setShadowCascades(self: NativePointer, value: Int)

@ExternalSymbolName("FilaLightManagerShadowOptions_getCascadeSplitPositions")
internal external fun FilaLightManagerShadowOptions_getCascadeSplitPositions(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaLightManagerShadowOptions_setCascadeSplitPositions")
internal external fun FilaLightManagerShadowOptions_setCascadeSplitPositions(self: NativePointer, value: NativePointer, valueCount: Int)

@ExternalSymbolName("FilaLightManagerShadowOptions_getConstantBias")
internal external fun FilaLightManagerShadowOptions_getConstantBias(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setConstantBias")
internal external fun FilaLightManagerShadowOptions_setConstantBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getNormalBias")
internal external fun FilaLightManagerShadowOptions_getNormalBias(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setNormalBias")
internal external fun FilaLightManagerShadowOptions_setNormalBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getShadowFar")
internal external fun FilaLightManagerShadowOptions_getShadowFar(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setShadowFar")
internal external fun FilaLightManagerShadowOptions_setShadowFar(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getShadowNearHint")
internal external fun FilaLightManagerShadowOptions_getShadowNearHint(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setShadowNearHint")
internal external fun FilaLightManagerShadowOptions_setShadowNearHint(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getShadowFarHint")
internal external fun FilaLightManagerShadowOptions_getShadowFarHint(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setShadowFarHint")
internal external fun FilaLightManagerShadowOptions_setShadowFarHint(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getStable")
internal external fun FilaLightManagerShadowOptions_getStable(self: NativePointer): Boolean

@ExternalSymbolName("FilaLightManagerShadowOptions_setStable")
internal external fun FilaLightManagerShadowOptions_setStable(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaLightManagerShadowOptions_getLispsm")
internal external fun FilaLightManagerShadowOptions_getLispsm(self: NativePointer): Boolean

@ExternalSymbolName("FilaLightManagerShadowOptions_setLispsm")
internal external fun FilaLightManagerShadowOptions_setLispsm(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaLightManagerShadowOptions_getPolygonOffsetConstant")
internal external fun FilaLightManagerShadowOptions_getPolygonOffsetConstant(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setPolygonOffsetConstant")
internal external fun FilaLightManagerShadowOptions_setPolygonOffsetConstant(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getPolygonOffsetSlope")
internal external fun FilaLightManagerShadowOptions_getPolygonOffsetSlope(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setPolygonOffsetSlope")
internal external fun FilaLightManagerShadowOptions_setPolygonOffsetSlope(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getScreenSpaceContactShadows")
internal external fun FilaLightManagerShadowOptions_getScreenSpaceContactShadows(self: NativePointer): Boolean

@ExternalSymbolName("FilaLightManagerShadowOptions_setScreenSpaceContactShadows")
internal external fun FilaLightManagerShadowOptions_setScreenSpaceContactShadows(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaLightManagerShadowOptions_getStepCount")
internal external fun FilaLightManagerShadowOptions_getStepCount(self: NativePointer): Int

@ExternalSymbolName("FilaLightManagerShadowOptions_setStepCount")
internal external fun FilaLightManagerShadowOptions_setStepCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaLightManagerShadowOptions_getMaxShadowDistance")
internal external fun FilaLightManagerShadowOptions_getMaxShadowDistance(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setMaxShadowDistance")
internal external fun FilaLightManagerShadowOptions_setMaxShadowDistance(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getVsm")
internal external fun FilaLightManagerShadowOptions_getVsm(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptions_setVsm")
internal external fun FilaLightManagerShadowOptions_setVsm(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptions_getShadowBulbRadius")
internal external fun FilaLightManagerShadowOptions_getShadowBulbRadius(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setShadowBulbRadius")
internal external fun FilaLightManagerShadowOptions_setShadowBulbRadius(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getTransform")
internal external fun FilaLightManagerShadowOptions_getTransform(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptions_setTransform")
internal external fun FilaLightManagerShadowOptions_setTransform(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaLightManagerShadowOptions_getPenumbraScale")
internal external fun FilaLightManagerShadowOptions_getPenumbraScale(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setPenumbraScale")
internal external fun FilaLightManagerShadowOptions_setPenumbraScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getPenumbraRatioScale")
internal external fun FilaLightManagerShadowOptions_getPenumbraRatioScale(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setPenumbraRatioScale")
internal external fun FilaLightManagerShadowOptions_setPenumbraRatioScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getMaxPenumbraRatio")
internal external fun FilaLightManagerShadowOptions_getMaxPenumbraRatio(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setMaxPenumbraRatio")
internal external fun FilaLightManagerShadowOptions_setMaxPenumbraRatio(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowOptions_getMaxSearchRadius")
internal external fun FilaLightManagerShadowOptions_getMaxSearchRadius(self: NativePointer): Float

@ExternalSymbolName("FilaLightManagerShadowOptions_setMaxSearchRadius")
internal external fun FilaLightManagerShadowOptions_setMaxSearchRadius(self: NativePointer, value: Float)

@ExternalSymbolName("FilaLightManagerShadowCascades_computeUniformSplits")
internal external fun FilaLightManagerShadowCascades_computeUniformSplits(splitPositions: NativePointer, cascades: Int)

@ExternalSymbolName("FilaLightManagerShadowCascades_computeLogSplits")
internal external fun FilaLightManagerShadowCascades_computeLogSplits(splitPositions: NativePointer, cascades: Int, near: Float, far: Float)

@ExternalSymbolName("FilaLightManagerShadowCascades_computePracticalSplits")
internal external fun FilaLightManagerShadowCascades_computePracticalSplits(splitPositions: NativePointer, cascades: Int, near: Float, far: Float, lambda: Float)

@ExternalSymbolName("FilaLightManagerBuilder_create")
internal external fun FilaLightManagerBuilder_create(type: Int): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_destroy")
internal external fun FilaLightManagerBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaLightManagerBuilder_lightChannel")
internal external fun FilaLightManagerBuilder_lightChannel(self: NativePointer, channel: Int, enable: Boolean): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_castShadows")
internal external fun FilaLightManagerBuilder_castShadows(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_shadowOptions")
internal external fun FilaLightManagerBuilder_shadowOptions(self: NativePointer, options: NativePointer): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_castLight")
internal external fun FilaLightManagerBuilder_castLight(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_position")
internal external fun FilaLightManagerBuilder_position(self: NativePointer, position: NativePointer): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_direction")
internal external fun FilaLightManagerBuilder_direction(self: NativePointer, direction: NativePointer): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_color")
internal external fun FilaLightManagerBuilder_color(self: NativePointer, color: NativePointer): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_intensity")
internal external fun FilaLightManagerBuilder_intensity(self: NativePointer, intensity: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_intensity_float")
internal external fun FilaLightManagerBuilder_intensity_float(self: NativePointer, watts: Float, efficiency: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_intensityCandela")
internal external fun FilaLightManagerBuilder_intensityCandela(self: NativePointer, intensity: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_falloff")
internal external fun FilaLightManagerBuilder_falloff(self: NativePointer, radius: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_spotLightCone")
internal external fun FilaLightManagerBuilder_spotLightCone(self: NativePointer, inner: Float, outer: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_sunAngularRadius")
internal external fun FilaLightManagerBuilder_sunAngularRadius(self: NativePointer, angularRadiusDeg: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_sunHaloSize")
internal external fun FilaLightManagerBuilder_sunHaloSize(self: NativePointer, haloSize: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_sunHaloFalloff")
internal external fun FilaLightManagerBuilder_sunHaloFalloff(self: NativePointer, haloFalloff: Float): NativePointer

@ExternalSymbolName("FilaLightManagerBuilder_build")
internal external fun FilaLightManagerBuilder_build(self: NativePointer, engine: NativePointer, entity: Int): Int

@ExternalSymbolName("FilaLightManager_getComponentCount")
internal external fun FilaLightManager_getComponentCount(self: NativePointer): Int

@ExternalSymbolName("FilaLightManager_hasComponent")
internal external fun FilaLightManager_hasComponent(self: NativePointer, e: Int): Boolean

@ExternalSymbolName("FilaLightManager_empty")
internal external fun FilaLightManager_empty(self: NativePointer): Boolean

@ExternalSymbolName("FilaLightManager_getEntity")
internal external fun FilaLightManager_getEntity(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaLightManager_getAllEntities")
internal external fun FilaLightManager_getAllEntities(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaLightManager_getInstance")
internal external fun FilaLightManager_getInstance(self: NativePointer, e: Int): Int

@ExternalSymbolName("FilaLightManager_destroy")
internal external fun FilaLightManager_destroy(self: NativePointer, e: Int)

@ExternalSymbolName("FilaLightManager_getType")
internal external fun FilaLightManager_getType(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaLightManager_isDirectional")
internal external fun FilaLightManager_isDirectional(self: NativePointer, i: Int): Boolean

@ExternalSymbolName("FilaLightManager_isPointLight")
internal external fun FilaLightManager_isPointLight(self: NativePointer, i: Int): Boolean

@ExternalSymbolName("FilaLightManager_isSpotLight")
internal external fun FilaLightManager_isSpotLight(self: NativePointer, i: Int): Boolean

@ExternalSymbolName("FilaLightManager_setLightChannel")
internal external fun FilaLightManager_setLightChannel(self: NativePointer, i: Int, channel: Int, enable: Boolean)

@ExternalSymbolName("FilaLightManager_getLightChannel")
internal external fun FilaLightManager_getLightChannel(self: NativePointer, i: Int, channel: Int): Boolean

@ExternalSymbolName("FilaLightManager_setPosition")
internal external fun FilaLightManager_setPosition(self: NativePointer, i: Int, position: NativePointer)

@ExternalSymbolName("FilaLightManager_getPosition")
internal external fun FilaLightManager_getPosition(self: NativePointer, i: Int, out: NativePointer)

@ExternalSymbolName("FilaLightManager_setDirection")
internal external fun FilaLightManager_setDirection(self: NativePointer, i: Int, direction: NativePointer)

@ExternalSymbolName("FilaLightManager_getDirection")
internal external fun FilaLightManager_getDirection(self: NativePointer, i: Int, out: NativePointer)

@ExternalSymbolName("FilaLightManager_setColor")
internal external fun FilaLightManager_setColor(self: NativePointer, i: Int, color: NativePointer)

@ExternalSymbolName("FilaLightManager_getColor")
internal external fun FilaLightManager_getColor(self: NativePointer, i: Int, out: NativePointer)

@ExternalSymbolName("FilaLightManager_setIntensity")
internal external fun FilaLightManager_setIntensity(self: NativePointer, i: Int, intensity: Float)

@ExternalSymbolName("FilaLightManager_setIntensity_float")
internal external fun FilaLightManager_setIntensity_float(self: NativePointer, i: Int, watts: Float, efficiency: Float)

@ExternalSymbolName("FilaLightManager_setIntensityCandela")
internal external fun FilaLightManager_setIntensityCandela(self: NativePointer, i: Int, intensity: Float)

@ExternalSymbolName("FilaLightManager_getIntensity")
internal external fun FilaLightManager_getIntensity(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_setFalloff")
internal external fun FilaLightManager_setFalloff(self: NativePointer, i: Int, radius: Float)

@ExternalSymbolName("FilaLightManager_getFalloff")
internal external fun FilaLightManager_getFalloff(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_setSpotLightCone")
internal external fun FilaLightManager_setSpotLightCone(self: NativePointer, i: Int, inner: Float, outer: Float)

@ExternalSymbolName("FilaLightManager_getSpotLightOuterCone")
internal external fun FilaLightManager_getSpotLightOuterCone(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_getSpotLightInnerCone")
internal external fun FilaLightManager_getSpotLightInnerCone(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_setSunAngularRadius")
internal external fun FilaLightManager_setSunAngularRadius(self: NativePointer, i: Int, angularRadius: Float)

@ExternalSymbolName("FilaLightManager_getSunAngularRadius")
internal external fun FilaLightManager_getSunAngularRadius(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_setSunHaloSize")
internal external fun FilaLightManager_setSunHaloSize(self: NativePointer, i: Int, haloSize: Float)

@ExternalSymbolName("FilaLightManager_getSunHaloSize")
internal external fun FilaLightManager_getSunHaloSize(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_setSunHaloFalloff")
internal external fun FilaLightManager_setSunHaloFalloff(self: NativePointer, i: Int, haloFalloff: Float)

@ExternalSymbolName("FilaLightManager_getSunHaloFalloff")
internal external fun FilaLightManager_getSunHaloFalloff(self: NativePointer, i: Int): Float

@ExternalSymbolName("FilaLightManager_getShadowOptions")
internal external fun FilaLightManager_getShadowOptions(self: NativePointer, i: Int, out: NativePointer)

@ExternalSymbolName("FilaLightManager_setShadowOptions")
internal external fun FilaLightManager_setShadowOptions(self: NativePointer, i: Int, options: NativePointer)

@ExternalSymbolName("FilaLightManager_setShadowCaster")
internal external fun FilaLightManager_setShadowCaster(self: NativePointer, i: Int, shadowCaster: Boolean)

@ExternalSymbolName("FilaLightManager_isShadowCaster")
internal external fun FilaLightManager_isShadowCaster(self: NativePointer, i: Int): Boolean
