// Generated by generateKotlinExternals from c/filament/generated/FilaGT7ToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGT7ToneMapper_create")
internal external fun FilaGT7ToneMapper_create(): NativePointer

@ExternalSymbolName("FilaGT7ToneMapper_destroy")
internal external fun FilaGT7ToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaGT7ToneMapper_asToneMapper")
internal external fun FilaGT7ToneMapper_asToneMapper(self: NativePointer): NativePointer
