// Generated by generateKotlinExternals from c/filament/generated/FilaFrameHistoryStream.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFrameHistoryStreamNewFramesRange_create")
internal external fun FilaFrameHistoryStreamNewFramesRange_create(history: NativePointer, historyCount: Int, pLastProcessedFrameId: NativePointer): NativePointer

@ExternalSymbolName("FilaFrameHistoryStream_create")
internal external fun FilaFrameHistoryStream_create(renderer: NativePointer): NativePointer

@ExternalSymbolName("FilaFrameHistoryStream_destroy")
internal external fun FilaFrameHistoryStream_destroy(self: NativePointer)
