// Generated by generateKotlinExternals from c/filament/generated/FilaVsmShadowOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaVsmShadowOptions_create")
internal external fun FilaVsmShadowOptions_create(): NativePointer

@ExternalSymbolName("FilaVsmShadowOptions_destroy")
internal external fun FilaVsmShadowOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaVsmShadowOptions_getAnisotropy")
internal external fun FilaVsmShadowOptions_getAnisotropy(self: NativePointer): Int

@ExternalSymbolName("FilaVsmShadowOptions_setAnisotropy")
internal external fun FilaVsmShadowOptions_setAnisotropy(self: NativePointer, value: Int)

@ExternalSymbolName("FilaVsmShadowOptions_getMipmapping")
internal external fun FilaVsmShadowOptions_getMipmapping(self: NativePointer): Boolean

@ExternalSymbolName("FilaVsmShadowOptions_setMipmapping")
internal external fun FilaVsmShadowOptions_setMipmapping(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaVsmShadowOptions_getMsaaSamples")
internal external fun FilaVsmShadowOptions_getMsaaSamples(self: NativePointer): Int

@ExternalSymbolName("FilaVsmShadowOptions_setMsaaSamples")
internal external fun FilaVsmShadowOptions_setMsaaSamples(self: NativePointer, value: Int)

@ExternalSymbolName("FilaVsmShadowOptions_getHighPrecision")
internal external fun FilaVsmShadowOptions_getHighPrecision(self: NativePointer): Boolean

@ExternalSymbolName("FilaVsmShadowOptions_setHighPrecision")
internal external fun FilaVsmShadowOptions_setHighPrecision(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaVsmShadowOptions_getMinVarianceScale")
internal external fun FilaVsmShadowOptions_getMinVarianceScale(self: NativePointer): Float

@ExternalSymbolName("FilaVsmShadowOptions_setMinVarianceScale")
internal external fun FilaVsmShadowOptions_setMinVarianceScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaVsmShadowOptions_getLightBleedReduction")
internal external fun FilaVsmShadowOptions_getLightBleedReduction(self: NativePointer): Float

@ExternalSymbolName("FilaVsmShadowOptions_setLightBleedReduction")
internal external fun FilaVsmShadowOptions_setLightBleedReduction(self: NativePointer, value: Float)
