// Generated by generateKotlinExternals from c/filament/generated/FilaMaterialInstance.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaMaterialInstance_duplicate")
internal external fun FilaMaterialInstance_duplicate(other: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterialInstance_getMaterial")
internal external fun FilaMaterialInstance_getMaterial(self: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterialInstance_getName")
internal external fun FilaMaterialInstance_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterialInstance_setParameter_Texture_TextureSampler")
internal external fun FilaMaterialInstance_setParameter_Texture_TextureSampler(self: NativePointer, name: NativePointer, texture: NativePointer, sampler: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_RgbType_float3")
internal external fun FilaMaterialInstance_setParameter_RgbType_float3(self: NativePointer, name: NativePointer, type: Int, color: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_RgbaType_float4")
internal external fun FilaMaterialInstance_setParameter_RgbaType_float4(self: NativePointer, name: NativePointer, type: Int, color: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float")
internal external fun FilaMaterialInstance_setParameter_float(self: NativePointer, name: NativePointer, value: Float)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int32_t")
internal external fun FilaMaterialInstance_setParameter_int32_t(self: NativePointer, name: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint32_t")
internal external fun FilaMaterialInstance_setParameter_uint32_t(self: NativePointer, name: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int2")
internal external fun FilaMaterialInstance_setParameter_int2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int3")
internal external fun FilaMaterialInstance_setParameter_int3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int4")
internal external fun FilaMaterialInstance_setParameter_int4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint2")
internal external fun FilaMaterialInstance_setParameter_uint2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint3")
internal external fun FilaMaterialInstance_setParameter_uint3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint4")
internal external fun FilaMaterialInstance_setParameter_uint4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float2")
internal external fun FilaMaterialInstance_setParameter_float2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float3")
internal external fun FilaMaterialInstance_setParameter_float3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float4")
internal external fun FilaMaterialInstance_setParameter_float4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_mat3f")
internal external fun FilaMaterialInstance_setParameter_mat3f(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_mat4f")
internal external fun FilaMaterialInstance_setParameter_mat4f(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool")
internal external fun FilaMaterialInstance_setParameter_bool(self: NativePointer, name: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool2")
internal external fun FilaMaterialInstance_setParameter_bool2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool3")
internal external fun FilaMaterialInstance_setParameter_bool3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool4")
internal external fun FilaMaterialInstance_setParameter_bool4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float_size_t")
internal external fun FilaMaterialInstance_setParameter_float_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int32_t_size_t")
internal external fun FilaMaterialInstance_setParameter_int32_t_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint32_t_size_t")
internal external fun FilaMaterialInstance_setParameter_uint32_t_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int2_size_t")
internal external fun FilaMaterialInstance_setParameter_int2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int3_size_t")
internal external fun FilaMaterialInstance_setParameter_int3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_int4_size_t")
internal external fun FilaMaterialInstance_setParameter_int4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint2_size_t")
internal external fun FilaMaterialInstance_setParameter_uint2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint3_size_t")
internal external fun FilaMaterialInstance_setParameter_uint3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_uint4_size_t")
internal external fun FilaMaterialInstance_setParameter_uint4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float2_size_t")
internal external fun FilaMaterialInstance_setParameter_float2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float3_size_t")
internal external fun FilaMaterialInstance_setParameter_float3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_float4_size_t")
internal external fun FilaMaterialInstance_setParameter_float4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_mat3f_size_t")
internal external fun FilaMaterialInstance_setParameter_mat3f_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_mat4f_size_t")
internal external fun FilaMaterialInstance_setParameter_mat4f_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool_size_t")
internal external fun FilaMaterialInstance_setParameter_bool_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool2_size_t")
internal external fun FilaMaterialInstance_setParameter_bool2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool3_size_t")
internal external fun FilaMaterialInstance_setParameter_bool3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_setParameter_bool4_size_t")
internal external fun FilaMaterialInstance_setParameter_bool4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterialInstance_getParameter_float")
internal external fun FilaMaterialInstance_getParameter_float(self: NativePointer, name: NativePointer): Float

@ExternalSymbolName("FilaMaterialInstance_getParameter_int32_t")
internal external fun FilaMaterialInstance_getParameter_int32_t(self: NativePointer, name: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_getParameter_uint32_t")
internal external fun FilaMaterialInstance_getParameter_uint32_t(self: NativePointer, name: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_getParameter_int2")
internal external fun FilaMaterialInstance_getParameter_int2(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_int3")
internal external fun FilaMaterialInstance_getParameter_int3(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_int4")
internal external fun FilaMaterialInstance_getParameter_int4(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_uint2")
internal external fun FilaMaterialInstance_getParameter_uint2(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_uint3")
internal external fun FilaMaterialInstance_getParameter_uint3(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_uint4")
internal external fun FilaMaterialInstance_getParameter_uint4(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_float2")
internal external fun FilaMaterialInstance_getParameter_float2(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_float3")
internal external fun FilaMaterialInstance_getParameter_float3(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_float4")
internal external fun FilaMaterialInstance_getParameter_float4(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_mat3f")
internal external fun FilaMaterialInstance_getParameter_mat3f(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_getParameter_mat4f")
internal external fun FilaMaterialInstance_getParameter_mat4f(self: NativePointer, name: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setConstant_int32_t")
internal external fun FilaMaterialInstance_setConstant_int32_t(self: NativePointer, name: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialInstance_setConstant_float")
internal external fun FilaMaterialInstance_setConstant_float(self: NativePointer, name: NativePointer, value: Float)

@ExternalSymbolName("FilaMaterialInstance_setConstant_bool")
internal external fun FilaMaterialInstance_setConstant_bool(self: NativePointer, name: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterialInstance_getConstant_int32_t")
internal external fun FilaMaterialInstance_getConstant_int32_t(self: NativePointer, name: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_getConstant_float")
internal external fun FilaMaterialInstance_getConstant_float(self: NativePointer, name: NativePointer): Float

@ExternalSymbolName("FilaMaterialInstance_getConstant_bool")
internal external fun FilaMaterialInstance_getConstant_bool(self: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_compile_UserVariantFilterMask_CallbackHandler_Invocable")
internal external fun FilaMaterialInstance_compile_UserVariantFilterMask_CallbackHandler_Invocable(self: NativePointer, priority: Int, variants: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_compile_UserVariantFilterBit_CallbackHandler_Invocable")
internal external fun FilaMaterialInstance_compile_UserVariantFilterBit_CallbackHandler_Invocable(self: NativePointer, priority: Int, variants: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_compile_CallbackHandler_Invocable")
internal external fun FilaMaterialInstance_compile_CallbackHandler_Invocable(self: NativePointer, priority: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setScissor")
internal external fun FilaMaterialInstance_setScissor(self: NativePointer, left: Int, bottom: Int, width: Int, height: Int)

@ExternalSymbolName("FilaMaterialInstance_unsetScissor")
internal external fun FilaMaterialInstance_unsetScissor(self: NativePointer)

@ExternalSymbolName("FilaMaterialInstance_setPolygonOffset")
internal external fun FilaMaterialInstance_setPolygonOffset(self: NativePointer, scale: Float, constant: Float)

@ExternalSymbolName("FilaMaterialInstance_setMaskThreshold")
internal external fun FilaMaterialInstance_setMaskThreshold(self: NativePointer, threshold: Float)

@ExternalSymbolName("FilaMaterialInstance_getMaskThreshold")
internal external fun FilaMaterialInstance_getMaskThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaMaterialInstance_setSpecularAntiAliasingVariance")
internal external fun FilaMaterialInstance_setSpecularAntiAliasingVariance(self: NativePointer, variance: Float)

@ExternalSymbolName("FilaMaterialInstance_getSpecularAntiAliasingVariance")
internal external fun FilaMaterialInstance_getSpecularAntiAliasingVariance(self: NativePointer): Float

@ExternalSymbolName("FilaMaterialInstance_setSpecularAntiAliasingThreshold")
internal external fun FilaMaterialInstance_setSpecularAntiAliasingThreshold(self: NativePointer, threshold: Float)

@ExternalSymbolName("FilaMaterialInstance_getSpecularAntiAliasingThreshold")
internal external fun FilaMaterialInstance_getSpecularAntiAliasingThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaMaterialInstance_setDoubleSided")
internal external fun FilaMaterialInstance_setDoubleSided(self: NativePointer, doubleSided: Boolean)

@ExternalSymbolName("FilaMaterialInstance_isDoubleSided")
internal external fun FilaMaterialInstance_isDoubleSided(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_setTransparencyMode")
internal external fun FilaMaterialInstance_setTransparencyMode(self: NativePointer, mode: Int)

@ExternalSymbolName("FilaMaterialInstance_getTransparencyMode")
internal external fun FilaMaterialInstance_getTransparencyMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_setCullingMode")
internal external fun FilaMaterialInstance_setCullingMode(self: NativePointer, culling: Int)

@ExternalSymbolName("FilaMaterialInstance_setCullingMode_CullingMode")
internal external fun FilaMaterialInstance_setCullingMode_CullingMode(self: NativePointer, colorPassCullingMode: Int, shadowPassCullingMode: Int)

@ExternalSymbolName("FilaMaterialInstance_getCullingMode")
internal external fun FilaMaterialInstance_getCullingMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_getShadowCullingMode")
internal external fun FilaMaterialInstance_getShadowCullingMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_setColorWrite")
internal external fun FilaMaterialInstance_setColorWrite(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaMaterialInstance_isColorWriteEnabled")
internal external fun FilaMaterialInstance_isColorWriteEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_setDepthWrite")
internal external fun FilaMaterialInstance_setDepthWrite(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaMaterialInstance_isDepthWriteEnabled")
internal external fun FilaMaterialInstance_isDepthWriteEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_setDepthCulling")
internal external fun FilaMaterialInstance_setDepthCulling(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaMaterialInstance_setDepthFunc")
internal external fun FilaMaterialInstance_setDepthFunc(self: NativePointer, depthFunc: Int)

@ExternalSymbolName("FilaMaterialInstance_getDepthFunc")
internal external fun FilaMaterialInstance_getDepthFunc(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialInstance_isDepthCullingEnabled")
internal external fun FilaMaterialInstance_isDepthCullingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_setStencilWrite")
internal external fun FilaMaterialInstance_setStencilWrite(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaMaterialInstance_isStencilWriteEnabled")
internal external fun FilaMaterialInstance_isStencilWriteEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialInstance_setStencilCompareFunction")
internal external fun FilaMaterialInstance_setStencilCompareFunction(self: NativePointer, func: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilOpStencilFail")
internal external fun FilaMaterialInstance_setStencilOpStencilFail(self: NativePointer, op: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilOpDepthFail")
internal external fun FilaMaterialInstance_setStencilOpDepthFail(self: NativePointer, op: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilOpDepthStencilPass")
internal external fun FilaMaterialInstance_setStencilOpDepthStencilPass(self: NativePointer, op: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilReferenceValue")
internal external fun FilaMaterialInstance_setStencilReferenceValue(self: NativePointer, value: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilReadMask")
internal external fun FilaMaterialInstance_setStencilReadMask(self: NativePointer, readMask: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_setStencilWriteMask")
internal external fun FilaMaterialInstance_setStencilWriteMask(self: NativePointer, writeMask: Int, face: Int)

@ExternalSymbolName("FilaMaterialInstance_commit")
internal external fun FilaMaterialInstance_commit(self: NativePointer, engine: NativePointer)
