// Generated by generateKotlinExternals from c/filament/generated/FilaColor.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColor_toLinear_RgbType_float3")
internal external fun FilaColor_toLinear_RgbType_float3(type: Int, color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_toLinear_RgbaType_float4")
internal external fun FilaColor_toLinear_RgbaType_float4(type: Int, color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_toLinear_sRGBColor")
internal external fun FilaColor_toLinear_sRGBColor(color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_toLinear_sRGBColorA")
internal external fun FilaColor_toLinear_sRGBColorA(color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_toSRGB_LinearColor")
internal external fun FilaColor_toSRGB_LinearColor(color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_toSRGB_LinearColorA")
internal external fun FilaColor_toSRGB_LinearColorA(color: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColor_cct")
internal external fun FilaColor_cct(K: Float, out: NativePointer)

@ExternalSymbolName("FilaColor_illuminantD")
internal external fun FilaColor_illuminantD(K: Float, out: NativePointer)

@ExternalSymbolName("FilaColor_absorptionAtDistance")
internal external fun FilaColor_absorptionAtDistance(color: NativePointer, distance: Float, out: NativePointer)
