// Generated by generateKotlinExternals from c/filament/generated/FilaFilmicToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFilmicToneMapper_create")
internal external fun FilaFilmicToneMapper_create(): NativePointer

@ExternalSymbolName("FilaFilmicToneMapper_destroy")
internal external fun FilaFilmicToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaFilmicToneMapper_asToneMapper")
internal external fun FilaFilmicToneMapper_asToneMapper(self: NativePointer): NativePointer
