// Generated by generateKotlinExternals from c/filament/generated/FilaLinearToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaLinearToneMapper_create")
internal external fun FilaLinearToneMapper_create(): NativePointer

@ExternalSymbolName("FilaLinearToneMapper_destroy")
internal external fun FilaLinearToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaLinearToneMapper_asToneMapper")
internal external fun FilaLinearToneMapper_asToneMapper(self: NativePointer): NativePointer
