// Generated by generateKotlinExternals from c/filament/generated/FilaVertexBuffer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_create")
internal external fun FilaVertexBufferBuilder_create(): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_destroy")
internal external fun FilaVertexBufferBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaVertexBufferBuilder_bufferCount")
internal external fun FilaVertexBufferBuilder_bufferCount(self: NativePointer, bufferCount: Int): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_vertexCount")
internal external fun FilaVertexBufferBuilder_vertexCount(self: NativePointer, vertexCount: Int): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_enableBufferObjects")
internal external fun FilaVertexBufferBuilder_enableBufferObjects(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_attribute")
internal external fun FilaVertexBufferBuilder_attribute(self: NativePointer, attribute: Int, bufferIndex: Int, attributeType: Int, byteOffset: Int, byteStride: Int): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_normalized")
internal external fun FilaVertexBufferBuilder_normalized(self: NativePointer, attribute: Int, normalized: Boolean): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_advancedSkinning")
internal external fun FilaVertexBufferBuilder_advancedSkinning(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_name")
internal external fun FilaVertexBufferBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_async")
internal external fun FilaVertexBufferBuilder_async(self: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): NativePointer

@ExternalSymbolName("FilaVertexBufferBuilder_build")
internal external fun FilaVertexBufferBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaVertexBuffer_getVertexCount")
internal external fun FilaVertexBuffer_getVertexCount(self: NativePointer): Int

@ExternalSymbolName("FilaVertexBuffer_setBufferAt")
internal external fun FilaVertexBuffer_setBufferAt(self: NativePointer, engine: NativePointer, bufferIndex: Int, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer, byteOffset: Int)

@ExternalSymbolName("FilaVertexBuffer_setBufferAtAsync")
internal external fun FilaVertexBuffer_setBufferAtAsync(self: NativePointer, engine: NativePointer, bufferIndex: Int, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer, byteOffset: Int, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaVertexBuffer_setBufferObjectAt")
internal external fun FilaVertexBuffer_setBufferObjectAt(self: NativePointer, engine: NativePointer, bufferIndex: Int, bufferObject: NativePointer)

@ExternalSymbolName("FilaVertexBuffer_setBufferObjectAtAsync")
internal external fun FilaVertexBuffer_setBufferObjectAtAsync(self: NativePointer, engine: NativePointer, bufferIndex: Int, bufferObject: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaVertexBuffer_isCreationComplete")
internal external fun FilaVertexBuffer_isCreationComplete(self: NativePointer): Boolean
