// Generated by generateKotlinExternals from c/filament/generated/FilaFramePipelineEstimator.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_create")
internal external fun FilaFramePipelineEstimatorWorkload_create(): NativePointer

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_destroy")
internal external fun FilaFramePipelineEstimatorWorkload_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_getIdealFrameDuration")
internal external fun FilaFramePipelineEstimatorWorkload_getIdealFrameDuration(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_setIdealFrameDuration")
internal external fun FilaFramePipelineEstimatorWorkload_setIdealFrameDuration(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_getIdealFrameRate")
internal external fun FilaFramePipelineEstimatorWorkload_getIdealFrameRate(self: NativePointer): Float

@ExternalSymbolName("FilaFramePipelineEstimatorWorkload_setIdealFrameRate")
internal external fun FilaFramePipelineEstimatorWorkload_setIdealFrameRate(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_create")
internal external fun FilaFramePipelineEstimatorPacingSizing_create(): NativePointer

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_destroy")
internal external fun FilaFramePipelineEstimatorPacingSizing_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_getLatencyFrames")
internal external fun FilaFramePipelineEstimatorPacingSizing_getLatencyFrames(self: NativePointer): Int

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_setLatencyFrames")
internal external fun FilaFramePipelineEstimatorPacingSizing_setLatencyFrames(self: NativePointer, value: Int)

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_getSafeDelayDuration")
internal external fun FilaFramePipelineEstimatorPacingSizing_getSafeDelayDuration(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimatorPacingSizing_setSafeDelayDuration")
internal external fun FilaFramePipelineEstimatorPacingSizing_setSafeDelayDuration(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePipelineEstimator_getZScore")
internal external fun FilaFramePipelineEstimator_getZScore(targetPercentile: Int): Double

@ExternalSymbolName("FilaFramePipelineEstimator_estimateWorkload_TargetPercentile")
internal external fun FilaFramePipelineEstimator_estimateWorkload_TargetPercentile(history: NativePointer, historyCount: Int, targetPercentile: Int, out: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimator_estimateWorkload_double")
internal external fun FilaFramePipelineEstimator_estimateWorkload_double(history: NativePointer, historyCount: Int, zScore: Double, out: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimator_estimatePacing_TargetPercentile")
internal external fun FilaFramePipelineEstimator_estimatePacing_TargetPercentile(history: NativePointer, historyCount: Int, pacingPeriod: Long, targetPercentile: Int, out: NativePointer)

@ExternalSymbolName("FilaFramePipelineEstimator_estimatePacing_double")
internal external fun FilaFramePipelineEstimator_estimatePacing_double(history: NativePointer, historyCount: Int, pacingPeriod: Long, zScore: Double, out: NativePointer)
