// Generated by generateKotlinExternals from c/filament/generated/FilaAgxToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaAgxToneMapper_create")
internal external fun FilaAgxToneMapper_create(look: Int): NativePointer

@ExternalSymbolName("FilaAgxToneMapper_destroy")
internal external fun FilaAgxToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaAgxToneMapper_asToneMapper")
internal external fun FilaAgxToneMapper_asToneMapper(self: NativePointer): NativePointer

@ExternalSymbolName("FilaAgxToneMapper_getLook")
internal external fun FilaAgxToneMapper_getLook(self: NativePointer): Int

@ExternalSymbolName("FilaAgxToneMapper_setLook")
internal external fun FilaAgxToneMapper_setLook(self: NativePointer, value: Int)
