// Generated by generateKotlinExternals from c/filament/generated/FilaCamera.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaCamera_projection_Fov_double_double_double_double")
internal external fun FilaCamera_projection_Fov_double_double_double_double(direction: Int, fovInDegrees: Double, aspect: Double, near: Double, far: Double, out: NativePointer)

@ExternalSymbolName("FilaCamera_projection_double_double_double_double")
internal external fun FilaCamera_projection_double_double_double_double(focalLengthInMillimeters: Double, aspect: Double, near: Double, far: Double, out: NativePointer)

@ExternalSymbolName("FilaCamera_setProjection_Projection_double_double_double_double_double_double")
internal external fun FilaCamera_setProjection_Projection_double_double_double_double_double_double(self: NativePointer, projection: Int, left: Double, right: Double, bottom: Double, top: Double, near: Double, far: Double)

@ExternalSymbolName("FilaCamera_setProjection_double_double_double_double_Fov")
internal external fun FilaCamera_setProjection_double_double_double_double_Fov(self: NativePointer, fovInDegrees: Double, aspect: Double, near: Double, far: Double, direction: Int)

@ExternalSymbolName("FilaCamera_setLensProjection")
internal external fun FilaCamera_setLensProjection(self: NativePointer, focalLengthInMillimeters: Double, aspect: Double, near: Double, far: Double)

@ExternalSymbolName("FilaCamera_setCustomProjection_double_double")
internal external fun FilaCamera_setCustomProjection_double_double(self: NativePointer, projection: NativePointer, near: Double, far: Double)

@ExternalSymbolName("FilaCamera_setCustomProjection_mat4_double_double")
internal external fun FilaCamera_setCustomProjection_mat4_double_double(self: NativePointer, projection: NativePointer, projectionForCulling: NativePointer, near: Double, far: Double)

@ExternalSymbolName("FilaCamera_setCustomEyeProjection")
internal external fun FilaCamera_setCustomEyeProjection(self: NativePointer, projection: NativePointer, count: Int, projectionForCulling: NativePointer, near: Double, far: Double)

@ExternalSymbolName("FilaCamera_setScaling")
internal external fun FilaCamera_setScaling(self: NativePointer, scaling: NativePointer)

@ExternalSymbolName("FilaCamera_setShift")
internal external fun FilaCamera_setShift(self: NativePointer, shift: NativePointer)

@ExternalSymbolName("FilaCamera_getScaling")
internal external fun FilaCamera_getScaling(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getShift")
internal external fun FilaCamera_getShift(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getProjectionMatrix")
internal external fun FilaCamera_getProjectionMatrix(self: NativePointer, eyeId: Int, out: NativePointer)

@ExternalSymbolName("FilaCamera_getCullingProjectionMatrix")
internal external fun FilaCamera_getCullingProjectionMatrix(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getNear")
internal external fun FilaCamera_getNear(self: NativePointer): Double

@ExternalSymbolName("FilaCamera_getCullingFar")
internal external fun FilaCamera_getCullingFar(self: NativePointer): Double

@ExternalSymbolName("FilaCamera_setModelMatrix_mat4")
internal external fun FilaCamera_setModelMatrix_mat4(self: NativePointer, modelMatrix: NativePointer)

@ExternalSymbolName("FilaCamera_setModelMatrix_mat4f")
internal external fun FilaCamera_setModelMatrix_mat4f(self: NativePointer, modelMatrix: NativePointer)

@ExternalSymbolName("FilaCamera_setEyeModelMatrix")
internal external fun FilaCamera_setEyeModelMatrix(self: NativePointer, eyeId: Int, model: NativePointer)

@ExternalSymbolName("FilaCamera_lookAt")
internal external fun FilaCamera_lookAt(self: NativePointer, eye: NativePointer, center: NativePointer, up: NativePointer)

@ExternalSymbolName("FilaCamera_getModelMatrix")
internal external fun FilaCamera_getModelMatrix(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getViewMatrix")
internal external fun FilaCamera_getViewMatrix(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getEyeFromViewMatrix")
internal external fun FilaCamera_getEyeFromViewMatrix(self: NativePointer, eyeId: Int, out: NativePointer)

@ExternalSymbolName("FilaCamera_getPosition")
internal external fun FilaCamera_getPosition(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getLeftVector")
internal external fun FilaCamera_getLeftVector(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getUpVector")
internal external fun FilaCamera_getUpVector(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getForwardVector")
internal external fun FilaCamera_getForwardVector(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_getFieldOfViewInDegrees")
internal external fun FilaCamera_getFieldOfViewInDegrees(self: NativePointer, direction: Int): Float

@ExternalSymbolName("FilaCamera_getEntity")
internal external fun FilaCamera_getEntity(self: NativePointer): Int

@ExternalSymbolName("FilaCamera_setExposure_float_float")
internal external fun FilaCamera_setExposure_float_float(self: NativePointer, aperture: Float, shutterSpeed: Float, sensitivity: Float)

@ExternalSymbolName("FilaCamera_setExposure")
internal external fun FilaCamera_setExposure(self: NativePointer, exposure: Float)

@ExternalSymbolName("FilaCamera_getAperture")
internal external fun FilaCamera_getAperture(self: NativePointer): Float

@ExternalSymbolName("FilaCamera_getShutterSpeed")
internal external fun FilaCamera_getShutterSpeed(self: NativePointer): Float

@ExternalSymbolName("FilaCamera_getSensitivity")
internal external fun FilaCamera_getSensitivity(self: NativePointer): Float

@ExternalSymbolName("FilaCamera_getFocalLength")
internal external fun FilaCamera_getFocalLength(self: NativePointer): Double

@ExternalSymbolName("FilaCamera_setFocusDistance")
internal external fun FilaCamera_setFocusDistance(self: NativePointer, distance: Float)

@ExternalSymbolName("FilaCamera_getFocusDistance")
internal external fun FilaCamera_getFocusDistance(self: NativePointer): Float

@ExternalSymbolName("FilaCamera_inverseProjection_mat4")
internal external fun FilaCamera_inverseProjection_mat4(p: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_inverseProjection_mat4f")
internal external fun FilaCamera_inverseProjection_mat4f(p: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamera_computeEffectiveFocalLength")
internal external fun FilaCamera_computeEffectiveFocalLength(focalLength: Double, focusDistance: Double): Double

@ExternalSymbolName("FilaCamera_computeEffectiveFov")
internal external fun FilaCamera_computeEffectiveFov(fovInDegrees: Double, focusDistance: Double): Double
