// Generated by generateKotlinExternals from c/filament/generated/FilaAabb.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaAabbCorners_create")
internal external fun FilaAabbCorners_create(): NativePointer

@ExternalSymbolName("FilaAabbCorners_destroy")
internal external fun FilaAabbCorners_destroy(self: NativePointer)

@ExternalSymbolName("FilaAabbCorners_begin")
internal external fun FilaAabbCorners_begin(self: NativePointer): NativePointer

@ExternalSymbolName("FilaAabbCorners_end")
internal external fun FilaAabbCorners_end(self: NativePointer): NativePointer

@ExternalSymbolName("FilaAabbCorners_data")
internal external fun FilaAabbCorners_data(self: NativePointer): NativePointer

@ExternalSymbolName("FilaAabbCorners_size")
internal external fun FilaAabbCorners_size(self: NativePointer): Int

@ExternalSymbolName("FilaAabbCorners_getVertices")
internal external fun FilaAabbCorners_getVertices(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaAabbCorners_setVertices")
internal external fun FilaAabbCorners_setVertices(self: NativePointer, value: NativePointer, valueCount: Int)

@ExternalSymbolName("FilaAabb_create")
internal external fun FilaAabb_create(): NativePointer

@ExternalSymbolName("FilaAabb_destroy")
internal external fun FilaAabb_destroy(self: NativePointer)

@ExternalSymbolName("FilaAabb_center")
internal external fun FilaAabb_center(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_extent")
internal external fun FilaAabb_extent(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_isEmpty")
internal external fun FilaAabb_isEmpty(self: NativePointer): Boolean

@ExternalSymbolName("FilaAabb_getCorners")
internal external fun FilaAabb_getCorners(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_contains")
internal external fun FilaAabb_contains(self: NativePointer, p: NativePointer): Float

@ExternalSymbolName("FilaAabb_transform_mat3f_float3_Aabb")
internal external fun FilaAabb_transform_mat3f_float3_Aabb(m: NativePointer, t: NativePointer, box: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_transform_mat4f")
internal external fun FilaAabb_transform_mat4f(self: NativePointer, m: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_getMin")
internal external fun FilaAabb_getMin(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_setMin")
internal external fun FilaAabb_setMin(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaAabb_getMax")
internal external fun FilaAabb_getMax(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAabb_setMax")
internal external fun FilaAabb_setMax(self: NativePointer, value: NativePointer)
