// Generated by generateKotlinExternals from c/filament/generated/FilaFogOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFogOptions_create")
internal external fun FilaFogOptions_create(): NativePointer

@ExternalSymbolName("FilaFogOptions_destroy")
internal external fun FilaFogOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaFogOptions_getDistance")
internal external fun FilaFogOptions_getDistance(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setDistance")
internal external fun FilaFogOptions_setDistance(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getCutOffDistance")
internal external fun FilaFogOptions_getCutOffDistance(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setCutOffDistance")
internal external fun FilaFogOptions_setCutOffDistance(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getMaximumOpacity")
internal external fun FilaFogOptions_getMaximumOpacity(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setMaximumOpacity")
internal external fun FilaFogOptions_setMaximumOpacity(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getHeight")
internal external fun FilaFogOptions_getHeight(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setHeight")
internal external fun FilaFogOptions_setHeight(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getHeightFalloff")
internal external fun FilaFogOptions_getHeightFalloff(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setHeightFalloff")
internal external fun FilaFogOptions_setHeightFalloff(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getColor")
internal external fun FilaFogOptions_getColor(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFogOptions_setColor")
internal external fun FilaFogOptions_setColor(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaFogOptions_getDensity")
internal external fun FilaFogOptions_getDensity(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setDensity")
internal external fun FilaFogOptions_setDensity(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getInScatteringStart")
internal external fun FilaFogOptions_getInScatteringStart(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setInScatteringStart")
internal external fun FilaFogOptions_setInScatteringStart(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getInScatteringSize")
internal external fun FilaFogOptions_getInScatteringSize(self: NativePointer): Float

@ExternalSymbolName("FilaFogOptions_setInScatteringSize")
internal external fun FilaFogOptions_setInScatteringSize(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFogOptions_getFogColorFromIbl")
internal external fun FilaFogOptions_getFogColorFromIbl(self: NativePointer): Boolean

@ExternalSymbolName("FilaFogOptions_setFogColorFromIbl")
internal external fun FilaFogOptions_setFogColorFromIbl(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaFogOptions_getSkyColor")
internal external fun FilaFogOptions_getSkyColor(self: NativePointer): NativePointer

@ExternalSymbolName("FilaFogOptions_setSkyColor")
internal external fun FilaFogOptions_setSkyColor(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaFogOptions_getEnabled")
internal external fun FilaFogOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaFogOptions_setEnabled")
internal external fun FilaFogOptions_setEnabled(self: NativePointer, value: Boolean)
