// Generated by generateKotlinExternals from c/filament/generated/FilaColorGamut.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColorGamut_create_Primaries")
internal external fun FilaColorGamut_create_Primaries(primaries: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGamut_create_float2_float2_float2")
internal external fun FilaColorGamut_create_float2_float2_float2(r: NativePointer, g: NativePointer, b: NativePointer): NativePointer

@ExternalSymbolName("FilaColorGamut_getPrimaries")
internal external fun FilaColorGamut_getPrimaries(self: NativePointer, out: NativePointer)
