// Generated by generateKotlinExternals from c/filament/generated/FilaColorTransferFunction.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColorTransferFunction_create_double_double")
internal external fun FilaColorTransferFunction_create_double_double(a: Double, b: Double, c: Double, d: Double, e: Double, f: Double, g: Double): NativePointer

@ExternalSymbolName("FilaColorTransferFunction_create")
internal external fun FilaColorTransferFunction_create(a: Double, b: Double, c: Double, d: Double, g: Double): NativePointer

@ExternalSymbolName("FilaColorTransferFunction_destroy")
internal external fun FilaColorTransferFunction_destroy(self: NativePointer)

@ExternalSymbolName("FilaColorTransferFunction_getA")
internal external fun FilaColorTransferFunction_getA(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setA")
internal external fun FilaColorTransferFunction_setA(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getB")
internal external fun FilaColorTransferFunction_getB(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setB")
internal external fun FilaColorTransferFunction_setB(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getC")
internal external fun FilaColorTransferFunction_getC(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setC")
internal external fun FilaColorTransferFunction_setC(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getD")
internal external fun FilaColorTransferFunction_getD(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setD")
internal external fun FilaColorTransferFunction_setD(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getE")
internal external fun FilaColorTransferFunction_getE(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setE")
internal external fun FilaColorTransferFunction_setE(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getF")
internal external fun FilaColorTransferFunction_getF(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setF")
internal external fun FilaColorTransferFunction_setF(self: NativePointer, value: Double)

@ExternalSymbolName("FilaColorTransferFunction_getG")
internal external fun FilaColorTransferFunction_getG(self: NativePointer): Double

@ExternalSymbolName("FilaColorTransferFunction_setG")
internal external fun FilaColorTransferFunction_setG(self: NativePointer, value: Double)
