// Generated by generateKotlinExternals from c/filament/generated/FilaScene.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaScene_setSkybox")
internal external fun FilaScene_setSkybox(self: NativePointer, skybox: NativePointer)

@ExternalSymbolName("FilaScene_getSkybox")
internal external fun FilaScene_getSkybox(self: NativePointer): NativePointer

@ExternalSymbolName("FilaScene_setIndirectLight")
internal external fun FilaScene_setIndirectLight(self: NativePointer, ibl: NativePointer)

@ExternalSymbolName("FilaScene_getIndirectLight")
internal external fun FilaScene_getIndirectLight(self: NativePointer): NativePointer

@ExternalSymbolName("FilaScene_addEntity")
internal external fun FilaScene_addEntity(self: NativePointer, entity: Int)

@ExternalSymbolName("FilaScene_addEntities")
internal external fun FilaScene_addEntities(self: NativePointer, entities: NativePointer, count: Int)

@ExternalSymbolName("FilaScene_remove")
internal external fun FilaScene_remove(self: NativePointer, entity: Int)

@ExternalSymbolName("FilaScene_removeEntities")
internal external fun FilaScene_removeEntities(self: NativePointer, entities: NativePointer, count: Int)

@ExternalSymbolName("FilaScene_removeAllEntities")
internal external fun FilaScene_removeAllEntities(self: NativePointer)

@ExternalSymbolName("FilaScene_getEntityCount")
internal external fun FilaScene_getEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaScene_getRenderableCount")
internal external fun FilaScene_getRenderableCount(self: NativePointer): Int

@ExternalSymbolName("FilaScene_getLightCount")
internal external fun FilaScene_getLightCount(self: NativePointer): Int

@ExternalSymbolName("FilaScene_hasEntity")
internal external fun FilaScene_hasEntity(self: NativePointer, entity: Int): Boolean
