// Generated by generateKotlinExternals from c/filament/generated/FilaSkinningBuffer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaSkinningBufferBuilder_create")
internal external fun FilaSkinningBufferBuilder_create(): NativePointer

@ExternalSymbolName("FilaSkinningBufferBuilder_destroy")
internal external fun FilaSkinningBufferBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaSkinningBufferBuilder_boneCount")
internal external fun FilaSkinningBufferBuilder_boneCount(self: NativePointer, boneCount: Int): NativePointer

@ExternalSymbolName("FilaSkinningBufferBuilder_initialize")
internal external fun FilaSkinningBufferBuilder_initialize(self: NativePointer, initialize: Boolean): NativePointer

@ExternalSymbolName("FilaSkinningBufferBuilder_name")
internal external fun FilaSkinningBufferBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaSkinningBufferBuilder_build")
internal external fun FilaSkinningBufferBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaSkinningBuffer_setBones_Bone_size_t_size_t")
internal external fun FilaSkinningBuffer_setBones_Bone_size_t_size_t(self: NativePointer, engine: NativePointer, transforms: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaSkinningBuffer_setBones_mat4f_size_t_size_t")
internal external fun FilaSkinningBuffer_setBones_mat4f_size_t_size_t(self: NativePointer, engine: NativePointer, transforms: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaSkinningBuffer_getBoneCount")
internal external fun FilaSkinningBuffer_getBoneCount(self: NativePointer): Int
