// Generated by generateKotlinExternals from c/filament/generated/FilaRenderer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaRendererDisplayInfo_create")
internal external fun FilaRendererDisplayInfo_create(): NativePointer

@ExternalSymbolName("FilaRendererDisplayInfo_destroy")
internal external fun FilaRendererDisplayInfo_destroy(self: NativePointer)

@ExternalSymbolName("FilaRendererDisplayInfo_getRefreshRate")
internal external fun FilaRendererDisplayInfo_getRefreshRate(self: NativePointer): Float

@ExternalSymbolName("FilaRendererDisplayInfo_setRefreshRate")
internal external fun FilaRendererDisplayInfo_setRefreshRate(self: NativePointer, value: Float)

@ExternalSymbolName("FilaRendererFrameInfo_create")
internal external fun FilaRendererFrameInfo_create(): NativePointer

@ExternalSymbolName("FilaRendererFrameInfo_destroy")
internal external fun FilaRendererFrameInfo_destroy(self: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_getFrameId")
internal external fun FilaRendererFrameInfo_getFrameId(self: NativePointer): Int

@ExternalSymbolName("FilaRendererFrameInfo_setFrameId")
internal external fun FilaRendererFrameInfo_setFrameId(self: NativePointer, value: Int)

@ExternalSymbolName("FilaRendererFrameInfo_getGpuFrameDuration")
internal external fun FilaRendererFrameInfo_getGpuFrameDuration(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setGpuFrameDuration")
internal external fun FilaRendererFrameInfo_setGpuFrameDuration(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getDenoisedGpuFrameDuration")
internal external fun FilaRendererFrameInfo_getDenoisedGpuFrameDuration(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setDenoisedGpuFrameDuration")
internal external fun FilaRendererFrameInfo_setDenoisedGpuFrameDuration(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getBeginFrame")
internal external fun FilaRendererFrameInfo_getBeginFrame(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setBeginFrame")
internal external fun FilaRendererFrameInfo_setBeginFrame(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getEndFrame")
internal external fun FilaRendererFrameInfo_getEndFrame(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setEndFrame")
internal external fun FilaRendererFrameInfo_setEndFrame(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getBackendBeginFrame")
internal external fun FilaRendererFrameInfo_getBackendBeginFrame(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setBackendBeginFrame")
internal external fun FilaRendererFrameInfo_setBackendBeginFrame(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getBackendEndFrame")
internal external fun FilaRendererFrameInfo_getBackendEndFrame(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setBackendEndFrame")
internal external fun FilaRendererFrameInfo_setBackendEndFrame(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getGpuFrameComplete")
internal external fun FilaRendererFrameInfo_getGpuFrameComplete(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setGpuFrameComplete")
internal external fun FilaRendererFrameInfo_setGpuFrameComplete(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getVsync")
internal external fun FilaRendererFrameInfo_getVsync(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setVsync")
internal external fun FilaRendererFrameInfo_setVsync(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getDisplayPresent")
internal external fun FilaRendererFrameInfo_getDisplayPresent(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setDisplayPresent")
internal external fun FilaRendererFrameInfo_setDisplayPresent(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getPresentDeadline")
internal external fun FilaRendererFrameInfo_getPresentDeadline(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setPresentDeadline")
internal external fun FilaRendererFrameInfo_setPresentDeadline(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getDisplayPresentInterval")
internal external fun FilaRendererFrameInfo_getDisplayPresentInterval(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setDisplayPresentInterval")
internal external fun FilaRendererFrameInfo_setDisplayPresentInterval(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getCompositionToPresentLatency")
internal external fun FilaRendererFrameInfo_getCompositionToPresentLatency(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setCompositionToPresentLatency")
internal external fun FilaRendererFrameInfo_setCompositionToPresentLatency(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getExpectedPresentLatency")
internal external fun FilaRendererFrameInfo_getExpectedPresentLatency(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setExpectedPresentLatency")
internal external fun FilaRendererFrameInfo_setExpectedPresentLatency(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameInfo_getFrameScheduleTime")
internal external fun FilaRendererFrameInfo_getFrameScheduleTime(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererFrameInfo_setFrameScheduleTime")
internal external fun FilaRendererFrameInfo_setFrameScheduleTime(self: NativePointer, value: Long)

@ExternalSymbolName("FilaRendererFrameRateOptions_create")
internal external fun FilaRendererFrameRateOptions_create(): NativePointer

@ExternalSymbolName("FilaRendererFrameRateOptions_destroy")
internal external fun FilaRendererFrameRateOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaRendererFrameRateOptions_getHeadRoomRatio")
internal external fun FilaRendererFrameRateOptions_getHeadRoomRatio(self: NativePointer): Float

@ExternalSymbolName("FilaRendererFrameRateOptions_setHeadRoomRatio")
internal external fun FilaRendererFrameRateOptions_setHeadRoomRatio(self: NativePointer, value: Float)

@ExternalSymbolName("FilaRendererFrameRateOptions_getScaleRate")
internal external fun FilaRendererFrameRateOptions_getScaleRate(self: NativePointer): Float

@ExternalSymbolName("FilaRendererFrameRateOptions_setScaleRate")
internal external fun FilaRendererFrameRateOptions_setScaleRate(self: NativePointer, value: Float)

@ExternalSymbolName("FilaRendererFrameRateOptions_getHistory")
internal external fun FilaRendererFrameRateOptions_getHistory(self: NativePointer): Int

@ExternalSymbolName("FilaRendererFrameRateOptions_setHistory")
internal external fun FilaRendererFrameRateOptions_setHistory(self: NativePointer, value: Int)

@ExternalSymbolName("FilaRendererFrameRateOptions_getInterval")
internal external fun FilaRendererFrameRateOptions_getInterval(self: NativePointer): Int

@ExternalSymbolName("FilaRendererFrameRateOptions_setInterval")
internal external fun FilaRendererFrameRateOptions_setInterval(self: NativePointer, value: Int)

@ExternalSymbolName("FilaRendererClearOptions_create")
internal external fun FilaRendererClearOptions_create(): NativePointer

@ExternalSymbolName("FilaRendererClearOptions_destroy")
internal external fun FilaRendererClearOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaRendererClearOptions_getClearColor")
internal external fun FilaRendererClearOptions_getClearColor(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRendererClearOptions_setClearColor")
internal external fun FilaRendererClearOptions_setClearColor(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaRendererClearOptions_getClearStencil")
internal external fun FilaRendererClearOptions_getClearStencil(self: NativePointer): Int

@ExternalSymbolName("FilaRendererClearOptions_setClearStencil")
internal external fun FilaRendererClearOptions_setClearStencil(self: NativePointer, value: Int)

@ExternalSymbolName("FilaRendererClearOptions_getClear")
internal external fun FilaRendererClearOptions_getClear(self: NativePointer): Boolean

@ExternalSymbolName("FilaRendererClearOptions_setClear")
internal external fun FilaRendererClearOptions_setClear(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaRendererClearOptions_getDiscard")
internal external fun FilaRendererClearOptions_getDiscard(self: NativePointer): Boolean

@ExternalSymbolName("FilaRendererClearOptions_setDiscard")
internal external fun FilaRendererClearOptions_setDiscard(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaRenderer_getFrameInfoHistory")
internal external fun FilaRenderer_getFrameInfoHistory(self: NativePointer, historySize: Int, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaRenderer_getMaxFrameHistorySize")
internal external fun FilaRenderer_getMaxFrameHistorySize(self: NativePointer): Int

@ExternalSymbolName("FilaRenderer_setDisplayInfo")
internal external fun FilaRenderer_setDisplayInfo(self: NativePointer, info: NativePointer)

@ExternalSymbolName("FilaRenderer_setFrameRateOptions")
internal external fun FilaRenderer_setFrameRateOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaRenderer_setClearOptions")
internal external fun FilaRenderer_setClearOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaRenderer_getClearOptions")
internal external fun FilaRenderer_getClearOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRenderer_getEngine")
internal external fun FilaRenderer_getEngine(self: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderer_setVsyncTime")
internal external fun FilaRenderer_setVsyncTime(self: NativePointer, steadyClockTimeNano: Long)

@ExternalSymbolName("FilaRenderer_skipFrame")
internal external fun FilaRenderer_skipFrame(self: NativePointer, vsyncSteadyClockTimeNano: Long)

@ExternalSymbolName("FilaRenderer_shouldRenderFrame")
internal external fun FilaRenderer_shouldRenderFrame(self: NativePointer): Boolean

@ExternalSymbolName("FilaRenderer_beginFrame")
internal external fun FilaRenderer_beginFrame(self: NativePointer, swapChain: NativePointer, vsyncSteadyClockTimeNano: Long): Boolean

@ExternalSymbolName("FilaRenderer_setPresentationTime_int64_t")
internal external fun FilaRenderer_setPresentationTime_int64_t(self: NativePointer, monotonic_clock_ns: Long)

@ExternalSymbolName("FilaRenderer_setPresentationTime_time_point")
internal external fun FilaRenderer_setPresentationTime_time_point(self: NativePointer, monotonic_clock: Long)

@ExternalSymbolName("FilaRenderer_setDesiredPresentationTime_int64_t")
internal external fun FilaRenderer_setDesiredPresentationTime_int64_t(self: NativePointer, monotonic_clock_ns: Long)

@ExternalSymbolName("FilaRenderer_setDesiredPresentationTime_time_point")
internal external fun FilaRenderer_setDesiredPresentationTime_time_point(self: NativePointer, monotonic_clock: Long)

@ExternalSymbolName("FilaRenderer_setRenderingDeadline_int64_t")
internal external fun FilaRenderer_setRenderingDeadline_int64_t(self: NativePointer, monotonic_clock_ns: Long)

@ExternalSymbolName("FilaRenderer_setRenderingDeadline_time_point")
internal external fun FilaRenderer_setRenderingDeadline_time_point(self: NativePointer, monotonic_clock: Long)

@ExternalSymbolName("FilaRenderer_render")
internal external fun FilaRenderer_render(self: NativePointer, view: NativePointer)

@ExternalSymbolName("FilaRenderer_copyFrame")
internal external fun FilaRenderer_copyFrame(self: NativePointer, dstSwapChain: NativePointer, dstViewport: NativePointer, srcViewport: NativePointer, flags: Int)

@ExternalSymbolName("FilaRenderer_readPixels_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor")
internal external fun FilaRenderer_readPixels_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor(self: NativePointer, xoffset: Int, yoffset: Int, width: Int, height: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaRenderer_readPixels_RenderTarget_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor")
internal external fun FilaRenderer_readPixels_RenderTarget_uint32_t_uint32_t_uint32_t_uint32_t_PixelBufferDescriptor(self: NativePointer, renderTarget: NativePointer, xoffset: Int, yoffset: Int, width: Int, height: Int, buffer: NativePointer, bufferSize: Int, bufferFormat: Int, bufferType: Int, bufferAlignment: Int, bufferLeft: Int, bufferTop: Int, bufferStride: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaRenderer_endFrame")
internal external fun FilaRenderer_endFrame(self: NativePointer)

@ExternalSymbolName("FilaRenderer_renderStandaloneView")
internal external fun FilaRenderer_renderStandaloneView(self: NativePointer, view: NativePointer)

@ExternalSymbolName("FilaRenderer_getMaterialTime")
internal external fun FilaRenderer_getMaterialTime(self: NativePointer): Double

@ExternalSymbolName("FilaRenderer_getUserTime")
internal external fun FilaRenderer_getUserTime(self: NativePointer): Double

@ExternalSymbolName("FilaRenderer_setMaterialTimeEpoch_int64_t")
internal external fun FilaRenderer_setMaterialTimeEpoch_int64_t(self: NativePointer, monotonic_clock_ns: Long)

@ExternalSymbolName("FilaRenderer_setMaterialTimeEpoch_time_point")
internal external fun FilaRenderer_setMaterialTimeEpoch_time_point(self: NativePointer, monotonic_clock: Long)

@ExternalSymbolName("FilaRenderer_resetUserTime")
internal external fun FilaRenderer_resetUserTime(self: NativePointer)

@ExternalSymbolName("FilaRenderer_skipNextFrames")
internal external fun FilaRenderer_skipNextFrames(self: NativePointer, frameCount: Int)

@ExternalSymbolName("FilaRenderer_getFrameToSkipCount")
internal external fun FilaRenderer_getFrameToSkipCount(self: NativePointer): Int

@ExternalSymbolName("FilaRenderer_hasGpuFallenBehind")
internal external fun FilaRenderer_hasGpuFallenBehind(self: NativePointer): Boolean

@ExternalSymbolName("FilaRenderer_setFrameScheduleTime_time_point")
internal external fun FilaRenderer_setFrameScheduleTime_time_point(self: NativePointer, time: Long)

@ExternalSymbolName("FilaRenderer_setFrameScheduleTime_uint64_t")
internal external fun FilaRenderer_setFrameScheduleTime_uint64_t(self: NativePointer, timeSteadyClockNano: Long)

@ExternalSymbolName("FilaRenderer_pauseRenderThread")
internal external fun FilaRenderer_pauseRenderThread(self: NativePointer, duration_ns: Long)
