// Generated by generateKotlinExternals from c/filament/generated/FilaSkybox.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_create")
internal external fun FilaSkyboxBuilder_create(): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_destroy")
internal external fun FilaSkyboxBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaSkyboxBuilder_environment")
internal external fun FilaSkyboxBuilder_environment(self: NativePointer, cubemap: NativePointer): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_showSun")
internal external fun FilaSkyboxBuilder_showSun(self: NativePointer, show: Boolean): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_intensity")
internal external fun FilaSkyboxBuilder_intensity(self: NativePointer, envIntensity: Float): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_color")
internal external fun FilaSkyboxBuilder_color(self: NativePointer, color: NativePointer): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_priority")
internal external fun FilaSkyboxBuilder_priority(self: NativePointer, priority: Int): NativePointer

@ExternalSymbolName("FilaSkyboxBuilder_build")
internal external fun FilaSkyboxBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaSkybox_setColor")
internal external fun FilaSkybox_setColor(self: NativePointer, color: NativePointer)

@ExternalSymbolName("FilaSkybox_setLayerMask")
internal external fun FilaSkybox_setLayerMask(self: NativePointer, select: Int, values: Int)

@ExternalSymbolName("FilaSkybox_getLayerMask")
internal external fun FilaSkybox_getLayerMask(self: NativePointer): Int

@ExternalSymbolName("FilaSkybox_getIntensity")
internal external fun FilaSkybox_getIntensity(self: NativePointer): Float

@ExternalSymbolName("FilaSkybox_getTexture")
internal external fun FilaSkybox_getTexture(self: NativePointer): NativePointer
