// Generated by generateKotlinExternals from c/filament/generated/FilaFramePacer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFramePacerHardwareTimeline_create")
internal external fun FilaFramePacerHardwareTimeline_create(): NativePointer

@ExternalSymbolName("FilaFramePacerHardwareTimeline_destroy")
internal external fun FilaFramePacerHardwareTimeline_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePacerHardwareTimeline_getExpectedPresentationTime")
internal external fun FilaFramePacerHardwareTimeline_getExpectedPresentationTime(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerHardwareTimeline_setExpectedPresentationTime")
internal external fun FilaFramePacerHardwareTimeline_setExpectedPresentationTime(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerHardwareTimeline_getDeadline")
internal external fun FilaFramePacerHardwareTimeline_getDeadline(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerHardwareTimeline_setDeadline")
internal external fun FilaFramePacerHardwareTimeline_setDeadline(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerVsyncTick_create")
internal external fun FilaFramePacerVsyncTick_create(): NativePointer

@ExternalSymbolName("FilaFramePacerVsyncTick_destroy")
internal external fun FilaFramePacerVsyncTick_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePacerVsyncTick_getBaseTime")
internal external fun FilaFramePacerVsyncTick_getBaseTime(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerVsyncTick_setBaseTime")
internal external fun FilaFramePacerVsyncTick_setBaseTime(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerVsyncTick_getVsyncPeriod")
internal external fun FilaFramePacerVsyncTick_getVsyncPeriod(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerVsyncTick_setVsyncPeriod")
internal external fun FilaFramePacerVsyncTick_setVsyncPeriod(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerVsyncTick_getFrameScheduleTime")
internal external fun FilaFramePacerVsyncTick_getFrameScheduleTime(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerVsyncTick_setFrameScheduleTime")
internal external fun FilaFramePacerVsyncTick_setFrameScheduleTime(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerVsyncTick_getTimelines")
internal external fun FilaFramePacerVsyncTick_getTimelines(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaFramePacerConfiguration_create")
internal external fun FilaFramePacerConfiguration_create(): NativePointer

@ExternalSymbolName("FilaFramePacerConfiguration_destroy")
internal external fun FilaFramePacerConfiguration_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePacerConfiguration_getTargetFrameRate")
internal external fun FilaFramePacerConfiguration_getTargetFrameRate(self: NativePointer): Float

@ExternalSymbolName("FilaFramePacerConfiguration_setTargetFrameRate")
internal external fun FilaFramePacerConfiguration_setTargetFrameRate(self: NativePointer, value: Float)

@ExternalSymbolName("FilaFramePacerConfiguration_getLatency")
internal external fun FilaFramePacerConfiguration_getLatency(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacerConfiguration_setLatency")
internal external fun FilaFramePacerConfiguration_setLatency(self: NativePointer, value: Long)

@ExternalSymbolName("FilaFramePacerBuilder_create")
internal external fun FilaFramePacerBuilder_create(): NativePointer

@ExternalSymbolName("FilaFramePacerBuilder_destroy")
internal external fun FilaFramePacerBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaFramePacerBuilder_targetFrameRate")
internal external fun FilaFramePacerBuilder_targetFrameRate(self: NativePointer, fps: Float): NativePointer

@ExternalSymbolName("FilaFramePacerBuilder_latency")
internal external fun FilaFramePacerBuilder_latency(self: NativePointer, latency: Long): NativePointer

@ExternalSymbolName("FilaFramePacerBuilder_latencyFrames")
internal external fun FilaFramePacerBuilder_latencyFrames(self: NativePointer, frames: Int): NativePointer

@ExternalSymbolName("FilaFramePacerBuilder_build")
internal external fun FilaFramePacerBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaFramePacer_configure")
internal external fun FilaFramePacer_configure(self: NativePointer, config: NativePointer)

@ExternalSymbolName("FilaFramePacer_getConfiguration")
internal external fun FilaFramePacer_getConfiguration(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacer_setupFrame")
internal external fun FilaFramePacer_setupFrame(self: NativePointer, tick: NativePointer): Int

@ExternalSymbolName("FilaFramePacer_setupExtraFrame")
internal external fun FilaFramePacer_setupExtraFrame(self: NativePointer): Boolean

@ExternalSymbolName("FilaFramePacer_hasGpuFallenBehind")
internal external fun FilaFramePacer_hasGpuFallenBehind(self: NativePointer, renderer: NativePointer): Boolean

@ExternalSymbolName("FilaFramePacer_applyPresentationTime")
internal external fun FilaFramePacer_applyPresentationTime(self: NativePointer, renderer: NativePointer)

@ExternalSymbolName("FilaFramePacer_getExpectedPresentationTime")
internal external fun FilaFramePacer_getExpectedPresentationTime(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacer_getRenderingDeadline")
internal external fun FilaFramePacer_getRenderingDeadline(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacer_getEffectiveLatency")
internal external fun FilaFramePacer_getEffectiveLatency(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaFramePacer_getPacingStatus")
internal external fun FilaFramePacer_getPacingStatus(self: NativePointer): Int

@ExternalSymbolName("FilaFramePacer_resetPacing")
internal external fun FilaFramePacer_resetPacing(self: NativePointer)

@ExternalSymbolName("FilaFramePacer_getSelectedFrameRate")
internal external fun FilaFramePacer_getSelectedFrameRate(self: NativePointer): Float

@ExternalSymbolName("FilaFramePacer_isExactFrameRateAchieved")
internal external fun FilaFramePacer_isExactFrameRateAchieved(self: NativePointer): Boolean
