// Generated by generateKotlinExternals from c/filament/generated/FilaEngine.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaEngineConfig_create")
internal external fun FilaEngineConfig_create(): NativePointer

@ExternalSymbolName("FilaEngineConfig_destroy")
internal external fun FilaEngineConfig_destroy(self: NativePointer)

@ExternalSymbolName("FilaEngineConfig_getCommandBufferSizeMB")
internal external fun FilaEngineConfig_getCommandBufferSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setCommandBufferSizeMB")
internal external fun FilaEngineConfig_setCommandBufferSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getPerRenderPassArenaSizeMB")
internal external fun FilaEngineConfig_getPerRenderPassArenaSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setPerRenderPassArenaSizeMB")
internal external fun FilaEngineConfig_setPerRenderPassArenaSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getDriverHandleArenaSizeMB")
internal external fun FilaEngineConfig_getDriverHandleArenaSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setDriverHandleArenaSizeMB")
internal external fun FilaEngineConfig_setDriverHandleArenaSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getMinCommandBufferSizeMB")
internal external fun FilaEngineConfig_getMinCommandBufferSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setMinCommandBufferSizeMB")
internal external fun FilaEngineConfig_setMinCommandBufferSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getPerFrameCommandsSizeMB")
internal external fun FilaEngineConfig_getPerFrameCommandsSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setPerFrameCommandsSizeMB")
internal external fun FilaEngineConfig_setPerFrameCommandsSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getJobSystemThreadCount")
internal external fun FilaEngineConfig_getJobSystemThreadCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setJobSystemThreadCount")
internal external fun FilaEngineConfig_setJobSystemThreadCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getMetalUploadBufferSizeBytes")
internal external fun FilaEngineConfig_getMetalUploadBufferSizeBytes(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setMetalUploadBufferSizeBytes")
internal external fun FilaEngineConfig_setMetalUploadBufferSizeBytes(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getMetalDisablePanicOnDrawableFailure")
internal external fun FilaEngineConfig_getMetalDisablePanicOnDrawableFailure(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setMetalDisablePanicOnDrawableFailure")
internal external fun FilaEngineConfig_setMetalDisablePanicOnDrawableFailure(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineConfig_getDisableParallelShaderCompile")
internal external fun FilaEngineConfig_getDisableParallelShaderCompile(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setDisableParallelShaderCompile")
internal external fun FilaEngineConfig_setDisableParallelShaderCompile(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineConfig_getStereoscopicType")
internal external fun FilaEngineConfig_getStereoscopicType(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setStereoscopicType")
internal external fun FilaEngineConfig_setStereoscopicType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getStereoscopicEyeCount")
internal external fun FilaEngineConfig_getStereoscopicEyeCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setStereoscopicEyeCount")
internal external fun FilaEngineConfig_setStereoscopicEyeCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getResourceAllocatorCacheSizeMB")
internal external fun FilaEngineConfig_getResourceAllocatorCacheSizeMB(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setResourceAllocatorCacheSizeMB")
internal external fun FilaEngineConfig_setResourceAllocatorCacheSizeMB(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getResourceAllocatorCacheMaxAge")
internal external fun FilaEngineConfig_getResourceAllocatorCacheMaxAge(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setResourceAllocatorCacheMaxAge")
internal external fun FilaEngineConfig_setResourceAllocatorCacheMaxAge(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getDisableHandleUseAfterFreeCheck")
internal external fun FilaEngineConfig_getDisableHandleUseAfterFreeCheck(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setDisableHandleUseAfterFreeCheck")
internal external fun FilaEngineConfig_setDisableHandleUseAfterFreeCheck(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineConfig_getPreferredShaderLanguage")
internal external fun FilaEngineConfig_getPreferredShaderLanguage(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setPreferredShaderLanguage")
internal external fun FilaEngineConfig_setPreferredShaderLanguage(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getForceGLES2Context")
internal external fun FilaEngineConfig_getForceGLES2Context(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setForceGLES2Context")
internal external fun FilaEngineConfig_setForceGLES2Context(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineConfig_getAssertNativeWindowIsValid")
internal external fun FilaEngineConfig_getAssertNativeWindowIsValid(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setAssertNativeWindowIsValid")
internal external fun FilaEngineConfig_setAssertNativeWindowIsValid(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineConfig_getGpuContextPriority")
internal external fun FilaEngineConfig_getGpuContextPriority(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setGpuContextPriority")
internal external fun FilaEngineConfig_setGpuContextPriority(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getSharedUboInitialSizeInBytes")
internal external fun FilaEngineConfig_getSharedUboInitialSizeInBytes(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setSharedUboInitialSizeInBytes")
internal external fun FilaEngineConfig_setSharedUboInitialSizeInBytes(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getAsynchronousMode")
internal external fun FilaEngineConfig_getAsynchronousMode(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setAsynchronousMode")
internal external fun FilaEngineConfig_setAsynchronousMode(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getMaterialCacheCapacity")
internal external fun FilaEngineConfig_getMaterialCacheCapacity(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setMaterialCacheCapacity")
internal external fun FilaEngineConfig_setMaterialCacheCapacity(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getProgramCacheCapacity")
internal external fun FilaEngineConfig_getProgramCacheCapacity(self: NativePointer): Int

@ExternalSymbolName("FilaEngineConfig_setProgramCacheCapacity")
internal external fun FilaEngineConfig_setProgramCacheCapacity(self: NativePointer, value: Int)

@ExternalSymbolName("FilaEngineConfig_getEnableMultipleDirectionalLights")
internal external fun FilaEngineConfig_getEnableMultipleDirectionalLights(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineConfig_setEnableMultipleDirectionalLights")
internal external fun FilaEngineConfig_setEnableMultipleDirectionalLights(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineFeatureFlag_create")
internal external fun FilaEngineFeatureFlag_create(): NativePointer

@ExternalSymbolName("FilaEngineFeatureFlag_destroy")
internal external fun FilaEngineFeatureFlag_destroy(self: NativePointer)

@ExternalSymbolName("FilaEngineFeatureFlag_getName")
internal external fun FilaEngineFeatureFlag_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineFeatureFlag_getDescription")
internal external fun FilaEngineFeatureFlag_getDescription(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineFeatureFlag_getValue")
internal external fun FilaEngineFeatureFlag_getValue(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineFeatureFlag_getConstant")
internal external fun FilaEngineFeatureFlag_getConstant(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngineFeatureFlag_setConstant")
internal external fun FilaEngineFeatureFlag_setConstant(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaEngineBuilder_create")
internal external fun FilaEngineBuilder_create(): NativePointer

@ExternalSymbolName("FilaEngineBuilder_destroy")
internal external fun FilaEngineBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaEngineBuilder_backend")
internal external fun FilaEngineBuilder_backend(self: NativePointer, backend: Int): NativePointer

@ExternalSymbolName("FilaEngineBuilder_platform")
internal external fun FilaEngineBuilder_platform(self: NativePointer, platform: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineBuilder_config")
internal external fun FilaEngineBuilder_config(self: NativePointer, config: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineBuilder_sharedContext")
internal external fun FilaEngineBuilder_sharedContext(self: NativePointer, sharedContext: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineBuilder_featureLevel")
internal external fun FilaEngineBuilder_featureLevel(self: NativePointer, featureLevel: Int): NativePointer

@ExternalSymbolName("FilaEngineBuilder_paused")
internal external fun FilaEngineBuilder_paused(self: NativePointer, paused: Boolean): NativePointer

@ExternalSymbolName("FilaEngineBuilder_feature")
internal external fun FilaEngineBuilder_feature(self: NativePointer, name: NativePointer, value: Boolean): NativePointer

@ExternalSymbolName("FilaEngineBuilder_colorGrading")
internal external fun FilaEngineBuilder_colorGrading(self: NativePointer, colorGrading: NativePointer): NativePointer

@ExternalSymbolName("FilaEngineBuilder_build_Invocable")
internal external fun FilaEngineBuilder_build_Invocable(self: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaEngineBuilder_build")
internal external fun FilaEngineBuilder_build(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_getFeatureFlags")
internal external fun FilaEngine_getFeatureFlags(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaEngine_create")
internal external fun FilaEngine_create(backend: Int, platform: NativePointer, sharedContext: NativePointer, config: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_createAsync")
internal external fun FilaEngine_createAsync(callback: NativePointer, user: NativePointer, backend: Int, platform: NativePointer, sharedContext: NativePointer, config: NativePointer)

@ExternalSymbolName("FilaEngine_getEngine")
internal external fun FilaEngine_getEngine(token: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_destroy_EnginePtr")
internal external fun FilaEngine_destroy_EnginePtr(engine: NativePointer)

@ExternalSymbolName("FilaEngine_destroy_Engine")
internal external fun FilaEngine_destroy_Engine(engine: NativePointer)

@ExternalSymbolName("FilaEngine_destroy_BufferObject")
internal external fun FilaEngine_destroy_BufferObject(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_VertexBuffer")
internal external fun FilaEngine_destroy_VertexBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Fence")
internal external fun FilaEngine_destroy_Fence(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_IndexBuffer")
internal external fun FilaEngine_destroy_IndexBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_SkinningBuffer")
internal external fun FilaEngine_destroy_SkinningBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_MorphTargetBuffer")
internal external fun FilaEngine_destroy_MorphTargetBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_IndirectLight")
internal external fun FilaEngine_destroy_IndirectLight(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Material")
internal external fun FilaEngine_destroy_Material(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_MaterialInstance")
internal external fun FilaEngine_destroy_MaterialInstance(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Renderer")
internal external fun FilaEngine_destroy_Renderer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_FramePacer")
internal external fun FilaEngine_destroy_FramePacer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Scene")
internal external fun FilaEngine_destroy_Scene(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Skybox")
internal external fun FilaEngine_destroy_Skybox(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_ColorGrading")
internal external fun FilaEngine_destroy_ColorGrading(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_SwapChain")
internal external fun FilaEngine_destroy_SwapChain(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Stream")
internal external fun FilaEngine_destroy_Stream(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Texture")
internal external fun FilaEngine_destroy_Texture(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_RenderTarget")
internal external fun FilaEngine_destroy_RenderTarget(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_View")
internal external fun FilaEngine_destroy_View(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_InstanceBuffer")
internal external fun FilaEngine_destroy_InstanceBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_destroy_Entity")
internal external fun FilaEngine_destroy_Entity(self: NativePointer, e: Int)

@ExternalSymbolName("FilaEngine_getSupportedFeatureLevel")
internal external fun FilaEngine_getSupportedFeatureLevel(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_setActiveFeatureLevel")
internal external fun FilaEngine_setActiveFeatureLevel(self: NativePointer, featureLevel: Int): Int

@ExternalSymbolName("FilaEngine_getActiveFeatureLevel")
internal external fun FilaEngine_getActiveFeatureLevel(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getMaxAutomaticInstances")
internal external fun FilaEngine_getMaxAutomaticInstances(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_isStereoSupported")
internal external fun FilaEngine_isStereoSupported(self: NativePointer, stereoscopicType: Int): Boolean

@ExternalSymbolName("FilaEngine_isAsynchronousModeEnabled")
internal external fun FilaEngine_isAsynchronousModeEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_hasUnrecoverableFailure")
internal external fun FilaEngine_hasUnrecoverableFailure(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_getConfig")
internal external fun FilaEngine_getConfig(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaEngine_getMaxStereoscopicEyes")
internal external fun FilaEngine_getMaxStereoscopicEyes(): Int

@ExternalSymbolName("FilaEngine_getEntityManager")
internal external fun FilaEngine_getEntityManager(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_getRenderableManager")
internal external fun FilaEngine_getRenderableManager(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_getLightManager")
internal external fun FilaEngine_getLightManager(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_getTransformManager")
internal external fun FilaEngine_getTransformManager(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_enableAccurateTranslations")
internal external fun FilaEngine_enableAccurateTranslations(self: NativePointer)

@ExternalSymbolName("FilaEngine_setAutomaticInstancingEnabled")
internal external fun FilaEngine_setAutomaticInstancingEnabled(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaEngine_isAutomaticInstancingEnabled")
internal external fun FilaEngine_isAutomaticInstancingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_createSwapChain_void_uint64_t")
internal external fun FilaEngine_createSwapChain_void_uint64_t(self: NativePointer, nativeWindow: NativePointer, flags: Long): NativePointer

@ExternalSymbolName("FilaEngine_createSwapChain_uint32_t_uint32_t_uint64_t")
internal external fun FilaEngine_createSwapChain_uint32_t_uint32_t_uint64_t(self: NativePointer, width: Int, height: Int, flags: Long): NativePointer

@ExternalSymbolName("FilaEngine_createRenderer")
internal external fun FilaEngine_createRenderer(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_createView")
internal external fun FilaEngine_createView(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_createScene")
internal external fun FilaEngine_createScene(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_createCamera")
internal external fun FilaEngine_createCamera(self: NativePointer, entity: Int): NativePointer

@ExternalSymbolName("FilaEngine_getCameraComponent")
internal external fun FilaEngine_getCameraComponent(self: NativePointer, entity: Int): NativePointer

@ExternalSymbolName("FilaEngine_destroyCameraComponent")
internal external fun FilaEngine_destroyCameraComponent(self: NativePointer, entity: Int)

@ExternalSymbolName("FilaEngine_createFence")
internal external fun FilaEngine_createFence(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_isValid_BufferObject")
internal external fun FilaEngine_isValid_BufferObject(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_VertexBuffer")
internal external fun FilaEngine_isValid_VertexBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Fence")
internal external fun FilaEngine_isValid_Fence(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_IndexBuffer")
internal external fun FilaEngine_isValid_IndexBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_SkinningBuffer")
internal external fun FilaEngine_isValid_SkinningBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_MorphTargetBuffer")
internal external fun FilaEngine_isValid_MorphTargetBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_IndirectLight")
internal external fun FilaEngine_isValid_IndirectLight(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Material")
internal external fun FilaEngine_isValid_Material(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Material_MaterialInstance")
internal external fun FilaEngine_isValid_Material_MaterialInstance(self: NativePointer, m: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Renderer")
internal external fun FilaEngine_isValid_Renderer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Scene")
internal external fun FilaEngine_isValid_Scene(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Skybox")
internal external fun FilaEngine_isValid_Skybox(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_ColorGrading")
internal external fun FilaEngine_isValid_ColorGrading(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_SwapChain")
internal external fun FilaEngine_isValid_SwapChain(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Stream")
internal external fun FilaEngine_isValid_Stream(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_Texture")
internal external fun FilaEngine_isValid_Texture(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_RenderTarget")
internal external fun FilaEngine_isValid_RenderTarget(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_View")
internal external fun FilaEngine_isValid_View(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValid_InstanceBuffer")
internal external fun FilaEngine_isValid_InstanceBuffer(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_isValidExpensive")
internal external fun FilaEngine_isValidExpensive(self: NativePointer, p: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_getBufferObjectCount")
internal external fun FilaEngine_getBufferObjectCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getViewCount")
internal external fun FilaEngine_getViewCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getSceneCount")
internal external fun FilaEngine_getSceneCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getSwapChainCount")
internal external fun FilaEngine_getSwapChainCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getStreamCount")
internal external fun FilaEngine_getStreamCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getIndexBufferCount")
internal external fun FilaEngine_getIndexBufferCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getSkinningBufferCount")
internal external fun FilaEngine_getSkinningBufferCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getMorphTargetBufferCount")
internal external fun FilaEngine_getMorphTargetBufferCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getInstanceBufferCount")
internal external fun FilaEngine_getInstanceBufferCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getVertexBufferCount")
internal external fun FilaEngine_getVertexBufferCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getIndirectLightCount")
internal external fun FilaEngine_getIndirectLightCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getMaterialCount")
internal external fun FilaEngine_getMaterialCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getTextureCount")
internal external fun FilaEngine_getTextureCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getSkyboxeCount")
internal external fun FilaEngine_getSkyboxeCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getColorGradingCount")
internal external fun FilaEngine_getColorGradingCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_getRenderTargetCount")
internal external fun FilaEngine_getRenderTargetCount(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_runCommandAsync")
internal external fun FilaEngine_runCommandAsync(self: NativePointer, command: NativePointer, commandUser: NativePointer, handler: NativePointer, onComplete: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaEngine_cancelAsyncCall")
internal external fun FilaEngine_cancelAsyncCall(self: NativePointer, id: Int): Boolean

@ExternalSymbolName("FilaEngine_flushAndWait")
internal external fun FilaEngine_flushAndWait(self: NativePointer)

@ExternalSymbolName("FilaEngine_flushAndWait_uint64_t")
internal external fun FilaEngine_flushAndWait_uint64_t(self: NativePointer, timeout: Long): Boolean

@ExternalSymbolName("FilaEngine_flush")
internal external fun FilaEngine_flush(self: NativePointer)

@ExternalSymbolName("FilaEngine_isPaused")
internal external fun FilaEngine_isPaused(self: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_setPaused")
internal external fun FilaEngine_setPaused(self: NativePointer, paused: Boolean)

@ExternalSymbolName("FilaEngine_pumpMessageQueues")
internal external fun FilaEngine_pumpMessageQueues(self: NativePointer)

@ExternalSymbolName("FilaEngine_unprotected")
internal external fun FilaEngine_unprotected(self: NativePointer)

@ExternalSymbolName("FilaEngine_getDefaultMaterial")
internal external fun FilaEngine_getDefaultMaterial(self: NativePointer): NativePointer

@ExternalSymbolName("FilaEngine_getBackend")
internal external fun FilaEngine_getBackend(self: NativePointer): Int

@ExternalSymbolName("FilaEngine_execute")
internal external fun FilaEngine_execute(self: NativePointer)

@ExternalSymbolName("FilaEngine_getSteadyClockTimeNano")
internal external fun FilaEngine_getSteadyClockTimeNano(out: NativePointer)

@ExternalSymbolName("FilaEngine_hasFeatureFlag")
internal external fun FilaEngine_hasFeatureFlag(self: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_setFeatureFlag")
internal external fun FilaEngine_setFeatureFlag(self: NativePointer, name: NativePointer, value: Boolean): Boolean

@ExternalSymbolName("FilaEngine_getFeatureFlag")
internal external fun FilaEngine_getFeatureFlag(self: NativePointer, name: NativePointer, out: NativePointer): Boolean

@ExternalSymbolName("FilaEngine_compile")
internal external fun FilaEngine_compile(self: NativePointer, priority: Int, material: NativePointer, view: NativePointer, shadowReceiver: Int, skinning: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)
