// Generated by generateKotlinExternals from c/filament/generated/FilaDisplayRangeToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaDisplayRangeToneMapper_create")
internal external fun FilaDisplayRangeToneMapper_create(): NativePointer

@ExternalSymbolName("FilaDisplayRangeToneMapper_destroy")
internal external fun FilaDisplayRangeToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaDisplayRangeToneMapper_asToneMapper")
internal external fun FilaDisplayRangeToneMapper_asToneMapper(self: NativePointer): NativePointer
