// Generated by generateKotlinExternals from c/filament/generated/FilaSwapChain.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaSwapChain_isProtectedContentSupported")
internal external fun FilaSwapChain_isProtectedContentSupported(engine: NativePointer): Boolean

@ExternalSymbolName("FilaSwapChain_isSRGBSwapChainSupported")
internal external fun FilaSwapChain_isSRGBSwapChainSupported(engine: NativePointer): Boolean

@ExternalSymbolName("FilaSwapChain_isMSAASwapChainSupported")
internal external fun FilaSwapChain_isMSAASwapChainSupported(engine: NativePointer, samples: Int): Boolean

@ExternalSymbolName("FilaSwapChain_isFrameRateChangeSupported")
internal external fun FilaSwapChain_isFrameRateChangeSupported(self: NativePointer): Int

@ExternalSymbolName("FilaSwapChain_setFrameRate")
internal external fun FilaSwapChain_setFrameRate(self: NativePointer, frameRate: Float, compatibility: Int, strategy: Int)

@ExternalSymbolName("FilaSwapChain_getNativeWindow")
internal external fun FilaSwapChain_getNativeWindow(self: NativePointer): NativePointer

@ExternalSymbolName("FilaSwapChain_isFrameScheduledCallbackSet")
internal external fun FilaSwapChain_isFrameScheduledCallbackSet(self: NativePointer): Boolean

@ExternalSymbolName("FilaSwapChain_setFrameCompletedCallback")
internal external fun FilaSwapChain_setFrameCompletedCallback(self: NativePointer, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)
