// Generated by generateKotlinExternals from c/filament/generated/FilaIndirectLight.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_create")
internal external fun FilaIndirectLightBuilder_create(): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_destroy")
internal external fun FilaIndirectLightBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaIndirectLightBuilder_reflections")
internal external fun FilaIndirectLightBuilder_reflections(self: NativePointer, cubemap: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_irradiance_uint8_t_float3")
internal external fun FilaIndirectLightBuilder_irradiance_uint8_t_float3(self: NativePointer, bands: Int, sh: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_irradiance_Texture")
internal external fun FilaIndirectLightBuilder_irradiance_Texture(self: NativePointer, cubemap: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_radiance")
internal external fun FilaIndirectLightBuilder_radiance(self: NativePointer, bands: Int, sh: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_intensity")
internal external fun FilaIndirectLightBuilder_intensity(self: NativePointer, envIntensity: Float): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_rotation")
internal external fun FilaIndirectLightBuilder_rotation(self: NativePointer, rotation: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLightBuilder_build")
internal external fun FilaIndirectLightBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLight_setIntensity")
internal external fun FilaIndirectLight_setIntensity(self: NativePointer, intensity: Float)

@ExternalSymbolName("FilaIndirectLight_getIntensity")
internal external fun FilaIndirectLight_getIntensity(self: NativePointer): Float

@ExternalSymbolName("FilaIndirectLight_setRotation")
internal external fun FilaIndirectLight_setRotation(self: NativePointer, rotation: NativePointer)

@ExternalSymbolName("FilaIndirectLight_getRotation")
internal external fun FilaIndirectLight_getRotation(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaIndirectLight_getReflectionsTexture")
internal external fun FilaIndirectLight_getReflectionsTexture(self: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLight_getIrradianceTexture")
internal external fun FilaIndirectLight_getIrradianceTexture(self: NativePointer): NativePointer

@ExternalSymbolName("FilaIndirectLight_getDirectionEstimate_float3")
internal external fun FilaIndirectLight_getDirectionEstimate_float3(sh: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaIndirectLight_getDirectionEstimate")
internal external fun FilaIndirectLight_getDirectionEstimate(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaIndirectLight_getColorEstimate_float3")
internal external fun FilaIndirectLight_getColorEstimate_float3(sh: NativePointer, direction: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaIndirectLight_getColorEstimate")
internal external fun FilaIndirectLight_getColorEstimate(self: NativePointer, direction: NativePointer, out: NativePointer)
