// Generated by generateKotlinExternals from c/filament/generated/FilaColorPrimaries.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColorPrimaries_create")
internal external fun FilaColorPrimaries_create(): NativePointer

@ExternalSymbolName("FilaColorPrimaries_destroy")
internal external fun FilaColorPrimaries_destroy(self: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_getR")
internal external fun FilaColorPrimaries_getR(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_setR")
internal external fun FilaColorPrimaries_setR(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_getG")
internal external fun FilaColorPrimaries_getG(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_setG")
internal external fun FilaColorPrimaries_setG(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_getB")
internal external fun FilaColorPrimaries_getB(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColorPrimaries_setB")
internal external fun FilaColorPrimaries_setB(self: NativePointer, value: NativePointer)
