// Generated by generateKotlinExternals from c/filament/generated/FilaFence.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFence_wait")
internal external fun FilaFence_wait(self: NativePointer, mode: Int, timeout: Long): Int

@ExternalSymbolName("FilaFence_waitAndDestroy")
internal external fun FilaFence_waitAndDestroy(fence: NativePointer, mode: Int): Int
