// Generated by generateKotlinExternals from c/filament/generated/FilaGeometrySurfaceOrientation.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_create")
internal external fun FilaGeometrySurfaceOrientationBuilder_create(): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_destroy")
internal external fun FilaGeometrySurfaceOrientationBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_vertexCount")
internal external fun FilaGeometrySurfaceOrientationBuilder_vertexCount(self: NativePointer, vertexCount: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_normals")
internal external fun FilaGeometrySurfaceOrientationBuilder_normals(self: NativePointer, arg0: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_tangents")
internal external fun FilaGeometrySurfaceOrientationBuilder_tangents(self: NativePointer, arg0: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_uvs")
internal external fun FilaGeometrySurfaceOrientationBuilder_uvs(self: NativePointer, arg0: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_positions")
internal external fun FilaGeometrySurfaceOrientationBuilder_positions(self: NativePointer, arg0: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_triangleCount")
internal external fun FilaGeometrySurfaceOrientationBuilder_triangleCount(self: NativePointer, triangleCount: Int): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_triangles_uint3")
internal external fun FilaGeometrySurfaceOrientationBuilder_triangles_uint3(self: NativePointer, arg0: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_triangles_ushort3")
internal external fun FilaGeometrySurfaceOrientationBuilder_triangles_ushort3(self: NativePointer, arg0: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientationBuilder_build")
internal external fun FilaGeometrySurfaceOrientationBuilder_build(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometrySurfaceOrientation_destroy")
internal external fun FilaGeometrySurfaceOrientation_destroy(self: NativePointer)

@ExternalSymbolName("FilaGeometrySurfaceOrientation_getVertexCount")
internal external fun FilaGeometrySurfaceOrientation_getVertexCount(self: NativePointer): Int

@ExternalSymbolName("FilaGeometrySurfaceOrientation_getQuats_quatf_size_t_size_t")
internal external fun FilaGeometrySurfaceOrientation_getQuats_quatf_size_t_size_t(self: NativePointer, out_: NativePointer, quatCount: Int, stride: Int)

@ExternalSymbolName("FilaGeometrySurfaceOrientation_getQuats_short4_size_t_size_t")
internal external fun FilaGeometrySurfaceOrientation_getQuats_short4_size_t_size_t(self: NativePointer, out_: NativePointer, quatCount: Int, stride: Int)

@ExternalSymbolName("FilaGeometrySurfaceOrientation_getQuats_quath_size_t_size_t")
internal external fun FilaGeometrySurfaceOrientation_getQuats_quath_size_t_size_t(self: NativePointer, out_: NativePointer, quatCount: Int, stride: Int)
