// Generated by generateKotlinExternals from c/filament/generated/FilaBloomOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaBloomOptions_create")
internal external fun FilaBloomOptions_create(): NativePointer

@ExternalSymbolName("FilaBloomOptions_destroy")
internal external fun FilaBloomOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaBloomOptions_getDirt")
internal external fun FilaBloomOptions_getDirt(self: NativePointer): NativePointer

@ExternalSymbolName("FilaBloomOptions_setDirt")
internal external fun FilaBloomOptions_setDirt(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaBloomOptions_getDirtStrength")
internal external fun FilaBloomOptions_getDirtStrength(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setDirtStrength")
internal external fun FilaBloomOptions_setDirtStrength(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getStrength")
internal external fun FilaBloomOptions_getStrength(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setStrength")
internal external fun FilaBloomOptions_setStrength(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getResolution")
internal external fun FilaBloomOptions_getResolution(self: NativePointer): Int

@ExternalSymbolName("FilaBloomOptions_setResolution")
internal external fun FilaBloomOptions_setResolution(self: NativePointer, value: Int)

@ExternalSymbolName("FilaBloomOptions_getLevels")
internal external fun FilaBloomOptions_getLevels(self: NativePointer): Int

@ExternalSymbolName("FilaBloomOptions_setLevels")
internal external fun FilaBloomOptions_setLevels(self: NativePointer, value: Int)

@ExternalSymbolName("FilaBloomOptions_getBlendMode")
internal external fun FilaBloomOptions_getBlendMode(self: NativePointer): Int

@ExternalSymbolName("FilaBloomOptions_setBlendMode")
internal external fun FilaBloomOptions_setBlendMode(self: NativePointer, value: Int)

@ExternalSymbolName("FilaBloomOptions_getThreshold")
internal external fun FilaBloomOptions_getThreshold(self: NativePointer): Boolean

@ExternalSymbolName("FilaBloomOptions_setThreshold")
internal external fun FilaBloomOptions_setThreshold(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaBloomOptions_getEnabled")
internal external fun FilaBloomOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaBloomOptions_setEnabled")
internal external fun FilaBloomOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaBloomOptions_getHighlight")
internal external fun FilaBloomOptions_getHighlight(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setHighlight")
internal external fun FilaBloomOptions_setHighlight(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getQuality")
internal external fun FilaBloomOptions_getQuality(self: NativePointer): Int

@ExternalSymbolName("FilaBloomOptions_setQuality")
internal external fun FilaBloomOptions_setQuality(self: NativePointer, value: Int)

@ExternalSymbolName("FilaBloomOptions_getLensFlare")
internal external fun FilaBloomOptions_getLensFlare(self: NativePointer): Boolean

@ExternalSymbolName("FilaBloomOptions_setLensFlare")
internal external fun FilaBloomOptions_setLensFlare(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaBloomOptions_getStarburst")
internal external fun FilaBloomOptions_getStarburst(self: NativePointer): Boolean

@ExternalSymbolName("FilaBloomOptions_setStarburst")
internal external fun FilaBloomOptions_setStarburst(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaBloomOptions_getChromaticAberration")
internal external fun FilaBloomOptions_getChromaticAberration(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setChromaticAberration")
internal external fun FilaBloomOptions_setChromaticAberration(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getGhostCount")
internal external fun FilaBloomOptions_getGhostCount(self: NativePointer): Int

@ExternalSymbolName("FilaBloomOptions_setGhostCount")
internal external fun FilaBloomOptions_setGhostCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaBloomOptions_getGhostSpacing")
internal external fun FilaBloomOptions_getGhostSpacing(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setGhostSpacing")
internal external fun FilaBloomOptions_setGhostSpacing(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getGhostThreshold")
internal external fun FilaBloomOptions_getGhostThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setGhostThreshold")
internal external fun FilaBloomOptions_setGhostThreshold(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getHaloThickness")
internal external fun FilaBloomOptions_getHaloThickness(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setHaloThickness")
internal external fun FilaBloomOptions_setHaloThickness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getHaloRadius")
internal external fun FilaBloomOptions_getHaloRadius(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setHaloRadius")
internal external fun FilaBloomOptions_setHaloRadius(self: NativePointer, value: Float)

@ExternalSymbolName("FilaBloomOptions_getHaloThreshold")
internal external fun FilaBloomOptions_getHaloThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaBloomOptions_setHaloThreshold")
internal external fun FilaBloomOptions_setHaloThreshold(self: NativePointer, value: Float)
