// Generated by generateKotlinExternals from c/filament/generated/FilaTemporalAntiAliasingOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_create")
internal external fun FilaTemporalAntiAliasingOptions_create(): NativePointer

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_destroy")
internal external fun FilaTemporalAntiAliasingOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getFilterWidth")
internal external fun FilaTemporalAntiAliasingOptions_getFilterWidth(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setFilterWidth")
internal external fun FilaTemporalAntiAliasingOptions_setFilterWidth(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getFeedback")
internal external fun FilaTemporalAntiAliasingOptions_getFeedback(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setFeedback")
internal external fun FilaTemporalAntiAliasingOptions_setFeedback(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getLodBias")
internal external fun FilaTemporalAntiAliasingOptions_getLodBias(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setLodBias")
internal external fun FilaTemporalAntiAliasingOptions_setLodBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getSharpness")
internal external fun FilaTemporalAntiAliasingOptions_getSharpness(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setSharpness")
internal external fun FilaTemporalAntiAliasingOptions_setSharpness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getEnabled")
internal external fun FilaTemporalAntiAliasingOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setEnabled")
internal external fun FilaTemporalAntiAliasingOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getUpscaling")
internal external fun FilaTemporalAntiAliasingOptions_getUpscaling(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setUpscaling")
internal external fun FilaTemporalAntiAliasingOptions_setUpscaling(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getFilterHistory")
internal external fun FilaTemporalAntiAliasingOptions_getFilterHistory(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setFilterHistory")
internal external fun FilaTemporalAntiAliasingOptions_setFilterHistory(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getFilterInput")
internal external fun FilaTemporalAntiAliasingOptions_getFilterInput(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setFilterInput")
internal external fun FilaTemporalAntiAliasingOptions_setFilterInput(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getUseYCoCg")
internal external fun FilaTemporalAntiAliasingOptions_getUseYCoCg(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setUseYCoCg")
internal external fun FilaTemporalAntiAliasingOptions_setUseYCoCg(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getHdr")
internal external fun FilaTemporalAntiAliasingOptions_getHdr(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setHdr")
internal external fun FilaTemporalAntiAliasingOptions_setHdr(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getBoxType")
internal external fun FilaTemporalAntiAliasingOptions_getBoxType(self: NativePointer): Int

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setBoxType")
internal external fun FilaTemporalAntiAliasingOptions_setBoxType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getBoxClipping")
internal external fun FilaTemporalAntiAliasingOptions_getBoxClipping(self: NativePointer): Int

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setBoxClipping")
internal external fun FilaTemporalAntiAliasingOptions_setBoxClipping(self: NativePointer, value: Int)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getJitterPattern")
internal external fun FilaTemporalAntiAliasingOptions_getJitterPattern(self: NativePointer): Int

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setJitterPattern")
internal external fun FilaTemporalAntiAliasingOptions_setJitterPattern(self: NativePointer, value: Int)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getVarianceGamma")
internal external fun FilaTemporalAntiAliasingOptions_getVarianceGamma(self: NativePointer): Float

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setVarianceGamma")
internal external fun FilaTemporalAntiAliasingOptions_setVarianceGamma(self: NativePointer, value: Float)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getPreventFlickering")
internal external fun FilaTemporalAntiAliasingOptions_getPreventFlickering(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setPreventFlickering")
internal external fun FilaTemporalAntiAliasingOptions_setPreventFlickering(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_getHistoryReprojection")
internal external fun FilaTemporalAntiAliasingOptions_getHistoryReprojection(self: NativePointer): Boolean

@ExternalSymbolName("FilaTemporalAntiAliasingOptions_setHistoryReprojection")
internal external fun FilaTemporalAntiAliasingOptions_setHistoryReprojection(self: NativePointer, value: Boolean)
