// Generated by generateKotlinExternals from c/filament/generated/FilaScreenSpaceReflectionsOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_create")
internal external fun FilaScreenSpaceReflectionsOptions_create(): NativePointer

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_destroy")
internal external fun FilaScreenSpaceReflectionsOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_getThickness")
internal external fun FilaScreenSpaceReflectionsOptions_getThickness(self: NativePointer): Float

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_setThickness")
internal external fun FilaScreenSpaceReflectionsOptions_setThickness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_getBias")
internal external fun FilaScreenSpaceReflectionsOptions_getBias(self: NativePointer): Float

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_setBias")
internal external fun FilaScreenSpaceReflectionsOptions_setBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_getMaxDistance")
internal external fun FilaScreenSpaceReflectionsOptions_getMaxDistance(self: NativePointer): Float

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_setMaxDistance")
internal external fun FilaScreenSpaceReflectionsOptions_setMaxDistance(self: NativePointer, value: Float)

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_getStride")
internal external fun FilaScreenSpaceReflectionsOptions_getStride(self: NativePointer): Float

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_setStride")
internal external fun FilaScreenSpaceReflectionsOptions_setStride(self: NativePointer, value: Float)

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_getEnabled")
internal external fun FilaScreenSpaceReflectionsOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaScreenSpaceReflectionsOptions_setEnabled")
internal external fun FilaScreenSpaceReflectionsOptions_setEnabled(self: NativePointer, value: Boolean)
