// Generated by generateKotlinExternals from c/filament/manual/FilaFrameHistoryStreamManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFrameHistoryStream_getNewFrames")
internal external fun FilaFrameHistoryStream_getNewFrames(self: NativePointer, out: NativePointer, missing: NativePointer, outCapacity: Int): Int
