// Generated by generateKotlinExternals from c/filament/generated/FilaStereoscopicOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaStereoscopicOptions_create")
internal external fun FilaStereoscopicOptions_create(): NativePointer

@ExternalSymbolName("FilaStereoscopicOptions_destroy")
internal external fun FilaStereoscopicOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaStereoscopicOptions_getEnabled")
internal external fun FilaStereoscopicOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaStereoscopicOptions_setEnabled")
internal external fun FilaStereoscopicOptions_setEnabled(self: NativePointer, value: Boolean)
