// Generated by generateKotlinExternals from c/filament/generated/FilaInstanceBuffer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaInstanceBufferBuilder_create")
internal external fun FilaInstanceBufferBuilder_create(instanceCount: Int): NativePointer

@ExternalSymbolName("FilaInstanceBufferBuilder_destroy")
internal external fun FilaInstanceBufferBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaInstanceBufferBuilder_localTransforms")
internal external fun FilaInstanceBufferBuilder_localTransforms(self: NativePointer, localTransforms: NativePointer): NativePointer

@ExternalSymbolName("FilaInstanceBufferBuilder_name")
internal external fun FilaInstanceBufferBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaInstanceBufferBuilder_build")
internal external fun FilaInstanceBufferBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaInstanceBuffer_getInstanceCount")
internal external fun FilaInstanceBuffer_getInstanceCount(self: NativePointer): Int

@ExternalSymbolName("FilaInstanceBuffer_setLocalTransforms")
internal external fun FilaInstanceBuffer_setLocalTransforms(self: NativePointer, localTransforms: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaInstanceBuffer_getLocalTransform")
internal external fun FilaInstanceBuffer_getLocalTransform(self: NativePointer, index: Int, out: NativePointer)
