// Generated by generateKotlinExternals from c/filament/generated/FilaACESToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaACESToneMapper_create")
internal external fun FilaACESToneMapper_create(): NativePointer

@ExternalSymbolName("FilaACESToneMapper_destroy")
internal external fun FilaACESToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaACESToneMapper_asToneMapper")
internal external fun FilaACESToneMapper_asToneMapper(self: NativePointer): NativePointer
