// Generated by generateKotlinExternals from c/filament/manual/FilaSceneManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaScene_forEach")
internal external fun FilaScene_forEach(self: NativePointer, out: NativePointer, outCapacity: Int): Int
