// Generated by generateKotlinExternals from c/filament/generated/FilaToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaToneMapper_destroy")
internal external fun FilaToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaToneMapper_invoke")
internal external fun FilaToneMapper_invoke(self: NativePointer, c: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaToneMapper_isOneDimensional")
internal external fun FilaToneMapper_isOneDimensional(self: NativePointer): Boolean

@ExternalSymbolName("FilaToneMapper_isLDR")
internal external fun FilaToneMapper_isLDR(self: NativePointer): Boolean
