// Generated by generateKotlinExternals from c/filament/generated/FilaStream.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaStreamBuilder_create")
internal external fun FilaStreamBuilder_create(): NativePointer

@ExternalSymbolName("FilaStreamBuilder_destroy")
internal external fun FilaStreamBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaStreamBuilder_width")
internal external fun FilaStreamBuilder_width(self: NativePointer, width: Int): NativePointer

@ExternalSymbolName("FilaStreamBuilder_height")
internal external fun FilaStreamBuilder_height(self: NativePointer, height: Int): NativePointer

@ExternalSymbolName("FilaStreamBuilder_name")
internal external fun FilaStreamBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaStreamBuilder_build")
internal external fun FilaStreamBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaStream_getStreamType")
internal external fun FilaStream_getStreamType(self: NativePointer): Int

@ExternalSymbolName("FilaStream_setAcquiredImage_Callback_void_mat3f")
internal external fun FilaStream_setAcquiredImage_Callback_void_mat3f(self: NativePointer, image: NativePointer, callback: NativePointer, userdata: NativePointer, transform: NativePointer)

@ExternalSymbolName("FilaStream_setAcquiredImage_CallbackHandler_Callback_void_mat3f")
internal external fun FilaStream_setAcquiredImage_CallbackHandler_Callback_void_mat3f(self: NativePointer, image: NativePointer, handler: NativePointer, callback: NativePointer, userdata: NativePointer, transform: NativePointer)

@ExternalSymbolName("FilaStream_setDimensions")
internal external fun FilaStream_setDimensions(self: NativePointer, width: Int, height: Int)

@ExternalSymbolName("FilaStream_getTimestamp")
internal external fun FilaStream_getTimestamp(self: NativePointer, out: NativePointer)
