// Generated by generateKotlinExternals from c/filament/generated/FilaSoftShadowOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaSoftShadowOptions_create")
internal external fun FilaSoftShadowOptions_create(): NativePointer

@ExternalSymbolName("FilaSoftShadowOptions_destroy")
internal external fun FilaSoftShadowOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaSoftShadowOptions_getPenumbraScale")
internal external fun FilaSoftShadowOptions_getPenumbraScale(self: NativePointer): Float

@ExternalSymbolName("FilaSoftShadowOptions_setPenumbraScale")
internal external fun FilaSoftShadowOptions_setPenumbraScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaSoftShadowOptions_getPenumbraRatioScale")
internal external fun FilaSoftShadowOptions_getPenumbraRatioScale(self: NativePointer): Float

@ExternalSymbolName("FilaSoftShadowOptions_setPenumbraRatioScale")
internal external fun FilaSoftShadowOptions_setPenumbraRatioScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaSoftShadowOptions_getMaxPenumbraRatio")
internal external fun FilaSoftShadowOptions_getMaxPenumbraRatio(self: NativePointer): Float

@ExternalSymbolName("FilaSoftShadowOptions_setMaxPenumbraRatio")
internal external fun FilaSoftShadowOptions_setMaxPenumbraRatio(self: NativePointer, value: Float)

@ExternalSymbolName("FilaSoftShadowOptions_getMaxSearchRadius")
internal external fun FilaSoftShadowOptions_getMaxSearchRadius(self: NativePointer): Float

@ExternalSymbolName("FilaSoftShadowOptions_setMaxSearchRadius")
internal external fun FilaSoftShadowOptions_setMaxSearchRadius(self: NativePointer, value: Float)
