// Generated by generateKotlinExternals from c/filament/generated/FilaPBRNeutralToneMapper.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaPBRNeutralToneMapper_create")
internal external fun FilaPBRNeutralToneMapper_create(): NativePointer

@ExternalSymbolName("FilaPBRNeutralToneMapper_destroy")
internal external fun FilaPBRNeutralToneMapper_destroy(self: NativePointer)

@ExternalSymbolName("FilaPBRNeutralToneMapper_asToneMapper")
internal external fun FilaPBRNeutralToneMapper_asToneMapper(self: NativePointer): NativePointer
