// Generated by generateKotlinExternals from c/filament/generated/FilaColorColorSpace.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaColorColorSpace_create")
internal external fun FilaColorColorSpace_create(primaries: NativePointer, transferFunction: NativePointer, whitePoint: NativePointer): NativePointer

@ExternalSymbolName("FilaColorColorSpace_destroy")
internal external fun FilaColorColorSpace_destroy(self: NativePointer)

@ExternalSymbolName("FilaColorColorSpace_getPrimaries")
internal external fun FilaColorColorSpace_getPrimaries(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaColorColorSpace_getTransferFunction")
internal external fun FilaColorColorSpace_getTransferFunction(self: NativePointer): NativePointer

@ExternalSymbolName("FilaColorColorSpace_getWhitePoint")
internal external fun FilaColorColorSpace_getWhitePoint(self: NativePointer, out: NativePointer)
