// Generated by generateKotlinExternals from c/filament/generated/FilaRenderableManager.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaRenderableManagerBone_create")
internal external fun FilaRenderableManagerBone_create(): NativePointer

@ExternalSymbolName("FilaRenderableManagerBone_destroy")
internal external fun FilaRenderableManagerBone_destroy(self: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBone_getUnitQuaternion")
internal external fun FilaRenderableManagerBone_getUnitQuaternion(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBone_setUnitQuaternion")
internal external fun FilaRenderableManagerBone_setUnitQuaternion(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBone_getTranslation")
internal external fun FilaRenderableManagerBone_getTranslation(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBone_setTranslation")
internal external fun FilaRenderableManagerBone_setTranslation(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBuilder_create")
internal external fun FilaRenderableManagerBuilder_create(count: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_destroy")
internal external fun FilaRenderableManagerBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaRenderableManagerBuilder_geometry_IndexBuffer_size_t_size_t_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_geometry_IndexBuffer_size_t_size_t_size_t_size_t(self: NativePointer, index: Int, type: Int, vertices: NativePointer, indices: NativePointer, offset: Int, minIndex: Int, maxIndex: Int, count: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_geometry_IndexBuffer_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_geometry_IndexBuffer_size_t_size_t(self: NativePointer, index: Int, type: Int, vertices: NativePointer, indices: NativePointer, offset: Int, count: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_geometry_IndexBuffer")
internal external fun FilaRenderableManagerBuilder_geometry_IndexBuffer(self: NativePointer, index: Int, type: Int, vertices: NativePointer, indices: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_geometry_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_geometry_size_t_size_t(self: NativePointer, index: Int, type: Int, vertices: NativePointer, offset: Int, count: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_geometry")
internal external fun FilaRenderableManagerBuilder_geometry(self: NativePointer, index: Int, type: Int, vertices: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_geometryType")
internal external fun FilaRenderableManagerBuilder_geometryType(self: NativePointer, type: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_material")
internal external fun FilaRenderableManagerBuilder_material(self: NativePointer, index: Int, materialInstance: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_boundingBox")
internal external fun FilaRenderableManagerBuilder_boundingBox(self: NativePointer, axisAlignedBoundingBox: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_layerMask")
internal external fun FilaRenderableManagerBuilder_layerMask(self: NativePointer, select: Int, values: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_priority")
internal external fun FilaRenderableManagerBuilder_priority(self: NativePointer, priority: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_channel")
internal external fun FilaRenderableManagerBuilder_channel(self: NativePointer, channel: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_culling")
internal external fun FilaRenderableManagerBuilder_culling(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_lightChannel")
internal external fun FilaRenderableManagerBuilder_lightChannel(self: NativePointer, channel: Int, enable: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_castShadows")
internal external fun FilaRenderableManagerBuilder_castShadows(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_receiveShadows")
internal external fun FilaRenderableManagerBuilder_receiveShadows(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_screenSpaceContactShadows")
internal external fun FilaRenderableManagerBuilder_screenSpaceContactShadows(self: NativePointer, enable: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_enableSkinningBuffers")
internal external fun FilaRenderableManagerBuilder_enableSkinningBuffers(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_fog")
internal external fun FilaRenderableManagerBuilder_fog(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_skinning_SkinningBuffer_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_skinning_SkinningBuffer_size_t_size_t(self: NativePointer, skinningBuffer: NativePointer, count: Int, offset: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_skinning_size_t")
internal external fun FilaRenderableManagerBuilder_skinning_size_t(self: NativePointer, boneCount: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_skinning_size_t_mat4f")
internal external fun FilaRenderableManagerBuilder_skinning_size_t_mat4f(self: NativePointer, boneCount: Int, transforms: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_skinning_size_t_Bone")
internal external fun FilaRenderableManagerBuilder_skinning_size_t_Bone(self: NativePointer, boneCount: Int, bones: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_boneIndicesAndWeights_float2_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_boneIndicesAndWeights_float2_size_t_size_t(self: NativePointer, primitiveIndex: Int, indicesAndWeights: NativePointer, count: Int, bonesPerVertex: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_morphing_size_t")
internal external fun FilaRenderableManagerBuilder_morphing_size_t(self: NativePointer, targetCount: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_morphing_MorphTargetBuffer")
internal external fun FilaRenderableManagerBuilder_morphing_MorphTargetBuffer(self: NativePointer, morphTargetBuffer: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_morphing_uint8_t_size_t_size_t")
internal external fun FilaRenderableManagerBuilder_morphing_uint8_t_size_t_size_t(self: NativePointer, level: Int, primitiveIndex: Int, offset: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_blendOrder")
internal external fun FilaRenderableManagerBuilder_blendOrder(self: NativePointer, primitiveIndex: Int, blendOrder: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_globalBlendOrderEnabled")
internal external fun FilaRenderableManagerBuilder_globalBlendOrderEnabled(self: NativePointer, primitiveIndex: Int, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_instances")
internal external fun FilaRenderableManagerBuilder_instances(self: NativePointer, instanceCount: Int): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_instances_InstanceBuffer")
internal external fun FilaRenderableManagerBuilder_instances_InstanceBuffer(self: NativePointer, instanceCount: Int, instanceBuffer: NativePointer): NativePointer

@ExternalSymbolName("FilaRenderableManagerBuilder_build")
internal external fun FilaRenderableManagerBuilder_build(self: NativePointer, engine: NativePointer, entity: Int): Int

@ExternalSymbolName("FilaRenderableManager_hasComponent")
internal external fun FilaRenderableManager_hasComponent(self: NativePointer, e: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_getInstance")
internal external fun FilaRenderableManager_getInstance(self: NativePointer, e: Int): Int

@ExternalSymbolName("FilaRenderableManager_getComponentCount")
internal external fun FilaRenderableManager_getComponentCount(self: NativePointer): Int

@ExternalSymbolName("FilaRenderableManager_empty")
internal external fun FilaRenderableManager_empty(self: NativePointer): Boolean

@ExternalSymbolName("FilaRenderableManager_getEntity")
internal external fun FilaRenderableManager_getEntity(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaRenderableManager_getAllEntities")
internal external fun FilaRenderableManager_getAllEntities(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaRenderableManager_destroy")
internal external fun FilaRenderableManager_destroy(self: NativePointer, e: Int)

@ExternalSymbolName("FilaRenderableManager_setAxisAlignedBoundingBox")
internal external fun FilaRenderableManager_setAxisAlignedBoundingBox(self: NativePointer, instance: Int, aabb: NativePointer)

@ExternalSymbolName("FilaRenderableManager_getAxisAlignedBoundingBox")
internal external fun FilaRenderableManager_getAxisAlignedBoundingBox(self: NativePointer, instance: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_setLayerMask")
internal external fun FilaRenderableManager_setLayerMask(self: NativePointer, instance: Int, select: Int, values: Int)

@ExternalSymbolName("FilaRenderableManager_getLayerMask")
internal external fun FilaRenderableManager_getLayerMask(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_setPriority")
internal external fun FilaRenderableManager_setPriority(self: NativePointer, instance: Int, priority: Int)

@ExternalSymbolName("FilaRenderableManager_getPriority")
internal external fun FilaRenderableManager_getPriority(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_setChannel")
internal external fun FilaRenderableManager_setChannel(self: NativePointer, instance: Int, channel: Int)

@ExternalSymbolName("FilaRenderableManager_getChannel")
internal external fun FilaRenderableManager_getChannel(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_setCulling")
internal external fun FilaRenderableManager_setCulling(self: NativePointer, instance: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_isCullingEnabled")
internal external fun FilaRenderableManager_isCullingEnabled(self: NativePointer, instance: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_setFogEnabled")
internal external fun FilaRenderableManager_setFogEnabled(self: NativePointer, instance: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_getFogEnabled")
internal external fun FilaRenderableManager_getFogEnabled(self: NativePointer, instance: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_setLightChannel")
internal external fun FilaRenderableManager_setLightChannel(self: NativePointer, instance: Int, channel: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_getLightChannel")
internal external fun FilaRenderableManager_getLightChannel(self: NativePointer, instance: Int, channel: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_setCastShadows")
internal external fun FilaRenderableManager_setCastShadows(self: NativePointer, instance: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_setReceiveShadows")
internal external fun FilaRenderableManager_setReceiveShadows(self: NativePointer, instance: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_setScreenSpaceContactShadows")
internal external fun FilaRenderableManager_setScreenSpaceContactShadows(self: NativePointer, instance: Int, enable: Boolean)

@ExternalSymbolName("FilaRenderableManager_isShadowCaster")
internal external fun FilaRenderableManager_isShadowCaster(self: NativePointer, instance: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_isShadowReceiver")
internal external fun FilaRenderableManager_isShadowReceiver(self: NativePointer, instance: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_isScreenSpaceContactShadowsEnabled")
internal external fun FilaRenderableManager_isScreenSpaceContactShadowsEnabled(self: NativePointer, instance: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_setBones_Bone_size_t_size_t")
internal external fun FilaRenderableManager_setBones_Bone_size_t_size_t(self: NativePointer, instance: Int, transforms: NativePointer, boneCount: Int, offset: Int)

@ExternalSymbolName("FilaRenderableManager_setBones_mat4f_size_t_size_t")
internal external fun FilaRenderableManager_setBones_mat4f_size_t_size_t(self: NativePointer, instance: Int, transforms: NativePointer, boneCount: Int, offset: Int)

@ExternalSymbolName("FilaRenderableManager_setSkinningBuffer")
internal external fun FilaRenderableManager_setSkinningBuffer(self: NativePointer, instance: Int, skinningBuffer: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaRenderableManager_setMorphWeights")
internal external fun FilaRenderableManager_setMorphWeights(self: NativePointer, instance: Int, weights: NativePointer, count: Int, offset: Int)

@ExternalSymbolName("FilaRenderableManager_setMorphTargetBufferOffsetAt")
internal external fun FilaRenderableManager_setMorphTargetBufferOffsetAt(self: NativePointer, instance: Int, level: Int, primitiveIndex: Int, offset: Int)

@ExternalSymbolName("FilaRenderableManager_getMorphTargetBuffer")
internal external fun FilaRenderableManager_getMorphTargetBuffer(self: NativePointer, instance: Int): NativePointer

@ExternalSymbolName("FilaRenderableManager_getMorphTargetCount")
internal external fun FilaRenderableManager_getMorphTargetCount(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_getPrimitiveCount")
internal external fun FilaRenderableManager_getPrimitiveCount(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_getInstanceCount")
internal external fun FilaRenderableManager_getInstanceCount(self: NativePointer, instance: Int): Int

@ExternalSymbolName("FilaRenderableManager_setMaterialInstanceAt")
internal external fun FilaRenderableManager_setMaterialInstanceAt(self: NativePointer, instance: Int, primitiveIndex: Int, materialInstance: NativePointer)

@ExternalSymbolName("FilaRenderableManager_clearMaterialInstanceAt")
internal external fun FilaRenderableManager_clearMaterialInstanceAt(self: NativePointer, instance: Int, primitiveIndex: Int)

@ExternalSymbolName("FilaRenderableManager_getMaterialInstanceAt")
internal external fun FilaRenderableManager_getMaterialInstanceAt(self: NativePointer, instance: Int, primitiveIndex: Int): NativePointer

@ExternalSymbolName("FilaRenderableManager_setGeometryAt_IndexBuffer")
internal external fun FilaRenderableManager_setGeometryAt_IndexBuffer(self: NativePointer, instance: Int, primitiveIndex: Int, type: Int, vertices: NativePointer, indices: NativePointer)

@ExternalSymbolName("FilaRenderableManager_setGeometryAt_IndexBuffer_size_t_size_t")
internal external fun FilaRenderableManager_setGeometryAt_IndexBuffer_size_t_size_t(self: NativePointer, instance: Int, primitiveIndex: Int, type: Int, vertices: NativePointer, indices: NativePointer, offset: Int, count: Int)

@ExternalSymbolName("FilaRenderableManager_setGeometryAt")
internal external fun FilaRenderableManager_setGeometryAt(self: NativePointer, instance: Int, primitiveIndex: Int, type: Int, vertices: NativePointer)

@ExternalSymbolName("FilaRenderableManager_setGeometryAt_size_t_size_t")
internal external fun FilaRenderableManager_setGeometryAt_size_t_size_t(self: NativePointer, instance: Int, primitiveIndex: Int, type: Int, vertices: NativePointer, offset: Int, count: Int)

@ExternalSymbolName("FilaRenderableManager_setBlendOrderAt")
internal external fun FilaRenderableManager_setBlendOrderAt(self: NativePointer, instance: Int, primitiveIndex: Int, order: Int)

@ExternalSymbolName("FilaRenderableManager_getBlendOrderAt")
internal external fun FilaRenderableManager_getBlendOrderAt(self: NativePointer, instance: Int, primitiveIndex: Int): Int

@ExternalSymbolName("FilaRenderableManager_setGlobalBlendOrderEnabledAt")
internal external fun FilaRenderableManager_setGlobalBlendOrderEnabledAt(self: NativePointer, instance: Int, primitiveIndex: Int, enabled: Boolean)

@ExternalSymbolName("FilaRenderableManager_isGlobalBlendOrderEnabledAt")
internal external fun FilaRenderableManager_isGlobalBlendOrderEnabledAt(self: NativePointer, instance: Int, primitiveIndex: Int): Boolean

@ExternalSymbolName("FilaRenderableManager_getEnabledAttributesAt")
internal external fun FilaRenderableManager_getEnabledAttributesAt(self: NativePointer, instance: Int, primitiveIndex: Int): Int

@ExternalSymbolName("FilaRenderableManager_computeAABB_float4_uint16_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_float4_uint16_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_float4_uint32_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_float4_uint32_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_half4_uint16_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_half4_uint16_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_half4_uint32_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_half4_uint32_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_float3_uint16_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_float3_uint16_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_float3_uint32_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_float3_uint32_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_half3_uint16_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_half3_uint16_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)

@ExternalSymbolName("FilaRenderableManager_computeAABB_half3_uint32_t_size_t_size_t")
internal external fun FilaRenderableManager_computeAABB_half3_uint32_t_size_t_size_t(vertices: NativePointer, indices: NativePointer, count: Int, stride: Int, out: NativePointer)
