// Generated by generateKotlinExternals from c/filament/generated/FilaBufferObject.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaBufferObjectBuilder_create")
internal external fun FilaBufferObjectBuilder_create(): NativePointer

@ExternalSymbolName("FilaBufferObjectBuilder_destroy")
internal external fun FilaBufferObjectBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaBufferObjectBuilder_size")
internal external fun FilaBufferObjectBuilder_size(self: NativePointer, byteCount: Int): NativePointer

@ExternalSymbolName("FilaBufferObjectBuilder_bindingType")
internal external fun FilaBufferObjectBuilder_bindingType(self: NativePointer, bindingType: Int): NativePointer

@ExternalSymbolName("FilaBufferObjectBuilder_name")
internal external fun FilaBufferObjectBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaBufferObjectBuilder_build")
internal external fun FilaBufferObjectBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaBufferObject_setBuffer")
internal external fun FilaBufferObject_setBuffer(self: NativePointer, engine: NativePointer, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer, byteOffset: Int)

@ExternalSymbolName("FilaBufferObject_getByteCount")
internal external fun FilaBufferObject_getByteCount(self: NativePointer): Int
