// Generated by generateKotlinExternals from c/filament/generated/FilaRenderQuality.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaRenderQuality_create")
internal external fun FilaRenderQuality_create(): NativePointer

@ExternalSymbolName("FilaRenderQuality_destroy")
internal external fun FilaRenderQuality_destroy(self: NativePointer)

@ExternalSymbolName("FilaRenderQuality_getHdrColorBuffer")
internal external fun FilaRenderQuality_getHdrColorBuffer(self: NativePointer): Int

@ExternalSymbolName("FilaRenderQuality_setHdrColorBuffer")
internal external fun FilaRenderQuality_setHdrColorBuffer(self: NativePointer, value: Int)
