// Generated by generateKotlinExternals from c/filament/generated/FilaTransformManager.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaTransformManager_hasComponent")
internal external fun FilaTransformManager_hasComponent(self: NativePointer, e: Int): Boolean

@ExternalSymbolName("FilaTransformManager_getInstance")
internal external fun FilaTransformManager_getInstance(self: NativePointer, e: Int): Int

@ExternalSymbolName("FilaTransformManager_getComponentCount")
internal external fun FilaTransformManager_getComponentCount(self: NativePointer): Int

@ExternalSymbolName("FilaTransformManager_empty")
internal external fun FilaTransformManager_empty(self: NativePointer): Boolean

@ExternalSymbolName("FilaTransformManager_getEntity")
internal external fun FilaTransformManager_getEntity(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaTransformManager_getAllEntities")
internal external fun FilaTransformManager_getAllEntities(self: NativePointer, out: NativePointer, outCapacity: Int): Int

@ExternalSymbolName("FilaTransformManager_setAccurateTranslationsEnabled")
internal external fun FilaTransformManager_setAccurateTranslationsEnabled(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaTransformManager_isAccurateTranslationsEnabled")
internal external fun FilaTransformManager_isAccurateTranslationsEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaTransformManager_create_mat4f")
internal external fun FilaTransformManager_create_mat4f(self: NativePointer, entity: Int, parent: Int, localTransform: NativePointer)

@ExternalSymbolName("FilaTransformManager_create_mat4")
internal external fun FilaTransformManager_create_mat4(self: NativePointer, entity: Int, parent: Int, localTransform: NativePointer)

@ExternalSymbolName("FilaTransformManager_create")
internal external fun FilaTransformManager_create(self: NativePointer, entity: Int, parent: Int)

@ExternalSymbolName("FilaTransformManager_destroy")
internal external fun FilaTransformManager_destroy(self: NativePointer, e: Int)

@ExternalSymbolName("FilaTransformManager_setParent")
internal external fun FilaTransformManager_setParent(self: NativePointer, i: Int, newParent: Int)

@ExternalSymbolName("FilaTransformManager_getParent")
internal external fun FilaTransformManager_getParent(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaTransformManager_getChildCount")
internal external fun FilaTransformManager_getChildCount(self: NativePointer, i: Int): Int

@ExternalSymbolName("FilaTransformManager_getChildren")
internal external fun FilaTransformManager_getChildren(self: NativePointer, i: Int, children: NativePointer, count: Int): Int

@ExternalSymbolName("FilaTransformManager_setTransform_mat4f")
internal external fun FilaTransformManager_setTransform_mat4f(self: NativePointer, ci: Int, localTransform: NativePointer)

@ExternalSymbolName("FilaTransformManager_setTransform_mat4")
internal external fun FilaTransformManager_setTransform_mat4(self: NativePointer, ci: Int, localTransform: NativePointer)

@ExternalSymbolName("FilaTransformManager_getTransform")
internal external fun FilaTransformManager_getTransform(self: NativePointer, ci: Int, out: NativePointer)

@ExternalSymbolName("FilaTransformManager_getTransformAccurate")
internal external fun FilaTransformManager_getTransformAccurate(self: NativePointer, ci: Int, out: NativePointer)

@ExternalSymbolName("FilaTransformManager_getWorldTransform")
internal external fun FilaTransformManager_getWorldTransform(self: NativePointer, ci: Int, out: NativePointer)

@ExternalSymbolName("FilaTransformManager_getWorldTransformAccurate")
internal external fun FilaTransformManager_getWorldTransformAccurate(self: NativePointer, ci: Int, out: NativePointer)

@ExternalSymbolName("FilaTransformManager_openLocalTransformTransaction")
internal external fun FilaTransformManager_openLocalTransformTransaction(self: NativePointer)

@ExternalSymbolName("FilaTransformManager_commitLocalTransformTransaction")
internal external fun FilaTransformManager_commitLocalTransformTransaction(self: NativePointer)
