// Generated by generateKotlinExternals from c/filament/generated/FilaDepthOfFieldOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaDepthOfFieldOptions_create")
internal external fun FilaDepthOfFieldOptions_create(): NativePointer

@ExternalSymbolName("FilaDepthOfFieldOptions_destroy")
internal external fun FilaDepthOfFieldOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaDepthOfFieldOptions_getCocScale")
internal external fun FilaDepthOfFieldOptions_getCocScale(self: NativePointer): Float

@ExternalSymbolName("FilaDepthOfFieldOptions_setCocScale")
internal external fun FilaDepthOfFieldOptions_setCocScale(self: NativePointer, value: Float)

@ExternalSymbolName("FilaDepthOfFieldOptions_getCocAspectRatio")
internal external fun FilaDepthOfFieldOptions_getCocAspectRatio(self: NativePointer): Float

@ExternalSymbolName("FilaDepthOfFieldOptions_setCocAspectRatio")
internal external fun FilaDepthOfFieldOptions_setCocAspectRatio(self: NativePointer, value: Float)

@ExternalSymbolName("FilaDepthOfFieldOptions_getMaxApertureDiameter")
internal external fun FilaDepthOfFieldOptions_getMaxApertureDiameter(self: NativePointer): Float

@ExternalSymbolName("FilaDepthOfFieldOptions_setMaxApertureDiameter")
internal external fun FilaDepthOfFieldOptions_setMaxApertureDiameter(self: NativePointer, value: Float)

@ExternalSymbolName("FilaDepthOfFieldOptions_getEnabled")
internal external fun FilaDepthOfFieldOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaDepthOfFieldOptions_setEnabled")
internal external fun FilaDepthOfFieldOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaDepthOfFieldOptions_getFilter")
internal external fun FilaDepthOfFieldOptions_getFilter(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setFilter")
internal external fun FilaDepthOfFieldOptions_setFilter(self: NativePointer, value: Int)

@ExternalSymbolName("FilaDepthOfFieldOptions_getNativeResolution")
internal external fun FilaDepthOfFieldOptions_getNativeResolution(self: NativePointer): Boolean

@ExternalSymbolName("FilaDepthOfFieldOptions_setNativeResolution")
internal external fun FilaDepthOfFieldOptions_setNativeResolution(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaDepthOfFieldOptions_getForegroundRingCount")
internal external fun FilaDepthOfFieldOptions_getForegroundRingCount(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setForegroundRingCount")
internal external fun FilaDepthOfFieldOptions_setForegroundRingCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaDepthOfFieldOptions_getBackgroundRingCount")
internal external fun FilaDepthOfFieldOptions_getBackgroundRingCount(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setBackgroundRingCount")
internal external fun FilaDepthOfFieldOptions_setBackgroundRingCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaDepthOfFieldOptions_getFastGatherRingCount")
internal external fun FilaDepthOfFieldOptions_getFastGatherRingCount(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setFastGatherRingCount")
internal external fun FilaDepthOfFieldOptions_setFastGatherRingCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaDepthOfFieldOptions_getMaxForegroundCOC")
internal external fun FilaDepthOfFieldOptions_getMaxForegroundCOC(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setMaxForegroundCOC")
internal external fun FilaDepthOfFieldOptions_setMaxForegroundCOC(self: NativePointer, value: Int)

@ExternalSymbolName("FilaDepthOfFieldOptions_getMaxBackgroundCOC")
internal external fun FilaDepthOfFieldOptions_getMaxBackgroundCOC(self: NativePointer): Int

@ExternalSymbolName("FilaDepthOfFieldOptions_setMaxBackgroundCOC")
internal external fun FilaDepthOfFieldOptions_setMaxBackgroundCOC(self: NativePointer, value: Int)
