// Generated by generateKotlinExternals from c/filament/manual/FilaFramePacerManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaFramePacerVsyncTick_setTimelines")
internal external fun FilaFramePacerVsyncTick_setTimelines(self: NativePointer, times: NativePointer, count: Int)
