// Generated by generateKotlinExternals from c/filament/generated/FilaAmbientOcclusionOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_create")
internal external fun FilaAmbientOcclusionOptionsSsct_create(): NativePointer

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_destroy")
internal external fun FilaAmbientOcclusionOptionsSsct_destroy(self: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getLightConeRad")
internal external fun FilaAmbientOcclusionOptionsSsct_getLightConeRad(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setLightConeRad")
internal external fun FilaAmbientOcclusionOptionsSsct_setLightConeRad(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getShadowDistance")
internal external fun FilaAmbientOcclusionOptionsSsct_getShadowDistance(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setShadowDistance")
internal external fun FilaAmbientOcclusionOptionsSsct_setShadowDistance(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getContactDistanceMax")
internal external fun FilaAmbientOcclusionOptionsSsct_getContactDistanceMax(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setContactDistanceMax")
internal external fun FilaAmbientOcclusionOptionsSsct_setContactDistanceMax(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getIntensity")
internal external fun FilaAmbientOcclusionOptionsSsct_getIntensity(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setIntensity")
internal external fun FilaAmbientOcclusionOptionsSsct_setIntensity(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getLightDirection")
internal external fun FilaAmbientOcclusionOptionsSsct_getLightDirection(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setLightDirection")
internal external fun FilaAmbientOcclusionOptionsSsct_setLightDirection(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getDepthBias")
internal external fun FilaAmbientOcclusionOptionsSsct_getDepthBias(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setDepthBias")
internal external fun FilaAmbientOcclusionOptionsSsct_setDepthBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getDepthSlopeBias")
internal external fun FilaAmbientOcclusionOptionsSsct_getDepthSlopeBias(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setDepthSlopeBias")
internal external fun FilaAmbientOcclusionOptionsSsct_setDepthSlopeBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getSampleCount")
internal external fun FilaAmbientOcclusionOptionsSsct_getSampleCount(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setSampleCount")
internal external fun FilaAmbientOcclusionOptionsSsct_setSampleCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getRayCount")
internal external fun FilaAmbientOcclusionOptionsSsct_getRayCount(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setRayCount")
internal external fun FilaAmbientOcclusionOptionsSsct_setRayCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_getEnabled")
internal external fun FilaAmbientOcclusionOptionsSsct_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaAmbientOcclusionOptionsSsct_setEnabled")
internal external fun FilaAmbientOcclusionOptionsSsct_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_create")
internal external fun FilaAmbientOcclusionOptionsGtao_create(): NativePointer

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_destroy")
internal external fun FilaAmbientOcclusionOptionsGtao_destroy(self: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getSampleSliceCount")
internal external fun FilaAmbientOcclusionOptionsGtao_getSampleSliceCount(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setSampleSliceCount")
internal external fun FilaAmbientOcclusionOptionsGtao_setSampleSliceCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getSampleStepsPerSlice")
internal external fun FilaAmbientOcclusionOptionsGtao_getSampleStepsPerSlice(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setSampleStepsPerSlice")
internal external fun FilaAmbientOcclusionOptionsGtao_setSampleStepsPerSlice(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getThicknessHeuristic")
internal external fun FilaAmbientOcclusionOptionsGtao_getThicknessHeuristic(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setThicknessHeuristic")
internal external fun FilaAmbientOcclusionOptionsGtao_setThicknessHeuristic(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getUseVisibilityBitmasks")
internal external fun FilaAmbientOcclusionOptionsGtao_getUseVisibilityBitmasks(self: NativePointer): Boolean

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setUseVisibilityBitmasks")
internal external fun FilaAmbientOcclusionOptionsGtao_setUseVisibilityBitmasks(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getConstThickness")
internal external fun FilaAmbientOcclusionOptionsGtao_getConstThickness(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setConstThickness")
internal external fun FilaAmbientOcclusionOptionsGtao_setConstThickness(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_getLinearThickness")
internal external fun FilaAmbientOcclusionOptionsGtao_getLinearThickness(self: NativePointer): Boolean

@ExternalSymbolName("FilaAmbientOcclusionOptionsGtao_setLinearThickness")
internal external fun FilaAmbientOcclusionOptionsGtao_setLinearThickness(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaAmbientOcclusionOptions_create")
internal external fun FilaAmbientOcclusionOptions_create(): NativePointer

@ExternalSymbolName("FilaAmbientOcclusionOptions_destroy")
internal external fun FilaAmbientOcclusionOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getAoType")
internal external fun FilaAmbientOcclusionOptions_getAoType(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptions_setAoType")
internal external fun FilaAmbientOcclusionOptions_setAoType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getRadius")
internal external fun FilaAmbientOcclusionOptions_getRadius(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setRadius")
internal external fun FilaAmbientOcclusionOptions_setRadius(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getPower")
internal external fun FilaAmbientOcclusionOptions_getPower(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setPower")
internal external fun FilaAmbientOcclusionOptions_setPower(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getBias")
internal external fun FilaAmbientOcclusionOptions_getBias(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setBias")
internal external fun FilaAmbientOcclusionOptions_setBias(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getResolution")
internal external fun FilaAmbientOcclusionOptions_getResolution(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setResolution")
internal external fun FilaAmbientOcclusionOptions_setResolution(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getIntensity")
internal external fun FilaAmbientOcclusionOptions_getIntensity(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setIntensity")
internal external fun FilaAmbientOcclusionOptions_setIntensity(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getBilateralThreshold")
internal external fun FilaAmbientOcclusionOptions_getBilateralThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setBilateralThreshold")
internal external fun FilaAmbientOcclusionOptions_setBilateralThreshold(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getQuality")
internal external fun FilaAmbientOcclusionOptions_getQuality(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptions_setQuality")
internal external fun FilaAmbientOcclusionOptions_setQuality(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getLowPassFilter")
internal external fun FilaAmbientOcclusionOptions_getLowPassFilter(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptions_setLowPassFilter")
internal external fun FilaAmbientOcclusionOptions_setLowPassFilter(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getUpsampling")
internal external fun FilaAmbientOcclusionOptions_getUpsampling(self: NativePointer): Int

@ExternalSymbolName("FilaAmbientOcclusionOptions_setUpsampling")
internal external fun FilaAmbientOcclusionOptions_setUpsampling(self: NativePointer, value: Int)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getEnabled")
internal external fun FilaAmbientOcclusionOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaAmbientOcclusionOptions_setEnabled")
internal external fun FilaAmbientOcclusionOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getBentNormals")
internal external fun FilaAmbientOcclusionOptions_getBentNormals(self: NativePointer): Boolean

@ExternalSymbolName("FilaAmbientOcclusionOptions_setBentNormals")
internal external fun FilaAmbientOcclusionOptions_setBentNormals(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getMinHorizonAngleRad")
internal external fun FilaAmbientOcclusionOptions_getMinHorizonAngleRad(self: NativePointer): Float

@ExternalSymbolName("FilaAmbientOcclusionOptions_setMinHorizonAngleRad")
internal external fun FilaAmbientOcclusionOptions_setMinHorizonAngleRad(self: NativePointer, value: Float)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getSsct")
internal external fun FilaAmbientOcclusionOptions_getSsct(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptions_setSsct")
internal external fun FilaAmbientOcclusionOptions_setSsct(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptions_getGtao")
internal external fun FilaAmbientOcclusionOptions_getGtao(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaAmbientOcclusionOptions_setGtao")
internal external fun FilaAmbientOcclusionOptions_setGtao(self: NativePointer, value: NativePointer)
