// Generated by generateKotlinExternals from c/filament/manual/FilaMaterialManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaMaterial_getParameters")
internal external fun FilaMaterial_getParameters(self: NativePointer, out: NativePointer, outCapacity: Int): Int
