// Generated by generateKotlinExternals from c/filament/generated/FilaView.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaViewPickingQueryResult_create")
internal external fun FilaViewPickingQueryResult_create(): NativePointer

@ExternalSymbolName("FilaViewPickingQueryResult_destroy")
internal external fun FilaViewPickingQueryResult_destroy(self: NativePointer)

@ExternalSymbolName("FilaViewPickingQueryResult_getRenderable")
internal external fun FilaViewPickingQueryResult_getRenderable(self: NativePointer): Int

@ExternalSymbolName("FilaViewPickingQueryResult_setRenderable")
internal external fun FilaViewPickingQueryResult_setRenderable(self: NativePointer, value: Int)

@ExternalSymbolName("FilaViewPickingQueryResult_getDepth")
internal external fun FilaViewPickingQueryResult_getDepth(self: NativePointer): Float

@ExternalSymbolName("FilaViewPickingQueryResult_setDepth")
internal external fun FilaViewPickingQueryResult_setDepth(self: NativePointer, value: Float)

@ExternalSymbolName("FilaViewPickingQueryResult_getFragCoords")
internal external fun FilaViewPickingQueryResult_getFragCoords(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaViewPickingQueryResult_setFragCoords")
internal external fun FilaViewPickingQueryResult_setFragCoords(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaViewPickingQuery_create")
internal external fun FilaViewPickingQuery_create(): NativePointer

@ExternalSymbolName("FilaViewPickingQuery_destroy")
internal external fun FilaViewPickingQuery_destroy(self: NativePointer)

@ExternalSymbolName("FilaView_setName")
internal external fun FilaView_setName(self: NativePointer, name: NativePointer)

@ExternalSymbolName("FilaView_getName")
internal external fun FilaView_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaView_setScene")
internal external fun FilaView_setScene(self: NativePointer, scene: NativePointer)

@ExternalSymbolName("FilaView_getScene")
internal external fun FilaView_getScene(self: NativePointer): NativePointer

@ExternalSymbolName("FilaView_setRenderTarget")
internal external fun FilaView_setRenderTarget(self: NativePointer, renderTarget: NativePointer)

@ExternalSymbolName("FilaView_getRenderTarget")
internal external fun FilaView_getRenderTarget(self: NativePointer): NativePointer

@ExternalSymbolName("FilaView_setViewport")
internal external fun FilaView_setViewport(self: NativePointer, viewport: NativePointer)

@ExternalSymbolName("FilaView_getViewport")
internal external fun FilaView_getViewport(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setCamera")
internal external fun FilaView_setCamera(self: NativePointer, camera: NativePointer)

@ExternalSymbolName("FilaView_hasCamera")
internal external fun FilaView_hasCamera(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_getCamera")
internal external fun FilaView_getCamera(self: NativePointer): NativePointer

@ExternalSymbolName("FilaView_setChannelDepthClearEnabled")
internal external fun FilaView_setChannelDepthClearEnabled(self: NativePointer, channel: Int, enabled: Boolean)

@ExternalSymbolName("FilaView_isChannelDepthClearEnabled")
internal external fun FilaView_isChannelDepthClearEnabled(self: NativePointer, channel: Int): Boolean

@ExternalSymbolName("FilaView_setBlendMode")
internal external fun FilaView_setBlendMode(self: NativePointer, blendMode: Int)

@ExternalSymbolName("FilaView_getBlendMode")
internal external fun FilaView_getBlendMode(self: NativePointer): Int

@ExternalSymbolName("FilaView_setVisibleLayers")
internal external fun FilaView_setVisibleLayers(self: NativePointer, select: Int, values: Int)

@ExternalSymbolName("FilaView_setLayerEnabled")
internal external fun FilaView_setLayerEnabled(self: NativePointer, layer: Int, enabled: Boolean)

@ExternalSymbolName("FilaView_getVisibleLayers")
internal external fun FilaView_getVisibleLayers(self: NativePointer): Int

@ExternalSymbolName("FilaView_setShadowingEnabled")
internal external fun FilaView_setShadowingEnabled(self: NativePointer, enabled: Boolean)

@ExternalSymbolName("FilaView_isShadowingEnabled")
internal external fun FilaView_isShadowingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setScreenSpaceRefractionEnabled")
internal external fun FilaView_setScreenSpaceRefractionEnabled(self: NativePointer, enabled: Boolean)

@ExternalSymbolName("FilaView_isScreenSpaceRefractionEnabled")
internal external fun FilaView_isScreenSpaceRefractionEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setAntiAliasing")
internal external fun FilaView_setAntiAliasing(self: NativePointer, type: Int)

@ExternalSymbolName("FilaView_getAntiAliasing")
internal external fun FilaView_getAntiAliasing(self: NativePointer): Int

@ExternalSymbolName("FilaView_setTemporalAntiAliasingOptions")
internal external fun FilaView_setTemporalAntiAliasingOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getTemporalAntiAliasingOptions")
internal external fun FilaView_getTemporalAntiAliasingOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setScreenSpaceReflectionsOptions")
internal external fun FilaView_setScreenSpaceReflectionsOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getScreenSpaceReflectionsOptions")
internal external fun FilaView_getScreenSpaceReflectionsOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setGuardBandOptions")
internal external fun FilaView_setGuardBandOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getGuardBandOptions")
internal external fun FilaView_getGuardBandOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setMultiSampleAntiAliasingOptions")
internal external fun FilaView_setMultiSampleAntiAliasingOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getMultiSampleAntiAliasingOptions")
internal external fun FilaView_getMultiSampleAntiAliasingOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setColorGrading")
internal external fun FilaView_setColorGrading(self: NativePointer, colorGrading: NativePointer)

@ExternalSymbolName("FilaView_getColorGrading")
internal external fun FilaView_getColorGrading(self: NativePointer): NativePointer

@ExternalSymbolName("FilaView_setAmbientOcclusionOptions")
internal external fun FilaView_setAmbientOcclusionOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getAmbientOcclusionOptions")
internal external fun FilaView_getAmbientOcclusionOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setBloomOptions")
internal external fun FilaView_setBloomOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getBloomOptions")
internal external fun FilaView_getBloomOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setFogOptions")
internal external fun FilaView_setFogOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getFogOptions")
internal external fun FilaView_getFogOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setDepthOfFieldOptions")
internal external fun FilaView_setDepthOfFieldOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getDepthOfFieldOptions")
internal external fun FilaView_getDepthOfFieldOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setVignetteOptions")
internal external fun FilaView_setVignetteOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getVignetteOptions")
internal external fun FilaView_getVignetteOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setDithering")
internal external fun FilaView_setDithering(self: NativePointer, dithering: Int)

@ExternalSymbolName("FilaView_getDithering")
internal external fun FilaView_getDithering(self: NativePointer): Int

@ExternalSymbolName("FilaView_setDynamicResolutionOptions")
internal external fun FilaView_setDynamicResolutionOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getDynamicResolutionOptions")
internal external fun FilaView_getDynamicResolutionOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_getLastDynamicResolutionScale")
internal external fun FilaView_getLastDynamicResolutionScale(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setRenderQuality")
internal external fun FilaView_setRenderQuality(self: NativePointer, renderQuality: NativePointer)

@ExternalSymbolName("FilaView_getRenderQuality")
internal external fun FilaView_getRenderQuality(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setDynamicLightingOptions")
internal external fun FilaView_setDynamicLightingOptions(self: NativePointer, zLightNear: Float, zLightFar: Float)

@ExternalSymbolName("FilaView_setGridSize")
internal external fun FilaView_setGridSize(self: NativePointer, size: Double)

@ExternalSymbolName("FilaView_getGridSize")
internal external fun FilaView_getGridSize(self: NativePointer): Double

@ExternalSymbolName("FilaView_getEffectiveGridSize")
internal external fun FilaView_getEffectiveGridSize(self: NativePointer): Double

@ExternalSymbolName("FilaView_setShadowType")
internal external fun FilaView_setShadowType(self: NativePointer, shadow: Int)

@ExternalSymbolName("FilaView_getShadowType")
internal external fun FilaView_getShadowType(self: NativePointer): Int

@ExternalSymbolName("FilaView_setVsmShadowOptions")
internal external fun FilaView_setVsmShadowOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getVsmShadowOptions")
internal external fun FilaView_getVsmShadowOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setSoftShadowOptions")
internal external fun FilaView_setSoftShadowOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getSoftShadowOptions")
internal external fun FilaView_getSoftShadowOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setPostProcessingEnabled")
internal external fun FilaView_setPostProcessingEnabled(self: NativePointer, enabled: Boolean)

@ExternalSymbolName("FilaView_isPostProcessingEnabled")
internal external fun FilaView_isPostProcessingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setFrontFaceWindingInverted")
internal external fun FilaView_setFrontFaceWindingInverted(self: NativePointer, inverted: Boolean)

@ExternalSymbolName("FilaView_isFrontFaceWindingInverted")
internal external fun FilaView_isFrontFaceWindingInverted(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setTransparentPickingEnabled")
internal external fun FilaView_setTransparentPickingEnabled(self: NativePointer, enabled: Boolean)

@ExternalSymbolName("FilaView_isTransparentPickingEnabled")
internal external fun FilaView_isTransparentPickingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setStencilBufferEnabled")
internal external fun FilaView_setStencilBufferEnabled(self: NativePointer, enabled: Boolean)

@ExternalSymbolName("FilaView_isStencilBufferEnabled")
internal external fun FilaView_isStencilBufferEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setStereoscopicOptions")
internal external fun FilaView_setStereoscopicOptions(self: NativePointer, options: NativePointer)

@ExternalSymbolName("FilaView_getStereoscopicOptions")
internal external fun FilaView_getStereoscopicOptions(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaView_setFrustumCullingEnabled")
internal external fun FilaView_setFrustumCullingEnabled(self: NativePointer, culling: Boolean)

@ExternalSymbolName("FilaView_isFrustumCullingEnabled")
internal external fun FilaView_isFrustumCullingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaView_setMaterialGlobal")
internal external fun FilaView_setMaterialGlobal(self: NativePointer, index: Int, value: NativePointer)

@ExternalSymbolName("FilaView_getMaterialGlobal")
internal external fun FilaView_getMaterialGlobal(self: NativePointer, index: Int, out: NativePointer)

@ExternalSymbolName("FilaView_getFogEntity")
internal external fun FilaView_getFogEntity(self: NativePointer): Int

@ExternalSymbolName("FilaView_getVisibleRenderableCount")
internal external fun FilaView_getVisibleRenderableCount(self: NativePointer): Int

@ExternalSymbolName("FilaView_clearFrameHistory")
internal external fun FilaView_clearFrameHistory(self: NativePointer, engine: NativePointer)
