// Generated by generateKotlinExternals from c/filament/generated/FilaTextureSampler.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaTextureSampler_create")
internal external fun FilaTextureSampler_create(): NativePointer

@ExternalSymbolName("FilaTextureSampler_create_MagFilter_WrapMode")
internal external fun FilaTextureSampler_create_MagFilter_WrapMode(minMag: Int, str: Int): NativePointer

@ExternalSymbolName("FilaTextureSampler_create_MinFilter_MagFilter_WrapMode")
internal external fun FilaTextureSampler_create_MinFilter_MagFilter_WrapMode(min: Int, mag: Int, str: Int): NativePointer

@ExternalSymbolName("FilaTextureSampler_create_MinFilter_MagFilter_WrapMode_WrapMode_WrapMode")
internal external fun FilaTextureSampler_create_MinFilter_MagFilter_WrapMode_WrapMode_WrapMode(min: Int, mag: Int, s: Int, t: Int, r: Int): NativePointer

@ExternalSymbolName("FilaTextureSampler_create_CompareMode_CompareFunc")
internal external fun FilaTextureSampler_create_CompareMode_CompareFunc(mode: Int, func: Int): NativePointer

@ExternalSymbolName("FilaTextureSampler_destroy")
internal external fun FilaTextureSampler_destroy(self: NativePointer)

@ExternalSymbolName("FilaTextureSampler_setMinFilter")
internal external fun FilaTextureSampler_setMinFilter(self: NativePointer, v: Int)

@ExternalSymbolName("FilaTextureSampler_setMagFilter")
internal external fun FilaTextureSampler_setMagFilter(self: NativePointer, v: Int)

@ExternalSymbolName("FilaTextureSampler_setWrapModeS")
internal external fun FilaTextureSampler_setWrapModeS(self: NativePointer, v: Int)

@ExternalSymbolName("FilaTextureSampler_setWrapModeT")
internal external fun FilaTextureSampler_setWrapModeT(self: NativePointer, v: Int)

@ExternalSymbolName("FilaTextureSampler_setWrapModeR")
internal external fun FilaTextureSampler_setWrapModeR(self: NativePointer, v: Int)

@ExternalSymbolName("FilaTextureSampler_setAnisotropy")
internal external fun FilaTextureSampler_setAnisotropy(self: NativePointer, anisotropy: Float)

@ExternalSymbolName("FilaTextureSampler_setCompareMode")
internal external fun FilaTextureSampler_setCompareMode(self: NativePointer, mode: Int, func: Int)

@ExternalSymbolName("FilaTextureSampler_getMinFilter")
internal external fun FilaTextureSampler_getMinFilter(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getMagFilter")
internal external fun FilaTextureSampler_getMagFilter(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getWrapModeS")
internal external fun FilaTextureSampler_getWrapModeS(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getWrapModeT")
internal external fun FilaTextureSampler_getWrapModeT(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getWrapModeR")
internal external fun FilaTextureSampler_getWrapModeR(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getAnisotropy")
internal external fun FilaTextureSampler_getAnisotropy(self: NativePointer): Float

@ExternalSymbolName("FilaTextureSampler_getCompareMode")
internal external fun FilaTextureSampler_getCompareMode(self: NativePointer): Int

@ExternalSymbolName("FilaTextureSampler_getCompareFunc")
internal external fun FilaTextureSampler_getCompareFunc(self: NativePointer): Int
