// Generated by generateKotlinExternals from c/filament/generated/FilaUtilsEntityManager.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaUtilsEntityManager_get")
internal external fun FilaUtilsEntityManager_get(): NativePointer

@ExternalSymbolName("FilaUtilsEntityManager_flushNotifications")
internal external fun FilaUtilsEntityManager_flushNotifications(self: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_getMaxEntityCount")
internal external fun FilaUtilsEntityManager_getMaxEntityCount(): Int

@ExternalSymbolName("FilaUtilsEntityManager_getEntityCount")
internal external fun FilaUtilsEntityManager_getEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaUtilsEntityManager_create_size_t_Entity")
internal external fun FilaUtilsEntityManager_create_size_t_Entity(self: NativePointer, n: Int, entities: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_create")
internal external fun FilaUtilsEntityManager_create(self: NativePointer): Int

@ExternalSymbolName("FilaUtilsEntityManager_destroy_size_t_Entity")
internal external fun FilaUtilsEntityManager_destroy_size_t_Entity(self: NativePointer, n: Int, entities: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_destroy_Entity")
internal external fun FilaUtilsEntityManager_destroy_Entity(self: NativePointer, e: Int)

@ExternalSymbolName("FilaUtilsEntityManager_isAlive")
internal external fun FilaUtilsEntityManager_isAlive(self: NativePointer, e: Int): Boolean

@ExternalSymbolName("FilaUtilsEntityManager_advanceEpoch")
internal external fun FilaUtilsEntityManager_advanceEpoch(self: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_reclaimSafeEpochs")
internal external fun FilaUtilsEntityManager_reclaimSafeEpochs(self: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_getLatestEpochID")
internal external fun FilaUtilsEntityManager_getLatestEpochID(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaUtilsEntityManager_getIndex")
internal external fun FilaUtilsEntityManager_getIndex(e: Int): Int
