// Generated by generateKotlinExternals from c/filament/generated/FilaMaterial.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaMaterialParameterInfo_create")
internal external fun FilaMaterialParameterInfo_create(): NativePointer

@ExternalSymbolName("FilaMaterialParameterInfo_destroy")
internal external fun FilaMaterialParameterInfo_destroy(self: NativePointer)

@ExternalSymbolName("FilaMaterialParameterInfo_getName")
internal external fun FilaMaterialParameterInfo_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterialParameterInfo_getIsSampler")
internal external fun FilaMaterialParameterInfo_getIsSampler(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialParameterInfo_setIsSampler")
internal external fun FilaMaterialParameterInfo_setIsSampler(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterialParameterInfo_getIsSubpass")
internal external fun FilaMaterialParameterInfo_getIsSubpass(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterialParameterInfo_setIsSubpass")
internal external fun FilaMaterialParameterInfo_setIsSubpass(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterialParameterInfo_getType")
internal external fun FilaMaterialParameterInfo_getType(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialParameterInfo_setType")
internal external fun FilaMaterialParameterInfo_setType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialParameterInfo_getSamplerType")
internal external fun FilaMaterialParameterInfo_getSamplerType(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialParameterInfo_setSamplerType")
internal external fun FilaMaterialParameterInfo_setSamplerType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialParameterInfo_getSubpassType")
internal external fun FilaMaterialParameterInfo_getSubpassType(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialParameterInfo_setSubpassType")
internal external fun FilaMaterialParameterInfo_setSubpassType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialParameterInfo_getCount")
internal external fun FilaMaterialParameterInfo_getCount(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialParameterInfo_setCount")
internal external fun FilaMaterialParameterInfo_setCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialParameterInfo_getPrecision")
internal external fun FilaMaterialParameterInfo_getPrecision(self: NativePointer): Int

@ExternalSymbolName("FilaMaterialParameterInfo_setPrecision")
internal external fun FilaMaterialParameterInfo_setPrecision(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterialBuilder_create")
internal external fun FilaMaterialBuilder_create(): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_destroy")
internal external fun FilaMaterialBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaMaterialBuilder_package")
internal external fun FilaMaterialBuilder_package(self: NativePointer, payload: NativePointer, size: Int): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_constant_int32_t")
internal external fun FilaMaterialBuilder_constant_int32_t(self: NativePointer, name: NativePointer, value: Int): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_constant_float")
internal external fun FilaMaterialBuilder_constant_float(self: NativePointer, name: NativePointer, value: Float): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_constant_bool")
internal external fun FilaMaterialBuilder_constant_bool(self: NativePointer, name: NativePointer, value: Boolean): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_sphericalHarmonicsBandCount")
internal external fun FilaMaterialBuilder_sphericalHarmonicsBandCount(self: NativePointer, shBandCount: Int): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_shadowSamplingQuality")
internal external fun FilaMaterialBuilder_shadowSamplingQuality(self: NativePointer, quality: Int): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_uboBatching")
internal external fun FilaMaterialBuilder_uboBatching(self: NativePointer, uboBatchingMode: Int): NativePointer

@ExternalSymbolName("FilaMaterialBuilder_build")
internal external fun FilaMaterialBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_compile_UserVariantFilterMask_CallbackHandler_Invocable")
internal external fun FilaMaterial_compile_UserVariantFilterMask_CallbackHandler_Invocable(self: NativePointer, priority: Int, variants: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterial_compile_UserVariantFilterBit_CallbackHandler_Invocable")
internal external fun FilaMaterial_compile_UserVariantFilterBit_CallbackHandler_Invocable(self: NativePointer, priority: Int, variants: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterial_compile_CallbackHandler_Invocable")
internal external fun FilaMaterial_compile_CallbackHandler_Invocable(self: NativePointer, priority: Int, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer)

@ExternalSymbolName("FilaMaterial_createInstance")
internal external fun FilaMaterial_createInstance(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getName")
internal external fun FilaMaterial_getName(self: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getShading")
internal external fun FilaMaterial_getShading(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getInterpolation")
internal external fun FilaMaterial_getInterpolation(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getBlendingMode")
internal external fun FilaMaterial_getBlendingMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getVertexDomain")
internal external fun FilaMaterial_getVertexDomain(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getSupportedVariants")
internal external fun FilaMaterial_getSupportedVariants(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getMaterialDomain")
internal external fun FilaMaterial_getMaterialDomain(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getCullingMode")
internal external fun FilaMaterial_getCullingMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getTransparencyMode")
internal external fun FilaMaterial_getTransparencyMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_isColorWriteEnabled")
internal external fun FilaMaterial_isColorWriteEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDepthWriteEnabled")
internal external fun FilaMaterial_isDepthWriteEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDepthCullingEnabled")
internal external fun FilaMaterial_isDepthCullingEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isDoubleSided")
internal external fun FilaMaterial_isDoubleSided(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isAlphaToCoverageEnabled")
internal external fun FilaMaterial_isAlphaToCoverageEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_getMaskThreshold")
internal external fun FilaMaterial_getMaskThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaMaterial_hasShadowMultiplier")
internal external fun FilaMaterial_hasShadowMultiplier(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_hasSpecularAntiAliasing")
internal external fun FilaMaterial_hasSpecularAntiAliasing(self: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_getSpecularAntiAliasingVariance")
internal external fun FilaMaterial_getSpecularAntiAliasingVariance(self: NativePointer): Float

@ExternalSymbolName("FilaMaterial_getSpecularAntiAliasingThreshold")
internal external fun FilaMaterial_getSpecularAntiAliasingThreshold(self: NativePointer): Float

@ExternalSymbolName("FilaMaterial_getRequiredAttributes")
internal external fun FilaMaterial_getRequiredAttributes(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getRefractionMode")
internal external fun FilaMaterial_getRefractionMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getRefractionType")
internal external fun FilaMaterial_getRefractionType(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getReflectionMode")
internal external fun FilaMaterial_getReflectionMode(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getFeatureLevel")
internal external fun FilaMaterial_getFeatureLevel(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_getParameterCount")
internal external fun FilaMaterial_getParameterCount(self: NativePointer): Int

@ExternalSymbolName("FilaMaterial_hasParameter_char")
internal external fun FilaMaterial_hasParameter_char(self: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_hasParameter_string_view")
internal external fun FilaMaterial_hasParameter_string_view(self: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_isSampler")
internal external fun FilaMaterial_isSampler(self: NativePointer, name: NativePointer): Boolean

@ExternalSymbolName("FilaMaterial_getSource")
internal external fun FilaMaterial_getSource(self: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_getParameterTransformName")
internal external fun FilaMaterial_getParameterTransformName(self: NativePointer, samplerName: NativePointer): NativePointer

@ExternalSymbolName("FilaMaterial_setDefaultParameter_Texture_TextureSampler")
internal external fun FilaMaterial_setDefaultParameter_Texture_TextureSampler(self: NativePointer, name: NativePointer, texture: NativePointer, sampler: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_RgbType_float3")
internal external fun FilaMaterial_setDefaultParameter_RgbType_float3(self: NativePointer, name: NativePointer, type: Int, color: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_RgbaType_float4")
internal external fun FilaMaterial_setDefaultParameter_RgbaType_float4(self: NativePointer, name: NativePointer, type: Int, color: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float")
internal external fun FilaMaterial_setDefaultParameter_float(self: NativePointer, name: NativePointer, value: Float)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int32_t")
internal external fun FilaMaterial_setDefaultParameter_int32_t(self: NativePointer, name: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint32_t")
internal external fun FilaMaterial_setDefaultParameter_uint32_t(self: NativePointer, name: NativePointer, value: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int2")
internal external fun FilaMaterial_setDefaultParameter_int2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int3")
internal external fun FilaMaterial_setDefaultParameter_int3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int4")
internal external fun FilaMaterial_setDefaultParameter_int4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint2")
internal external fun FilaMaterial_setDefaultParameter_uint2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint3")
internal external fun FilaMaterial_setDefaultParameter_uint3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint4")
internal external fun FilaMaterial_setDefaultParameter_uint4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float2")
internal external fun FilaMaterial_setDefaultParameter_float2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float3")
internal external fun FilaMaterial_setDefaultParameter_float3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float4")
internal external fun FilaMaterial_setDefaultParameter_float4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_mat3f")
internal external fun FilaMaterial_setDefaultParameter_mat3f(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_mat4f")
internal external fun FilaMaterial_setDefaultParameter_mat4f(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool")
internal external fun FilaMaterial_setDefaultParameter_bool(self: NativePointer, name: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool2")
internal external fun FilaMaterial_setDefaultParameter_bool2(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool3")
internal external fun FilaMaterial_setDefaultParameter_bool3(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool4")
internal external fun FilaMaterial_setDefaultParameter_bool4(self: NativePointer, name: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float_size_t")
internal external fun FilaMaterial_setDefaultParameter_float_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int32_t_size_t")
internal external fun FilaMaterial_setDefaultParameter_int32_t_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint32_t_size_t")
internal external fun FilaMaterial_setDefaultParameter_uint32_t_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int2_size_t")
internal external fun FilaMaterial_setDefaultParameter_int2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int3_size_t")
internal external fun FilaMaterial_setDefaultParameter_int3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_int4_size_t")
internal external fun FilaMaterial_setDefaultParameter_int4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint2_size_t")
internal external fun FilaMaterial_setDefaultParameter_uint2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint3_size_t")
internal external fun FilaMaterial_setDefaultParameter_uint3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_uint4_size_t")
internal external fun FilaMaterial_setDefaultParameter_uint4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float2_size_t")
internal external fun FilaMaterial_setDefaultParameter_float2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float3_size_t")
internal external fun FilaMaterial_setDefaultParameter_float3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_float4_size_t")
internal external fun FilaMaterial_setDefaultParameter_float4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_mat3f_size_t")
internal external fun FilaMaterial_setDefaultParameter_mat3f_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_mat4f_size_t")
internal external fun FilaMaterial_setDefaultParameter_mat4f_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool_size_t")
internal external fun FilaMaterial_setDefaultParameter_bool_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool2_size_t")
internal external fun FilaMaterial_setDefaultParameter_bool2_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool3_size_t")
internal external fun FilaMaterial_setDefaultParameter_bool3_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_setDefaultParameter_bool4_size_t")
internal external fun FilaMaterial_setDefaultParameter_bool4_size_t(self: NativePointer, name: NativePointer, values: NativePointer, count: Int)

@ExternalSymbolName("FilaMaterial_getDefaultInstance")
internal external fun FilaMaterial_getDefaultInstance(self: NativePointer): NativePointer
