// Generated by generateKotlinExternals from c/filament/generated/FilaIndexBuffer.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_create")
internal external fun FilaIndexBufferBuilder_create(): NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_destroy")
internal external fun FilaIndexBufferBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaIndexBufferBuilder_indexCount")
internal external fun FilaIndexBufferBuilder_indexCount(self: NativePointer, indexCount: Int): NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_bufferType")
internal external fun FilaIndexBufferBuilder_bufferType(self: NativePointer, indexType: Int): NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_name")
internal external fun FilaIndexBufferBuilder_name(self: NativePointer, name: NativePointer): NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_async")
internal external fun FilaIndexBufferBuilder_async(self: NativePointer, handler: NativePointer, callback: NativePointer, user: NativePointer): NativePointer

@ExternalSymbolName("FilaIndexBufferBuilder_build")
internal external fun FilaIndexBufferBuilder_build(self: NativePointer, engine: NativePointer): NativePointer

@ExternalSymbolName("FilaIndexBuffer_setBuffer")
internal external fun FilaIndexBuffer_setBuffer(self: NativePointer, engine: NativePointer, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer, byteOffset: Int)

@ExternalSymbolName("FilaIndexBuffer_setBufferAsync")
internal external fun FilaIndexBuffer_setBufferAsync(self: NativePointer, engine: NativePointer, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer, byteOffset: Int, handler: NativePointer, callback: NativePointer, user: NativePointer): Int

@ExternalSymbolName("FilaIndexBuffer_getIndexCount")
internal external fun FilaIndexBuffer_getIndexCount(self: NativePointer): Int

@ExternalSymbolName("FilaIndexBuffer_isCreationComplete")
internal external fun FilaIndexBuffer_isCreationComplete(self: NativePointer): Boolean
