// Generated by generateKotlinExternals from c/filament/generated/FilaBox.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaBox_create")
internal external fun FilaBox_create(): NativePointer

@ExternalSymbolName("FilaBox_destroy")
internal external fun FilaBox_destroy(self: NativePointer)

@ExternalSymbolName("FilaBox_isEmpty")
internal external fun FilaBox_isEmpty(self: NativePointer): Boolean

@ExternalSymbolName("FilaBox_getMin")
internal external fun FilaBox_getMin(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_getMax")
internal external fun FilaBox_getMax(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_set")
internal external fun FilaBox_set(self: NativePointer, min: NativePointer, max: NativePointer): NativePointer

@ExternalSymbolName("FilaBox_unionSelf")
internal external fun FilaBox_unionSelf(self: NativePointer, box: NativePointer): NativePointer

@ExternalSymbolName("FilaBox_translateTo")
internal external fun FilaBox_translateTo(self: NativePointer, tr: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_getBoundingSphere")
internal external fun FilaBox_getBoundingSphere(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_transform")
internal external fun FilaBox_transform(m: NativePointer, t: NativePointer, box: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_getCenter")
internal external fun FilaBox_getCenter(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_setCenter")
internal external fun FilaBox_setCenter(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaBox_getHalfExtent")
internal external fun FilaBox_getHalfExtent(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaBox_setHalfExtent")
internal external fun FilaBox_setHalfExtent(self: NativePointer, value: NativePointer)
