// Generated by generateKotlinExternals from c/filament/manual/FilaSwapChainManual.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaSwapChain_setFrameScheduledCallback")
internal external fun FilaSwapChain_setFrameScheduledCallback(self: NativePointer, handler: NativePointer, callback: NativePointer, callbackUser: NativePointer, flags: Long)
