// Generated by generateKotlinExternals from c/filament/generated/FilaExposure.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaExposure_ev100_Camera")
internal external fun FilaExposure_ev100_Camera(camera: NativePointer): Float

@ExternalSymbolName("FilaExposure_ev100_float_float_float")
internal external fun FilaExposure_ev100_float_float_float(aperture: Float, shutterSpeed: Float, sensitivity: Float): Float

@ExternalSymbolName("FilaExposure_ev100FromLuminance")
internal external fun FilaExposure_ev100FromLuminance(luminance: Float): Float

@ExternalSymbolName("FilaExposure_ev100FromIlluminance")
internal external fun FilaExposure_ev100FromIlluminance(illuminance: Float): Float

@ExternalSymbolName("FilaExposure_exposure_Camera")
internal external fun FilaExposure_exposure_Camera(camera: NativePointer): Float

@ExternalSymbolName("FilaExposure_exposure_float_float_float")
internal external fun FilaExposure_exposure_float_float_float(aperture: Float, shutterSpeed: Float, sensitivity: Float): Float

@ExternalSymbolName("FilaExposure_exposure_float")
internal external fun FilaExposure_exposure_float(ev100: Float): Float

@ExternalSymbolName("FilaExposure_luminance_Camera")
internal external fun FilaExposure_luminance_Camera(camera: NativePointer): Float

@ExternalSymbolName("FilaExposure_luminance_float_float_float")
internal external fun FilaExposure_luminance_float_float_float(aperture: Float, shutterSpeed: Float, sensitivity: Float): Float

@ExternalSymbolName("FilaExposure_luminance_float")
internal external fun FilaExposure_luminance_float(ev100: Float): Float

@ExternalSymbolName("FilaExposure_illuminance_Camera")
internal external fun FilaExposure_illuminance_Camera(camera: NativePointer): Float

@ExternalSymbolName("FilaExposure_illuminance_float_float_float")
internal external fun FilaExposure_illuminance_float_float_float(aperture: Float, shutterSpeed: Float, sensitivity: Float): Float

@ExternalSymbolName("FilaExposure_illuminance_float")
internal external fun FilaExposure_illuminance_float(ev100: Float): Float
