// Generated by generateKotlinExternals from c/filament/generated/FilaMultiSampleAntiAliasingOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_create")
internal external fun FilaMultiSampleAntiAliasingOptions_create(): NativePointer

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_destroy")
internal external fun FilaMultiSampleAntiAliasingOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_getEnabled")
internal external fun FilaMultiSampleAntiAliasingOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_setEnabled")
internal external fun FilaMultiSampleAntiAliasingOptions_setEnabled(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_getSampleCount")
internal external fun FilaMultiSampleAntiAliasingOptions_getSampleCount(self: NativePointer): Int

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_setSampleCount")
internal external fun FilaMultiSampleAntiAliasingOptions_setSampleCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_getCustomResolve")
internal external fun FilaMultiSampleAntiAliasingOptions_getCustomResolve(self: NativePointer): Boolean

@ExternalSymbolName("FilaMultiSampleAntiAliasingOptions_setCustomResolve")
internal external fun FilaMultiSampleAntiAliasingOptions_setCustomResolve(self: NativePointer, value: Boolean)
