// Generated by generateKotlinExternals from c/filament/generated/FilaGuardBandOptions.h; do not edit.
package io.github.erkko68.filament.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGuardBandOptions_create")
internal external fun FilaGuardBandOptions_create(): NativePointer

@ExternalSymbolName("FilaGuardBandOptions_destroy")
internal external fun FilaGuardBandOptions_destroy(self: NativePointer)

@ExternalSymbolName("FilaGuardBandOptions_getEnabled")
internal external fun FilaGuardBandOptions_getEnabled(self: NativePointer): Boolean

@ExternalSymbolName("FilaGuardBandOptions_setEnabled")
internal external fun FilaGuardBandOptions_setEnabled(self: NativePointer, value: Boolean)
