// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioMaterialKey.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioMaterialKey_create")
internal external fun FilaGltfioMaterialKey_create(): NativePointer

@ExternalSymbolName("FilaGltfioMaterialKey_destroy")
internal external fun FilaGltfioMaterialKey_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioMaterialKey_getDoubleSided")
internal external fun FilaGltfioMaterialKey_getDoubleSided(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setDoubleSided")
internal external fun FilaGltfioMaterialKey_setDoubleSided(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getUnlit")
internal external fun FilaGltfioMaterialKey_getUnlit(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setUnlit")
internal external fun FilaGltfioMaterialKey_setUnlit(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasVertexColors")
internal external fun FilaGltfioMaterialKey_getHasVertexColors(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasVertexColors")
internal external fun FilaGltfioMaterialKey_setHasVertexColors(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasBaseColorTexture")
internal external fun FilaGltfioMaterialKey_getHasBaseColorTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasBaseColorTexture")
internal external fun FilaGltfioMaterialKey_setHasBaseColorTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasNormalTexture")
internal external fun FilaGltfioMaterialKey_getHasNormalTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasNormalTexture")
internal external fun FilaGltfioMaterialKey_setHasNormalTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasOcclusionTexture")
internal external fun FilaGltfioMaterialKey_getHasOcclusionTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasOcclusionTexture")
internal external fun FilaGltfioMaterialKey_setHasOcclusionTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasEmissiveTexture")
internal external fun FilaGltfioMaterialKey_getHasEmissiveTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasEmissiveTexture")
internal external fun FilaGltfioMaterialKey_setHasEmissiveTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getUseSpecularGlossiness")
internal external fun FilaGltfioMaterialKey_getUseSpecularGlossiness(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setUseSpecularGlossiness")
internal external fun FilaGltfioMaterialKey_setUseSpecularGlossiness(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getAlphaMode")
internal external fun FilaGltfioMaterialKey_getAlphaMode(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setAlphaMode")
internal external fun FilaGltfioMaterialKey_setAlphaMode(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getEnableDiagnostics")
internal external fun FilaGltfioMaterialKey_getEnableDiagnostics(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setEnableDiagnostics")
internal external fun FilaGltfioMaterialKey_setEnableDiagnostics(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasMetallicRoughnessTexture")
internal external fun FilaGltfioMaterialKey_getHasMetallicRoughnessTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasMetallicRoughnessTexture")
internal external fun FilaGltfioMaterialKey_setHasMetallicRoughnessTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getMetallicRoughnessUV")
internal external fun FilaGltfioMaterialKey_getMetallicRoughnessUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setMetallicRoughnessUV")
internal external fun FilaGltfioMaterialKey_setMetallicRoughnessUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSpecularGlossinessTexture")
internal external fun FilaGltfioMaterialKey_getHasSpecularGlossinessTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSpecularGlossinessTexture")
internal external fun FilaGltfioMaterialKey_setHasSpecularGlossinessTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getSpecularGlossinessUV")
internal external fun FilaGltfioMaterialKey_getSpecularGlossinessUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setSpecularGlossinessUV")
internal external fun FilaGltfioMaterialKey_setSpecularGlossinessUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getBaseColorUV")
internal external fun FilaGltfioMaterialKey_getBaseColorUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setBaseColorUV")
internal external fun FilaGltfioMaterialKey_setBaseColorUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasClearCoatTexture")
internal external fun FilaGltfioMaterialKey_getHasClearCoatTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasClearCoatTexture")
internal external fun FilaGltfioMaterialKey_setHasClearCoatTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getClearCoatUV")
internal external fun FilaGltfioMaterialKey_getClearCoatUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setClearCoatUV")
internal external fun FilaGltfioMaterialKey_setClearCoatUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasClearCoatRoughnessTexture")
internal external fun FilaGltfioMaterialKey_getHasClearCoatRoughnessTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasClearCoatRoughnessTexture")
internal external fun FilaGltfioMaterialKey_setHasClearCoatRoughnessTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getClearCoatRoughnessUV")
internal external fun FilaGltfioMaterialKey_getClearCoatRoughnessUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setClearCoatRoughnessUV")
internal external fun FilaGltfioMaterialKey_setClearCoatRoughnessUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasClearCoatNormalTexture")
internal external fun FilaGltfioMaterialKey_getHasClearCoatNormalTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasClearCoatNormalTexture")
internal external fun FilaGltfioMaterialKey_setHasClearCoatNormalTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getClearCoatNormalUV")
internal external fun FilaGltfioMaterialKey_getClearCoatNormalUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setClearCoatNormalUV")
internal external fun FilaGltfioMaterialKey_setClearCoatNormalUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasClearCoat")
internal external fun FilaGltfioMaterialKey_getHasClearCoat(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasClearCoat")
internal external fun FilaGltfioMaterialKey_setHasClearCoat(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasTransmission")
internal external fun FilaGltfioMaterialKey_getHasTransmission(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasTransmission")
internal external fun FilaGltfioMaterialKey_setHasTransmission(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasTextureTransforms")
internal external fun FilaGltfioMaterialKey_getHasTextureTransforms(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasTextureTransforms")
internal external fun FilaGltfioMaterialKey_setHasTextureTransforms(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getEmissiveUV")
internal external fun FilaGltfioMaterialKey_getEmissiveUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setEmissiveUV")
internal external fun FilaGltfioMaterialKey_setEmissiveUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getAoUV")
internal external fun FilaGltfioMaterialKey_getAoUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setAoUV")
internal external fun FilaGltfioMaterialKey_setAoUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getNormalUV")
internal external fun FilaGltfioMaterialKey_getNormalUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setNormalUV")
internal external fun FilaGltfioMaterialKey_setNormalUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasTransmissionTexture")
internal external fun FilaGltfioMaterialKey_getHasTransmissionTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasTransmissionTexture")
internal external fun FilaGltfioMaterialKey_setHasTransmissionTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getTransmissionUV")
internal external fun FilaGltfioMaterialKey_getTransmissionUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setTransmissionUV")
internal external fun FilaGltfioMaterialKey_setTransmissionUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSheenColorTexture")
internal external fun FilaGltfioMaterialKey_getHasSheenColorTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSheenColorTexture")
internal external fun FilaGltfioMaterialKey_setHasSheenColorTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getSheenColorUV")
internal external fun FilaGltfioMaterialKey_getSheenColorUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setSheenColorUV")
internal external fun FilaGltfioMaterialKey_setSheenColorUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSheenRoughnessTexture")
internal external fun FilaGltfioMaterialKey_getHasSheenRoughnessTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSheenRoughnessTexture")
internal external fun FilaGltfioMaterialKey_setHasSheenRoughnessTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getSheenRoughnessUV")
internal external fun FilaGltfioMaterialKey_getSheenRoughnessUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setSheenRoughnessUV")
internal external fun FilaGltfioMaterialKey_setSheenRoughnessUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasVolumeThicknessTexture")
internal external fun FilaGltfioMaterialKey_getHasVolumeThicknessTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasVolumeThicknessTexture")
internal external fun FilaGltfioMaterialKey_setHasVolumeThicknessTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getVolumeThicknessUV")
internal external fun FilaGltfioMaterialKey_getVolumeThicknessUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setVolumeThicknessUV")
internal external fun FilaGltfioMaterialKey_setVolumeThicknessUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSheen")
internal external fun FilaGltfioMaterialKey_getHasSheen(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSheen")
internal external fun FilaGltfioMaterialKey_setHasSheen(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasIOR")
internal external fun FilaGltfioMaterialKey_getHasIOR(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasIOR")
internal external fun FilaGltfioMaterialKey_setHasIOR(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasVolume")
internal external fun FilaGltfioMaterialKey_getHasVolume(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasVolume")
internal external fun FilaGltfioMaterialKey_setHasVolume(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasDispersion")
internal external fun FilaGltfioMaterialKey_getHasDispersion(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasDispersion")
internal external fun FilaGltfioMaterialKey_setHasDispersion(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSpecular")
internal external fun FilaGltfioMaterialKey_getHasSpecular(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSpecular")
internal external fun FilaGltfioMaterialKey_setHasSpecular(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSpecularTexture")
internal external fun FilaGltfioMaterialKey_getHasSpecularTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSpecularTexture")
internal external fun FilaGltfioMaterialKey_setHasSpecularTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getHasSpecularColorTexture")
internal external fun FilaGltfioMaterialKey_getHasSpecularColorTexture(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioMaterialKey_setHasSpecularColorTexture")
internal external fun FilaGltfioMaterialKey_setHasSpecularColorTexture(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGltfioMaterialKey_getSpecularTextureUV")
internal external fun FilaGltfioMaterialKey_getSpecularTextureUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setSpecularTextureUV")
internal external fun FilaGltfioMaterialKey_setSpecularTextureUV(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGltfioMaterialKey_getSpecularColorTextureUV")
internal external fun FilaGltfioMaterialKey_getSpecularColorTextureUV(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialKey_setSpecularColorTextureUV")
internal external fun FilaGltfioMaterialKey_setSpecularColorTextureUV(self: NativePointer, value: Int)
