// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioAssetConfiguration.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioAssetConfiguration_create")
internal external fun FilaGltfioAssetConfiguration_create(): NativePointer

@ExternalSymbolName("FilaGltfioAssetConfiguration_destroy")
internal external fun FilaGltfioAssetConfiguration_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioAssetConfiguration_getEngine")
internal external fun FilaGltfioAssetConfiguration_getEngine(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetConfiguration_setEngine")
internal external fun FilaGltfioAssetConfiguration_setEngine(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaGltfioAssetConfiguration_getMaterials")
internal external fun FilaGltfioAssetConfiguration_getMaterials(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetConfiguration_setMaterials")
internal external fun FilaGltfioAssetConfiguration_setMaterials(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaGltfioAssetConfiguration_getEntities")
internal external fun FilaGltfioAssetConfiguration_getEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetConfiguration_setEntities")
internal external fun FilaGltfioAssetConfiguration_setEntities(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaGltfioAssetConfiguration_getDefaultNodeName")
internal external fun FilaGltfioAssetConfiguration_getDefaultNodeName(self: NativePointer): NativePointer
