// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioAssetLoader.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_create")
internal external fun FilaGltfioAssetLoader_create(config: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_destroy")
internal external fun FilaGltfioAssetLoader_destroy(loader: NativePointer)

@ExternalSymbolName("FilaGltfioAssetLoader_createAsset")
internal external fun FilaGltfioAssetLoader_createAsset(self: NativePointer, bytes: NativePointer, numBytes: Int): NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_createInstancedAsset")
internal external fun FilaGltfioAssetLoader_createInstancedAsset(self: NativePointer, bytes: NativePointer, numBytes: Int, instances: NativePointer, numInstances: Int): NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_createInstance")
internal external fun FilaGltfioAssetLoader_createInstance(self: NativePointer, asset: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_enableDiagnostics")
internal external fun FilaGltfioAssetLoader_enableDiagnostics(self: NativePointer, enable: Boolean)

@ExternalSymbolName("FilaGltfioAssetLoader_destroyAsset")
internal external fun FilaGltfioAssetLoader_destroyAsset(self: NativePointer, asset: NativePointer)

@ExternalSymbolName("FilaGltfioAssetLoader_gc")
internal external fun FilaGltfioAssetLoader_gc(self: NativePointer)

@ExternalSymbolName("FilaGltfioAssetLoader_getMaterials")
internal external fun FilaGltfioAssetLoader_getMaterials(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioAssetLoader_getMaterialsCount")
internal external fun FilaGltfioAssetLoader_getMaterialsCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioAssetLoader_getMaterialProvider")
internal external fun FilaGltfioAssetLoader_getMaterialProvider(self: NativePointer): NativePointer
