// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioMaterialProvider.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioMaterialProvider_destroy")
internal external fun FilaGltfioMaterialProvider_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioMaterialProvider_createMaterialInstance")
internal external fun FilaGltfioMaterialProvider_createMaterialInstance(self: NativePointer, config: NativePointer, uvmap: NativePointer, uvmapCount: Int, label: NativePointer, extras: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioMaterialProvider_getMaterial")
internal external fun FilaGltfioMaterialProvider_getMaterial(self: NativePointer, config: NativePointer, uvmap: NativePointer, uvmapCount: Int, label: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioMaterialProvider_getMaterials")
internal external fun FilaGltfioMaterialProvider_getMaterials(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioMaterialProvider_getMaterialsCount")
internal external fun FilaGltfioMaterialProvider_getMaterialsCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioMaterialProvider_destroyMaterials")
internal external fun FilaGltfioMaterialProvider_destroyMaterials(self: NativePointer)

@ExternalSymbolName("FilaGltfioMaterialProvider_needsDummyData")
internal external fun FilaGltfioMaterialProvider_needsDummyData(self: NativePointer, attrib: Int): Boolean
