// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioResourceConfiguration.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioResourceConfiguration_create")
internal external fun FilaGltfioResourceConfiguration_create(): NativePointer

@ExternalSymbolName("FilaGltfioResourceConfiguration_destroy")
internal external fun FilaGltfioResourceConfiguration_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioResourceConfiguration_getEngine")
internal external fun FilaGltfioResourceConfiguration_getEngine(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioResourceConfiguration_setEngine")
internal external fun FilaGltfioResourceConfiguration_setEngine(self: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaGltfioResourceConfiguration_getNormalizeSkinningWeights")
internal external fun FilaGltfioResourceConfiguration_getNormalizeSkinningWeights(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioResourceConfiguration_setNormalizeSkinningWeights")
internal external fun FilaGltfioResourceConfiguration_setNormalizeSkinningWeights(self: NativePointer, value: Boolean)
