// Generated by generateKotlinExternals from c/gltfio/manual/FilaGltfioManual.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfio_getUberarchiveData")
internal external fun FilaGltfio_getUberarchiveData(): NativePointer

@ExternalSymbolName("FilaGltfio_getUberarchiveSize")
internal external fun FilaGltfio_getUberarchiveSize(): Int

@ExternalSymbolName("FilaGltfioResourceLoader_setConfiguration")
internal external fun FilaGltfioResourceLoader_setConfiguration(self: NativePointer, config: NativePointer)
