// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioAnimator.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioAnimator_applyAnimation")
internal external fun FilaGltfioAnimator_applyAnimation(self: NativePointer, animationIndex: Int, time: Float)

@ExternalSymbolName("FilaGltfioAnimator_updateBoneMatrices")
internal external fun FilaGltfioAnimator_updateBoneMatrices(self: NativePointer)

@ExternalSymbolName("FilaGltfioAnimator_applyCrossFade")
internal external fun FilaGltfioAnimator_applyCrossFade(self: NativePointer, previousAnimIndex: Int, previousAnimTime: Float, alpha: Float)

@ExternalSymbolName("FilaGltfioAnimator_resetBoneMatrices")
internal external fun FilaGltfioAnimator_resetBoneMatrices(self: NativePointer)

@ExternalSymbolName("FilaGltfioAnimator_getAnimationCount")
internal external fun FilaGltfioAnimator_getAnimationCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioAnimator_getAnimationDuration")
internal external fun FilaGltfioAnimator_getAnimationDuration(self: NativePointer, animationIndex: Int): Float

@ExternalSymbolName("FilaGltfioAnimator_getAnimationName")
internal external fun FilaGltfioAnimator_getAnimationName(self: NativePointer, animationIndex: Int): NativePointer
