// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfio.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfio_getNumUvSets")
internal external fun FilaGltfio_getNumUvSets(uvmap: NativePointer, uvmapCount: Int): Int

@ExternalSymbolName("FilaGltfio_constrainMaterial")
internal external fun FilaGltfio_constrainMaterial(key: NativePointer, uvmap: NativePointer, uvmapCount: Int)

@ExternalSymbolName("FilaGltfio_createUbershaderProvider")
internal external fun FilaGltfio_createUbershaderProvider(engine: NativePointer, archive: NativePointer, archiveByteCount: Int): NativePointer

@ExternalSymbolName("FilaGltfio_createStbProvider")
internal external fun FilaGltfio_createStbProvider(engine: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfio_createKtx2Provider")
internal external fun FilaGltfio_createKtx2Provider(engine: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfio_createWebpProvider")
internal external fun FilaGltfio_createWebpProvider(engine: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfio_isWebpSupported")
internal external fun FilaGltfio_isWebpSupported(): Boolean
