// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioResourceLoader.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioResourceLoader_create")
internal external fun FilaGltfioResourceLoader_create(config: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioResourceLoader_destroy")
internal external fun FilaGltfioResourceLoader_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioResourceLoader_addResourceData")
internal external fun FilaGltfioResourceLoader_addResourceData(self: NativePointer, uri: NativePointer, buffer: NativePointer, bufferSize: Int, bufferCallback: NativePointer, bufferUser: NativePointer)

@ExternalSymbolName("FilaGltfioResourceLoader_addTextureProvider")
internal external fun FilaGltfioResourceLoader_addTextureProvider(self: NativePointer, mimeType: NativePointer, provider: NativePointer)

@ExternalSymbolName("FilaGltfioResourceLoader_hasResourceData")
internal external fun FilaGltfioResourceLoader_hasResourceData(self: NativePointer, uri: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioResourceLoader_evictResourceData")
internal external fun FilaGltfioResourceLoader_evictResourceData(self: NativePointer)

@ExternalSymbolName("FilaGltfioResourceLoader_loadResources")
internal external fun FilaGltfioResourceLoader_loadResources(self: NativePointer, asset: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioResourceLoader_asyncBeginLoad")
internal external fun FilaGltfioResourceLoader_asyncBeginLoad(self: NativePointer, asset: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioResourceLoader_asyncGetLoadProgress")
internal external fun FilaGltfioResourceLoader_asyncGetLoadProgress(self: NativePointer): Float

@ExternalSymbolName("FilaGltfioResourceLoader_asyncUpdateLoad")
internal external fun FilaGltfioResourceLoader_asyncUpdateLoad(self: NativePointer)

@ExternalSymbolName("FilaGltfioResourceLoader_asyncCancelLoad")
internal external fun FilaGltfioResourceLoader_asyncCancelLoad(self: NativePointer)
