// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioFilamentAsset.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getEntities")
internal external fun FilaGltfioFilamentAsset_getEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getEntityCount")
internal external fun FilaGltfioFilamentAsset_getEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getLightEntities")
internal external fun FilaGltfioFilamentAsset_getLightEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getLightEntityCount")
internal external fun FilaGltfioFilamentAsset_getLightEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getRenderableEntities")
internal external fun FilaGltfioFilamentAsset_getRenderableEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getRenderableEntityCount")
internal external fun FilaGltfioFilamentAsset_getRenderableEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getCameraEntities")
internal external fun FilaGltfioFilamentAsset_getCameraEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getCameraEntityCount")
internal external fun FilaGltfioFilamentAsset_getCameraEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getRoot")
internal external fun FilaGltfioFilamentAsset_getRoot(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_popRenderable")
internal external fun FilaGltfioFilamentAsset_popRenderable(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_popRenderables")
internal external fun FilaGltfioFilamentAsset_popRenderables(self: NativePointer, entities: NativePointer, count: Int): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getResourceUris")
internal external fun FilaGltfioFilamentAsset_getResourceUris(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getResourceUriCount")
internal external fun FilaGltfioFilamentAsset_getResourceUriCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getBoundingBox")
internal external fun FilaGltfioFilamentAsset_getBoundingBox(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentAsset_getName")
internal external fun FilaGltfioFilamentAsset_getName(self: NativePointer, arg0: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getFirstEntityByName")
internal external fun FilaGltfioFilamentAsset_getFirstEntityByName(self: NativePointer, name: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getEntitiesByName")
internal external fun FilaGltfioFilamentAsset_getEntitiesByName(self: NativePointer, name: NativePointer, entities: NativePointer, maxCount: Int): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getEntitiesByPrefix")
internal external fun FilaGltfioFilamentAsset_getEntitiesByPrefix(self: NativePointer, prefix: NativePointer, entities: NativePointer, maxCount: Int): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getExtras")
internal external fun FilaGltfioFilamentAsset_getExtras(self: NativePointer, entity: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getMorphTargetNameAt")
internal external fun FilaGltfioFilamentAsset_getMorphTargetNameAt(self: NativePointer, entity: Int, targetIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getMorphTargetCountAt")
internal external fun FilaGltfioFilamentAsset_getMorphTargetCountAt(self: NativePointer, entity: Int): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getWireframe")
internal external fun FilaGltfioFilamentAsset_getWireframe(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getEngine")
internal external fun FilaGltfioFilamentAsset_getEngine(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_releaseSourceData")
internal external fun FilaGltfioFilamentAsset_releaseSourceData(self: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentAsset_getSourceAsset")
internal external fun FilaGltfioFilamentAsset_getSourceAsset(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getSceneCount")
internal external fun FilaGltfioFilamentAsset_getSceneCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentAsset_getSceneName")
internal external fun FilaGltfioFilamentAsset_getSceneName(self: NativePointer, sceneIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_addEntitiesToScene")
internal external fun FilaGltfioFilamentAsset_addEntitiesToScene(self: NativePointer, targetScene: NativePointer, entities: NativePointer, count: Int, sceneFilter: Int)

@ExternalSymbolName("FilaGltfioFilamentAsset_detachFilamentComponents")
internal external fun FilaGltfioFilamentAsset_detachFilamentComponents(self: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentAsset_areFilamentComponentsDetached")
internal external fun FilaGltfioFilamentAsset_areFilamentComponentsDetached(self: NativePointer): Boolean

@ExternalSymbolName("FilaGltfioFilamentAsset_getInstance")
internal external fun FilaGltfioFilamentAsset_getInstance(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getAssetInstances")
internal external fun FilaGltfioFilamentAsset_getAssetInstances(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentAsset_getAssetInstanceCount")
internal external fun FilaGltfioFilamentAsset_getAssetInstanceCount(self: NativePointer): Int
