// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioTextureProvider.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioTextureProvider_destroy")
internal external fun FilaGltfioTextureProvider_destroy(self: NativePointer)
