// Generated by generateKotlinExternals from c/gltfio/generated/FilaGltfioFilamentInstance.h; do not edit.
package io.github.erkko68.filament.gltfio.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_create")
internal external fun FilaGltfioFilamentInstance_create(): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_destroy")
internal external fun FilaGltfioFilamentInstance_destroy(self: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentInstance_getAsset")
internal external fun FilaGltfioFilamentInstance_getAsset(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getEntities")
internal external fun FilaGltfioFilamentInstance_getEntities(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getEntityCount")
internal external fun FilaGltfioFilamentInstance_getEntityCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_getRoot")
internal external fun FilaGltfioFilamentInstance_getRoot(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_applyMaterialVariant")
internal external fun FilaGltfioFilamentInstance_applyMaterialVariant(self: NativePointer, variantIndex: Int)

@ExternalSymbolName("FilaGltfioFilamentInstance_getMaterialVariantCount")
internal external fun FilaGltfioFilamentInstance_getMaterialVariantCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_getMaterialVariantName")
internal external fun FilaGltfioFilamentInstance_getMaterialVariantName(self: NativePointer, variantIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getAnimator")
internal external fun FilaGltfioFilamentInstance_getAnimator(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getSkinCount")
internal external fun FilaGltfioFilamentInstance_getSkinCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_getSkinNameAt")
internal external fun FilaGltfioFilamentInstance_getSkinNameAt(self: NativePointer, skinIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getJointCountAt")
internal external fun FilaGltfioFilamentInstance_getJointCountAt(self: NativePointer, skinIndex: Int): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_getJointsAt")
internal external fun FilaGltfioFilamentInstance_getJointsAt(self: NativePointer, skinIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_attachSkin")
internal external fun FilaGltfioFilamentInstance_attachSkin(self: NativePointer, skinIndex: Int, target: Int)

@ExternalSymbolName("FilaGltfioFilamentInstance_detachSkin")
internal external fun FilaGltfioFilamentInstance_detachSkin(self: NativePointer, skinIndex: Int, target: Int)

@ExternalSymbolName("FilaGltfioFilamentInstance_getInverseBindMatricesAt")
internal external fun FilaGltfioFilamentInstance_getInverseBindMatricesAt(self: NativePointer, skinIndex: Int): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_recomputeBoundingBoxes")
internal external fun FilaGltfioFilamentInstance_recomputeBoundingBoxes(self: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentInstance_getBoundingBox")
internal external fun FilaGltfioFilamentInstance_getBoundingBox(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaGltfioFilamentInstance_getMaterialInstances")
internal external fun FilaGltfioFilamentInstance_getMaterialInstances(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGltfioFilamentInstance_getMaterialInstanceCount")
internal external fun FilaGltfioFilamentInstance_getMaterialInstanceCount(self: NativePointer): Int

@ExternalSymbolName("FilaGltfioFilamentInstance_detachMaterialInstances")
internal external fun FilaGltfioFilamentInstance_detachMaterialInstances(self: NativePointer)
