package buildlogic.bindings.wasm

import buildlogic.bindings.ExternalFunction

/**
 * Writes `WASM_ARITIES` (export → parameter count) for :web's export parity test: a Kotlin declaration
 * whose arity differs from the compiled C function has drifted from the header.
 */
object WasmArityTableWriter {
    fun write(functions: List<ExternalFunction>): String = buildString {
        append("// Generated by GenerateBindings. Do not edit.\npackage io.github.erkko68.filament.wasm\n\n")
        append("val WASM_ARITIES: List<Pair<String, Int>> = listOf(\n")
        functions.forEach { append("    \"_${it.symbol}\" to ${it.params.size},\n") }
        append(")\n")
    }
}
