package buildlogic.apigen.gaps

import buildlogic.apigen.ApiHeaders
import buildlogic.apigen.c.cApiWriter
import buildlogic.apigen.kotlin.kotlinExternals
import buildlogic.apigen.kotlin.packageDir
import buildlogic.apigen.relativeHeaders
import org.gradle.api.DefaultTask
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.TaskAction
import org.gradle.api.tasks.UntrackedTask
import org.gradle.process.ExecOperations
import java.io.File
import javax.inject.Inject

/**
 * Writes [report]: each C function the C++ API calls for: bound, and a public Kotlin wrapper calls it (`wrapped`) or none
 * does yet (`unwrapped`); or why it isn't bound (`todo`, `skipped`). Then each enum value and class constant of that API,
 * which no function carries: the Kotlin API declares it (`declared`) or doesn't (`undeclared`; `untyped` when it has no
 * declaration of the enum's name). Committed, so a Filament bump's diff shows what changed and how far it got. Warns when
 * the committed C API or Kotlin externals aren't what the generators would write.
 */
@UntrackedTask(because = "A report to diff, cheap next to reading the AST")
abstract class ApiCoverageTask @Inject constructor(private val exec: ExecOperations) : DefaultTask() {
    @get:Internal abstract val publicHeaders: ConfigurableFileCollection
    @get:Internal abstract val includeDir: DirectoryProperty
    @get:Internal abstract val apiHeadersFile: RegularFileProperty
    @get:Internal abstract val cDir: DirectoryProperty
    @get:Internal abstract val kotlinDir: DirectoryProperty

    /** C module → the Kotlin package of its externals. */
    @get:Internal abstract val packages: MapProperty<String, String>

    @get:Internal abstract val report: RegularFileProperty

    @TaskAction
    fun run() {
        val include = includeDir.get().asFile
        val c = cDir.get().asFile
        val kotlin = kotlinDir.get().asFile
        val apiHeaders = ApiHeaders.parse(apiHeadersFile.get().asFile.readText())
        val headers = relativeHeaders(publicHeaders.files, include)
        val writer = cApiWriter(exec, temporaryDir, include, headers, apiHeaders, c)
        val cFiles = writer.write()
        warnStale("C API", "generateCApi", c, cFiles, apiHeaders.modules.keys.map { "$it/generated" })
        warnStale("Kotlin externals", "generateKotlinExternals", kotlin, kotlinExternals(c, packages.get()), packages.get().map { (m, p) -> packageDir(m, p) })

        // The wrappers: main sources outside capi, comments aside (tests call externals directly).
        val sources = kotlin.walkTopDown().filter { f -> f.extension == "kt" && f.invariantSeparatorsPath.let { MAIN.containsMatchIn(it) && "/capi/" !in it } }
            .sortedBy { it.path }.joinToString("\n") { COMMENT.replace(it.readText(), "") }
        val called = FILA.findAll(sources).mapTo(HashSet()) { it.value }
        val lines = writer.bindings.distinctBy { it.c to it.cpp }.sortedWith(compareBy({ it.c }, { it.cpp })).map { b ->
            val status = b.gap?.substringBefore(':') ?: if (b.c in called) "wrapped" else "unwrapped"
            "${status.padEnd(9)} ${b.c} = ${b.cpp}" + (b.gap?.substringAfter(": ")?.let { "  -- $it" } ?: "")
        }
        val summary = summary(lines, STATUSES)
        val api = writer.api
        val declarations = KotlinDeclarations(sources)
        val values = (api.apiEnums(headers).flatMap { e ->
            // Kotlin names an enum as the API's alias does: Texture.InternalFormat for backend::TextureFormat.
            val scope = declarations.scope(api.aliasesOf(e.name)) ?: return@flatMap listOf("untyped" to e.name)
            e.constants.map { "${e.name}::${it.first}" }.filter { api.skipReason(it) == null }.map { declarations.status(scope, it) to it }
        } + api.apiConstants(headers).map { c ->
            (declarations.scope(listOf(c.substringBeforeLast("::")))?.let { declarations.status(it, c) } ?: "untyped") to c
        }).map { (status, name) -> "${status.padEnd(10)} $name" }
        val valueSummary = summary(values, VALUE_STATUSES)
        report.get().asFile.writeText(
            "# Generated by apiCoverage; do not edit. Each C function the C++ API calls for: bound, and a public Kotlin wrapper\n" +
                "# calls it (wrapped) or none does yet (unwrapped); or why it isn't bound (todo, skipped).\n# $summary\n\n" + lines.joinToString("\n", postfix = "\n") +
                "\n# Each enum value and class constant of that API: the Kotlin API declares it (declared) or doesn't (undeclared);\n" +
                "# untyped: Kotlin has no declaration of the enum's, or the constant's owner's, name.\n# $valueSummary\n\n" + values.joinToString("\n", postfix = "\n"),
        )
        logger.lifecycle("API coverage: $summary; $valueSummary")
        logger.lifecycle("Report: ${report.get().asFile.toURI()} (git diff it to see what changed)")
    }

    private fun summary(lines: List<String>, statuses: List<String>) =
        lines.groupingBy { it.substringBefore(' ') }.eachCount().let { counts -> statuses.joinToString(", ") { "${counts[it] ?: 0} $it" } }

    /** Warns about [expected] files (by path under [root]) that differ from [root], and files under [dirs] it doesn't list. */
    private fun warnStale(what: String, task: String, root: File, expected: Map<String, String>, dirs: List<String>) {
        val onDisk = dirs.flatMap { d -> root.resolve(d).walkTopDown().filter { it.isFile }.map { it.relativeTo(root).invariantSeparatorsPath } }
        val stale = expected.filter { (path, text) -> root.resolve(path).let { !it.isFile || it.readText() != text } }.keys + (onDisk - expected.keys)
        if (stale.isNotEmpty()) logger.warn("The committed $what is stale (${stale.size} files, e.g. ${stale.first()}): run $task")
    }

    private companion object {
        val FILA = Regex("""\bFila\w+""")
        val MAIN = Regex("""/src/\w*Main/""")
        val COMMENT = Regex("""//[^\n]*|/\*[\s\S]*?\*/""")
        val STATUSES = listOf("wrapped", "unwrapped", "todo", "skipped")
        val VALUE_STATUSES = listOf("declared", "undeclared", "untyped")
    }
}
