import java.util.Base64 as JavaBase64

plugins {
    id("filament-kmp-module")
    id("org.jetbrains.compose")
    id("org.jetbrains.kotlin.plugin.compose")
}

composeCompiler {
    // Teaches the compiler that Filament's native handles are stable — see the file for why.
    stabilityConfigurationFiles.add(layout.projectDirectory.file("compose-stability.conf"))

    // Stability/recomposition reports: -PcomposeMetrics. Output lands in build/compose-reports
    // (*-composables.txt, *-classes.txt, *-module.json).
    if (providers.gradleProperty("composeMetrics").isPresent) {
        metricsDestination = layout.buildDirectory.dir("compose-reports")
        reportsDestination = layout.buildDirectory.dir("compose-reports")
    }
}

// ── Embed the built-in .filamat materials as base64 into a generated commonMain source ──
// Resource access differs per platform (JVM classpath / iOS bundle / browser HTTP / Android
// assets) and runtime material compilation (filamat) isn't available on Web, so the standard
// materials are precompiled with `matc` (committed under src/commonMain/materials) and encoded
// into a generated Kotlin object decoded on first use. This makes the bytes available
// identically and synchronously on every target. Regenerate the .filamat blobs with
// `matc -p all -a all` on each filaVersion bump — see docs/upgrading-filament.md.
val materialsInputDir = layout.projectDirectory.dir("src/commonMain/materials")
val materialsGenDir = layout.buildDirectory.dir("generated/embeddedMaterials/kotlin")
val generateEmbeddedMaterials = tasks.register("generateEmbeddedMaterials") {
    val inDir = materialsInputDir.asFile
    val outRoot = materialsGenDir.get().asFile
    inputs.dir(materialsInputDir).withPropertyName("materials")
        .withPathSensitivity(PathSensitivity.RELATIVE)
    outputs.dir(materialsGenDir).withPropertyName("out")
    doLast {
        val files = (inDir.listFiles { f -> f.isFile && f.name.endsWith(".filamat") }
            ?: emptyArray()).sortedBy { it.name }
        val pkgDir = outRoot.resolve("io/github/erkko68/filament/compose/scene")
        pkgDir.mkdirs()
        val sb = StringBuilder()
        sb.appendLine("package io.github.erkko68.filament.compose.scene")
        sb.appendLine()
        sb.appendLine("import kotlin.io.encoding.Base64")
        sb.appendLine("import kotlin.io.encoding.ExperimentalEncodingApi")
        sb.appendLine()
        sb.appendLine("// Generated by :kotlin:filament-compose:generateEmbeddedMaterials from")
        sb.appendLine("// src/commonMain/materials. Do not edit.")
        sb.appendLine("@OptIn(ExperimentalEncodingApi::class)")
        sb.appendLine("internal object EmbeddedMaterials {")
        // A single Kotlin/JVM string constant caps at 64 KB of UTF-8; base64 is ASCII so chunk
        // well under that and concatenate before decoding.
        sb.appendLine("    private fun d(vararg c: String): ByteArray = Base64.decode(c.joinToString(\"\"))")
        for (f in files) {
            // standard_lit.filamat -> standardLit
            val ident = f.nameWithoutExtension
                .split('_')
                .filter { it.isNotEmpty() }
                .mapIndexed { i, p -> if (i == 0) p else p.replaceFirstChar { it.uppercase() } }
                .joinToString("")
            val b64 = JavaBase64.getEncoder().encodeToString(f.readBytes())
            val chunks = b64.chunked(32000)
            sb.appendLine("    val $ident: ByteArray by lazy {")
            sb.appendLine("        d(")
            chunks.forEachIndexed { i, c ->
                sb.appendLine("            \"$c\"" + if (i < chunks.lastIndex) "," else "")
            }
            sb.appendLine("        )")
            sb.appendLine("    }")
        }
        sb.appendLine("}")
        pkgDir.resolve("EmbeddedMaterials.kt").writeText(sb.toString())
    }
}

// ── Embed test .glb assets into a generated commonTest source ────────────────
// Same rationale as the materials above (and mirroring :kotlin:gltfio): the committed .glb in
// src/commonTest/glb is the source of truth, base64-encoded so every target reads it without
// per-platform resource IO. Keep this set minimal — the bytes land in generated Kotlin source.
val generateEmbeddedGlb = registerEmbeddedTestResources(
    taskName = "generateEmbeddedGlb",
    inputDir = "src/commonTest/glb",
    fileExtension = ".glb",
    packageName = "io.github.erkko68.filament.compose.testutils",
    objectName = "EmbeddedGlb",
)

kotlin {
    sourceSets {
        commonMain {
            kotlin.srcDir(generateEmbeddedMaterials)
        }
        named("commonTest") {
            kotlin.srcDir(generateEmbeddedGlb)
        }
        commonMain.dependencies {
            api(project(":kotlin:filament"))
            api(project(":kotlin:filament-utils"))
            api(project(":kotlin:gltfio"))
            api(project(":kotlin:filamat"))
            api(libs.compose.runtime)
            api(libs.compose.foundation)
            api(libs.compose.ui)
        }
        jvmMain.dependencies {
            implementation(compose.desktop.currentOs)
            // Optional: the GPU surface kicks in only when the app itself runs on Nucleus.
            compileOnly(libs.nucleus.decoratedWindowTao)
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation(project(":kotlin:test-support"))
            @OptIn(org.jetbrains.compose.ExperimentalComposeLibrary::class)
            implementation(compose.uiTest)
        }
        // Android instrumented tests: runComposeUiTest needs a host Activity, supplied by the
        // ui-test-manifest artifact (it merges a debug AndroidManifest with a test ComponentActivity).
        // Lives only here — filament-compose is the only module that drives runComposeUiTest.
        named("androidDeviceTest") {
            dependencies {
                implementation(libs.androidx.compose.ui.test.manifest)
                // Override the stale Espresso (3.5.0) that compose ui-test drags in; the old one calls
                // an InputManager method removed in Android 14+, breaking waitForIdle() on-device.
                implementation(libs.androidx.test.espresso.core)
            }
        }
    }
}

// ── Published-artifact size trimming (Maven Central deployment bundle cap) ────
// Two payloads get duplicated across all seven per-target publications and dominate
// the deployment bundle. Neither is useful to a consumer.

// 1. EmbeddedMaterials.kt is 3.3 MB of generated base64. Seven sources jars carry it.
// KMP sources jars are org.gradle.jvm.tasks.Jar, not the bundling.Jar that `Jar` resolves to.
tasks.withType<org.gradle.jvm.tasks.Jar>().matching { it.name.endsWith("SourcesJar") }.configureEach {
    exclude("**/EmbeddedMaterials.kt")
}

// 2. The Compose plugin stages the skiko web runtime (9.8 MB, mostly skiko.wasm) into
//    jsMain resources for app bundling, and Kotlin/JS packs resources into the klib.
//    Consumer apps unpack their own copy. jsTest keeps its (the plugin stages that
//    compilation's resources separately), so Karma still serves skiko.
tasks.named<ProcessResources>("jsProcessResources") {
    exclude("skiko.wasm", "skiko.mjs", "skikod8.mjs", "js-reexport-symbols.mjs")
}
