package buildlogic.bindings.jni

import buildlogic.bindings.ExternalFunction
import buildlogic.bindings.ExternalSource

/**
 * Writes the C side of the JNI bindings: for each external, the `Java_<class>_<name>` function the JVM
 * links it to, forwarding to the C symbol. Only the Kotlin types are known: pointers cross as `jlong` and
 * go through `void*`, which C converts to the declared pointer type; the included Fila* prototypes let
 * the C compiler check everything else.
 */
object JniForwarderWriter {
    fun write(source: ExternalSource, headers: List<String>): String = buildString {
        append("// Generated by GenerateBindings from ${source.file.name}. Do not edit.\n")
        append("#include <jni.h>\n#include <stdint.h>\n\n")
        headers.forEach { append("#include \"$it\"\n") }
        append("\n")
        val jniClass = mangle(source.jvmClass)
        source.functions.forEach { append(forwarder(jniClass, it, "${it.name} in ${source.file.name}")) }
    }

    private fun forwarder(jniClass: String, fn: ExternalFunction, where: String): String {
        val params = fn.params.joinToString("") { ", ${jniType(it.type, where)} ${it.name}" }
        val args = fn.params.joinToString { if (it.type == "NativePointer") "(void*)(intptr_t) ${it.name}" else it.name }
        val call = "${fn.symbol}($args)"
        val body = when (fn.returnType) {
            "Unit" -> "$call;"
            "NativePointer" -> "return (jlong)(intptr_t) $call;"
            "Boolean" -> "return $call ? JNI_TRUE : JNI_FALSE;"
            else -> "return (${jniType(fn.returnType, where)}) $call;"
        }
        val returnType = if (fn.returnType == "Unit") "void" else jniType(fn.returnType, where)
        return "JNIEXPORT $returnType JNICALL Java_${jniClass}_${mangle(fn.name)}(JNIEnv* env, jclass cls$params) {\n    $body\n}\n\n"
    }

    private fun jniType(kotlin: String, where: String) = when (kotlin) {
        "NativePointer", "Long" -> "jlong"
        "Int" -> "jint"
        "Float" -> "jfloat"
        "Double" -> "jdouble"
        "Boolean" -> "jboolean"
        else -> error("No JNI mapping for Kotlin type '$kotlin' ($where)")
    }

    // JNI name mangling: '_' → "_1", '.' → '_' (identifiers here are ASCII).
    private fun mangle(name: String) = name.replace("_", "_1").replace('.', '_')
}
