// Generated by generateKotlinExternals from c/filament-utils/manual/FilaUtilsManual.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaHDRLoader_createTexture")
internal external fun FilaHDRLoader_createTexture(engine: NativePointer, buffer: NativePointer, size: Int, internalFormat: Int): NativePointer

@ExternalSymbolName("FilaTextureLoader_loadTexture")
internal external fun FilaTextureLoader_loadTexture(engine: NativePointer, buffer: NativePointer, size: Int, srgb: Boolean): NativePointer
