// Generated by generateKotlinExternals from c/filament-utils/generated/FilaCamutilsBookmark.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaCamutilsBookmark_create")
internal external fun FilaCamutilsBookmark_create(): NativePointer

@ExternalSymbolName("FilaCamutilsBookmark_destroy")
internal external fun FilaCamutilsBookmark_destroy(self: NativePointer)

@ExternalSymbolName("FilaCamutilsBookmark_interpolate")
internal external fun FilaCamutilsBookmark_interpolate(a: NativePointer, b: NativePointer, t: Double, out: NativePointer)

@ExternalSymbolName("FilaCamutilsBookmark_duration")
internal external fun FilaCamutilsBookmark_duration(a: NativePointer, b: NativePointer): Double
