// Generated by generateKotlinExternals from c/filament-utils/generated/FilaGeometryTranscoder.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGeometryTranscoderConfig_create")
internal external fun FilaGeometryTranscoderConfig_create(): NativePointer

@ExternalSymbolName("FilaGeometryTranscoderConfig_destroy")
internal external fun FilaGeometryTranscoderConfig_destroy(self: NativePointer)

@ExternalSymbolName("FilaGeometryTranscoderConfig_getComponentType")
internal external fun FilaGeometryTranscoderConfig_getComponentType(self: NativePointer): Int

@ExternalSymbolName("FilaGeometryTranscoderConfig_setComponentType")
internal external fun FilaGeometryTranscoderConfig_setComponentType(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGeometryTranscoderConfig_getNormalized")
internal external fun FilaGeometryTranscoderConfig_getNormalized(self: NativePointer): Boolean

@ExternalSymbolName("FilaGeometryTranscoderConfig_setNormalized")
internal external fun FilaGeometryTranscoderConfig_setNormalized(self: NativePointer, value: Boolean)

@ExternalSymbolName("FilaGeometryTranscoderConfig_getComponentCount")
internal external fun FilaGeometryTranscoderConfig_getComponentCount(self: NativePointer): Int

@ExternalSymbolName("FilaGeometryTranscoderConfig_setComponentCount")
internal external fun FilaGeometryTranscoderConfig_setComponentCount(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGeometryTranscoderConfig_getInputStrideBytes")
internal external fun FilaGeometryTranscoderConfig_getInputStrideBytes(self: NativePointer): Int

@ExternalSymbolName("FilaGeometryTranscoderConfig_setInputStrideBytes")
internal external fun FilaGeometryTranscoderConfig_setInputStrideBytes(self: NativePointer, value: Int)

@ExternalSymbolName("FilaGeometryTranscoder_create")
internal external fun FilaGeometryTranscoder_create(config: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometryTranscoder_destroy")
internal external fun FilaGeometryTranscoder_destroy(self: NativePointer)

@ExternalSymbolName("FilaGeometryTranscoder_invoke")
internal external fun FilaGeometryTranscoder_invoke(self: NativePointer, target: NativePointer, source: NativePointer, count: Int): Int
