// Generated by generateKotlinExternals from c/filament-utils/generated/FilaGeometryTangentSpaceMesh.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_create")
internal external fun FilaGeometryTangentSpaceMeshBuilder_create(): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_destroy")
internal external fun FilaGeometryTangentSpaceMeshBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_vertexCount")
internal external fun FilaGeometryTangentSpaceMeshBuilder_vertexCount(self: NativePointer, vertexCount: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_normals")
internal external fun FilaGeometryTangentSpaceMeshBuilder_normals(self: NativePointer, normals: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_tangents")
internal external fun FilaGeometryTangentSpaceMeshBuilder_tangents(self: NativePointer, tangents: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_uvs")
internal external fun FilaGeometryTangentSpaceMeshBuilder_uvs(self: NativePointer, uvs: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_positions")
internal external fun FilaGeometryTangentSpaceMeshBuilder_positions(self: NativePointer, positions: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_triangleCount")
internal external fun FilaGeometryTangentSpaceMeshBuilder_triangleCount(self: NativePointer, triangleCount: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_triangles_uint3")
internal external fun FilaGeometryTangentSpaceMeshBuilder_triangles_uint3(self: NativePointer, triangles: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_triangles_ushort3")
internal external fun FilaGeometryTangentSpaceMeshBuilder_triangles_ushort3(self: NativePointer, triangles: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_algorithm")
internal external fun FilaGeometryTangentSpaceMeshBuilder_algorithm(self: NativePointer, algorithm: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_build")
internal external fun FilaGeometryTangentSpaceMeshBuilder_build(self: NativePointer): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_destroy")
internal external fun FilaGeometryTangentSpaceMesh_destroy(mesh: NativePointer)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getVertexCount")
internal external fun FilaGeometryTangentSpaceMesh_getVertexCount(self: NativePointer): Int

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getPositions")
internal external fun FilaGeometryTangentSpaceMesh_getPositions(self: NativePointer, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getUVs")
internal external fun FilaGeometryTangentSpaceMesh_getUVs(self: NativePointer, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getQuats_quatf_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getQuats_quatf_size_t(self: NativePointer, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getQuats_short4_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getQuats_short4_size_t(self: NativePointer, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getQuats_quath_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getQuats_quath_size_t(self: NativePointer, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getAux_float2_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getAux_float2_size_t(self: NativePointer, attribute: Int, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getAux_float3_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getAux_float3_size_t(self: NativePointer, attribute: Int, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getAux_float4_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getAux_float4_size_t(self: NativePointer, attribute: Int, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getAux_ushort3_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getAux_ushort3_size_t(self: NativePointer, attribute: Int, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getAux_ushort4_size_t")
internal external fun FilaGeometryTangentSpaceMesh_getAux_ushort4_size_t(self: NativePointer, attribute: Int, out_: NativePointer, stride: Int)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getTriangleCount")
internal external fun FilaGeometryTangentSpaceMesh_getTriangleCount(self: NativePointer): Int

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getTriangles_uint3")
internal external fun FilaGeometryTangentSpaceMesh_getTriangles_uint3(self: NativePointer, out_: NativePointer)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_getTriangles_ushort3")
internal external fun FilaGeometryTangentSpaceMesh_getTriangles_ushort3(self: NativePointer, out_: NativePointer)

@ExternalSymbolName("FilaGeometryTangentSpaceMesh_remeshed")
internal external fun FilaGeometryTangentSpaceMesh_remeshed(self: NativePointer): Boolean
