// Generated by generateKotlinExternals from c/filament-utils/manual/FilaImageKtx1BundleManual.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaImageKtx1Bundle_getMetadata")
internal external fun FilaImageKtx1Bundle_getMetadata(self: NativePointer, key: NativePointer, valueSize: NativePointer): NativePointer
