// Generated by generateKotlinExternals from c/filament-utils/generated/FilaImageKtx1Bundle.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaImageKtx1Bundle_create_uint32_t_uint32_t_bool")
internal external fun FilaImageKtx1Bundle_create_uint32_t_uint32_t_bool(numMipLevels: Int, arrayLength: Int, isCubemap: Boolean): NativePointer

@ExternalSymbolName("FilaImageKtx1Bundle_create_uint8_t_uint32_t")
internal external fun FilaImageKtx1Bundle_create_uint8_t_uint32_t(bytes: NativePointer, nbytes: Int): NativePointer

@ExternalSymbolName("FilaImageKtx1Bundle_destroy")
internal external fun FilaImageKtx1Bundle_destroy(self: NativePointer)

@ExternalSymbolName("FilaImageKtx1Bundle_serialize")
internal external fun FilaImageKtx1Bundle_serialize(self: NativePointer, destination: NativePointer, numBytes: Int): Boolean

@ExternalSymbolName("FilaImageKtx1Bundle_getSerializedLength")
internal external fun FilaImageKtx1Bundle_getSerializedLength(self: NativePointer): Int

@ExternalSymbolName("FilaImageKtx1Bundle_setMetadata")
internal external fun FilaImageKtx1Bundle_setMetadata(self: NativePointer, key: NativePointer, value: NativePointer)

@ExternalSymbolName("FilaImageKtx1Bundle_getSphericalHarmonics")
internal external fun FilaImageKtx1Bundle_getSphericalHarmonics(self: NativePointer, result: NativePointer): Boolean

@ExternalSymbolName("FilaImageKtx1Bundle_getNumMipLevels")
internal external fun FilaImageKtx1Bundle_getNumMipLevels(self: NativePointer): Int

@ExternalSymbolName("FilaImageKtx1Bundle_getArrayLength")
internal external fun FilaImageKtx1Bundle_getArrayLength(self: NativePointer): Int

@ExternalSymbolName("FilaImageKtx1Bundle_isCubemap")
internal external fun FilaImageKtx1Bundle_isCubemap(self: NativePointer): Boolean
