// Generated by generateKotlinExternals from c/filament-utils/manual/FilaGeometryTangentSpaceMeshManual.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_aux_float2")
internal external fun FilaGeometryTangentSpaceMeshBuilder_aux_float2(self: NativePointer, attribute: Int, data: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_aux_float3")
internal external fun FilaGeometryTangentSpaceMeshBuilder_aux_float3(self: NativePointer, attribute: Int, data: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_aux_float4")
internal external fun FilaGeometryTangentSpaceMeshBuilder_aux_float4(self: NativePointer, attribute: Int, data: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_aux_ushort3")
internal external fun FilaGeometryTangentSpaceMeshBuilder_aux_ushort3(self: NativePointer, attribute: Int, data: NativePointer, stride: Int): NativePointer

@ExternalSymbolName("FilaGeometryTangentSpaceMeshBuilder_aux_ushort4")
internal external fun FilaGeometryTangentSpaceMeshBuilder_aux_ushort4(self: NativePointer, attribute: Int, data: NativePointer, stride: Int): NativePointer
