// Generated by generateKotlinExternals from c/filament-utils/generated/FilaKtxreaderKtx1Reader.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaKtxreaderKtx1Reader_createTexture_Callback_void")
internal external fun FilaKtxreaderKtx1Reader_createTexture_Callback_void(engine: NativePointer, ktx: NativePointer, srgb: Boolean, callback: NativePointer, userdata: NativePointer): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx1Reader_createTexture")
internal external fun FilaKtxreaderKtx1Reader_createTexture(engine: NativePointer, ktx: NativePointer, srgb: Boolean): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx1Reader_isSrgbTextureFormat")
internal external fun FilaKtxreaderKtx1Reader_isSrgbTextureFormat(format: Int): Boolean
