// Generated by generateKotlinExternals from c/filament-utils/generated/FilaKtxreaderKtx2Reader.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaKtxreaderKtx2ReaderAsync_getTexture")
internal external fun FilaKtxreaderKtx2ReaderAsync_getTexture(self: NativePointer): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx2ReaderAsync_doTranscoding")
internal external fun FilaKtxreaderKtx2ReaderAsync_doTranscoding(self: NativePointer): Int

@ExternalSymbolName("FilaKtxreaderKtx2ReaderAsync_uploadImages")
internal external fun FilaKtxreaderKtx2ReaderAsync_uploadImages(self: NativePointer)

@ExternalSymbolName("FilaKtxreaderKtx2Reader_create")
internal external fun FilaKtxreaderKtx2Reader_create(engine: NativePointer, quiet: Boolean): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx2Reader_destroy")
internal external fun FilaKtxreaderKtx2Reader_destroy(self: NativePointer)

@ExternalSymbolName("FilaKtxreaderKtx2Reader_requestFormat")
internal external fun FilaKtxreaderKtx2Reader_requestFormat(self: NativePointer, format: Int): Int

@ExternalSymbolName("FilaKtxreaderKtx2Reader_unrequestFormat")
internal external fun FilaKtxreaderKtx2Reader_unrequestFormat(self: NativePointer, format: Int)

@ExternalSymbolName("FilaKtxreaderKtx2Reader_load")
internal external fun FilaKtxreaderKtx2Reader_load(self: NativePointer, data: NativePointer, size: Int, transfer: Int): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx2Reader_asyncCreate")
internal external fun FilaKtxreaderKtx2Reader_asyncCreate(self: NativePointer, data: NativePointer, size: Int, transfer: Int): NativePointer

@ExternalSymbolName("FilaKtxreaderKtx2Reader_asyncDestroy")
internal external fun FilaKtxreaderKtx2Reader_asyncDestroy(self: NativePointer, async: NativePointer)
