// Generated by generateKotlinExternals from c/filament-utils/generated/FilaCamutilsManipulator.h; do not edit.
package io.github.erkko68.filament.utils.capi

import io.github.erkko68.filament.interop.ExternalSymbolName
import io.github.erkko68.filament.interop.NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_create")
internal external fun FilaCamutilsManipulatorBuilder_create(): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_destroy")
internal external fun FilaCamutilsManipulatorBuilder_destroy(self: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_viewport")
internal external fun FilaCamutilsManipulatorBuilder_viewport(self: NativePointer, width: Int, height: Int): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_targetPosition")
internal external fun FilaCamutilsManipulatorBuilder_targetPosition(self: NativePointer, x: Float, y: Float, z: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_upVector")
internal external fun FilaCamutilsManipulatorBuilder_upVector(self: NativePointer, x: Float, y: Float, z: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_zoomSpeed")
internal external fun FilaCamutilsManipulatorBuilder_zoomSpeed(self: NativePointer, `val`: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_orbitHomePosition")
internal external fun FilaCamutilsManipulatorBuilder_orbitHomePosition(self: NativePointer, x: Float, y: Float, z: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_orbitSpeed")
internal external fun FilaCamutilsManipulatorBuilder_orbitSpeed(self: NativePointer, x: Float, y: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_fovDirection")
internal external fun FilaCamutilsManipulatorBuilder_fovDirection(self: NativePointer, fov: Int): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_fovDegrees")
internal external fun FilaCamutilsManipulatorBuilder_fovDegrees(self: NativePointer, degrees: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_farPlane")
internal external fun FilaCamutilsManipulatorBuilder_farPlane(self: NativePointer, distance: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_mapExtent")
internal external fun FilaCamutilsManipulatorBuilder_mapExtent(self: NativePointer, worldWidth: Float, worldHeight: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_mapMinDistance")
internal external fun FilaCamutilsManipulatorBuilder_mapMinDistance(self: NativePointer, mindist: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightStartPosition")
internal external fun FilaCamutilsManipulatorBuilder_flightStartPosition(self: NativePointer, x: Float, y: Float, z: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightStartOrientation")
internal external fun FilaCamutilsManipulatorBuilder_flightStartOrientation(self: NativePointer, pitch: Float, yaw: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightMaxMoveSpeed")
internal external fun FilaCamutilsManipulatorBuilder_flightMaxMoveSpeed(self: NativePointer, maxSpeed: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightSpeedSteps")
internal external fun FilaCamutilsManipulatorBuilder_flightSpeedSteps(self: NativePointer, steps: Int): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightPanSpeed")
internal external fun FilaCamutilsManipulatorBuilder_flightPanSpeed(self: NativePointer, x: Float, y: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_flightMoveDamping")
internal external fun FilaCamutilsManipulatorBuilder_flightMoveDamping(self: NativePointer, damping: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_groundPlane")
internal external fun FilaCamutilsManipulatorBuilder_groundPlane(self: NativePointer, a: Float, b: Float, c: Float, d: Float): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_panning")
internal external fun FilaCamutilsManipulatorBuilder_panning(self: NativePointer, enabled: Boolean): NativePointer

@ExternalSymbolName("FilaCamutilsManipulatorBuilder_build")
internal external fun FilaCamutilsManipulatorBuilder_build(self: NativePointer, mode: Int): NativePointer

@ExternalSymbolName("FilaCamutilsManipulator_destroy")
internal external fun FilaCamutilsManipulator_destroy(self: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_getMode")
internal external fun FilaCamutilsManipulator_getMode(self: NativePointer): Int

@ExternalSymbolName("FilaCamutilsManipulator_setViewport")
internal external fun FilaCamutilsManipulator_setViewport(self: NativePointer, width: Int, height: Int)

@ExternalSymbolName("FilaCamutilsManipulator_getLookAt")
internal external fun FilaCamutilsManipulator_getLookAt(self: NativePointer, eyePosition: NativePointer, targetPosition: NativePointer, upward: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_raycast")
internal external fun FilaCamutilsManipulator_raycast(self: NativePointer, x: Int, y: Int, result: NativePointer): Boolean

@ExternalSymbolName("FilaCamutilsManipulator_getRay")
internal external fun FilaCamutilsManipulator_getRay(self: NativePointer, x: Int, y: Int, origin: NativePointer, dir: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_grabBegin")
internal external fun FilaCamutilsManipulator_grabBegin(self: NativePointer, x: Int, y: Int, strafe: Boolean)

@ExternalSymbolName("FilaCamutilsManipulator_grabUpdate")
internal external fun FilaCamutilsManipulator_grabUpdate(self: NativePointer, x: Int, y: Int)

@ExternalSymbolName("FilaCamutilsManipulator_grabEnd")
internal external fun FilaCamutilsManipulator_grabEnd(self: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_keyDown")
internal external fun FilaCamutilsManipulator_keyDown(self: NativePointer, key: Int)

@ExternalSymbolName("FilaCamutilsManipulator_keyUp")
internal external fun FilaCamutilsManipulator_keyUp(self: NativePointer, key: Int)

@ExternalSymbolName("FilaCamutilsManipulator_scroll")
internal external fun FilaCamutilsManipulator_scroll(self: NativePointer, x: Int, y: Int, scrolldelta: Float)

@ExternalSymbolName("FilaCamutilsManipulator_update")
internal external fun FilaCamutilsManipulator_update(self: NativePointer, deltaTime: Float)

@ExternalSymbolName("FilaCamutilsManipulator_getCurrentBookmark")
internal external fun FilaCamutilsManipulator_getCurrentBookmark(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_getHomeBookmark")
internal external fun FilaCamutilsManipulator_getHomeBookmark(self: NativePointer, out: NativePointer)

@ExternalSymbolName("FilaCamutilsManipulator_jumpToBookmark")
internal external fun FilaCamutilsManipulator_jumpToBookmark(self: NativePointer, bookmark: NativePointer)
